### ISSUE TITLE
Retry later if network fails

### ISSUE THREAD

**Issue by eschava** [jpmens/mqttwarn#112]
Have an option to retry warning message sending later (email/push/etc) if now message cannot be send after the networking failure

Could be implemented as part of failover mechanism

**Comment by jpmens** [comment]
Nice idea. It would however require some form of persistence in order to make it fail-safe.

**Comment by otdftr** [comment]
Just an idea: What about using rrdcached?

**Comment by jpmens** [comment]
Added enhancement tag; closing for now.
