### ISSUE TITLE
Launch a program

### ISSUE THREAD

**Issue by hagenbauer** [jpmens/mqttwarn#116]
I am searching for an example how to create a service which is just launching a program.

Any help is appreciated

Hagen

**Comment by jpmens** [comment]
Take the `file' service as a starter. The question is what you mean my "launching a program". Launch as in start and let it run, pipe into a program, etc. You'd have to be very careful to not open yourself up to a DoS; what I'd probably do is to have a semaphore of some sort to ensure that only N programs could be launched at once.

**Comment by hagenbauer** [comment]
Launch as in "start and let it run". The servers is behind a firewall so DoS is not an issue

**Comment by jpmens** [comment]
I think you'll find some inspiration by looking at [mqtt-spawn](https://github.com/PowerDNS/mqtt-spawn).

**Comment by hagenbauer** [comment]
I have a a "solution" that will work for me with the logfile plugin. Then I will launch my program that needs the last message as input 

watch 'tail logfile | tail -n1 | xargs dcled -s 200 -m '
