### ISSUE TITLE
running mqttwarn with relative paths?

### ISSUE THREAD

**Issue by dvand** [jpmens/mqttwarn#118]
In order to get the script to work I had to add the line following. Otherwise it couldn't find the config file. I am running the script from a process supervisor (daemontools).

os.chdir(os.path.dirname(sys.argv[0]))

**Comment by dvand** [comment]
My bad did't realize there was a variable!

As a suggestion maybe it would be good to reference that in the installation section of the configuration guide.

**Comment by jpmens** [comment]
It is documented.
