### ISSUE TITLE
Mention use of JSON for xively recipe

### ISSUE THREAD

**Issue by rabarberski** [jpmens/mqttwarn#119]
I struggled a bit getting the xively service working. I took me some time to figure out that I actually needed to have JSON in my MQTT messages, after which things worked properly. Perhaps the xively explanation in the `REAME.md` can be updated slightly to reflect this? For example by updating it along the following lines:

--------

The `xively` service can send a subset of your data to Xively per defined feedid.

    [config:xively]
    apikey = '1234567890abcdefghiklmnopqrstuvwxyz'
    targets = {
            # feedid        : [ 'datastream1', 'datastream2']
            '1234567' : [ 'temperature', 'waterlevel' ],
            '7654321' : [ 'dataItemA' ]
      } 

Publishing the following message will add a datapoint to the `temperature` and `waterlevel` channel of your xively feed 1234567 (`humidity` will be ignored, as it's not defined in the xively configuration above):

    $ mosquitto_pub -t "osx/json" -m '{"temperature":15,"waterlevel":100,"humidity":35}'

--------

**Comment by rabarberski** [comment]
Thanks, however, don't forget to change the relevant target line in the config snippet to include `temperature`and `waterlevel`, instead of the current `dataItem1`and `dataItem2`. Currently the code doesn't make much sense. And if you're at it, perhaps also change the first line to include the word "JSON" so it becomes:
"Publishing the following *JSON* message will add a datapoint ..."

**Comment by jpmens** [comment]
Thank *you* for being so attentive! :-)

**Comment by jpmens** [comment]
If there's anything else you find in the docs (and you will) or code, I'll be happy to accept pull requests.
