### ISSUE TITLE
How to pass received mqtt payload to plugin (instapush)

### ISSUE THREAD

**Issue by pfichtner** [jpmens/mqttwarn#121]
How can i pass the payload received to the instapush plugin. 

```
[foo/bar]
targets = instapush:webcamalert

[config:instapush]
appid = 'secret'
appsecret = 'secretToo'
targets = {
  'webcamalert' : [ 'webcam', {"device":"hardCodedDevice", "type":"hardcodedType"}]
  }
```

When publishing a message via ```mosquitto_pub -h mqtt -t foo/bar -m '{"device":"webcam 4", "type": "motion"}'```

I'd like to send the payload received by mqtt (```{"device":"Webcam #4", "type": "motion"}```) 
and not the static content ```{"device":"hardCodedDevice", "type":"hardcodedType"}```

I played around with format but couldn't get it to work

Thank you!

**Comment by jpmens** [comment]
What should work is using the _format_ specifier as follows:

```ini
format = {payload}
```

**Comment by pfichtner** [comment]
and how would  ```targets = {
  'webcamalert' : [ 'webcam', {"?????"}]
  }``` of ```[config:instapush]``` look like?

**Comment by jpmens** [comment]
That _looks_ right to me, but I have no experience with instapush.
@dgomes Can you give us a hand here?

**Comment by pfichtner** [comment]
Just for clarification: I do know how to format the payload via ```format``` but I don't know what to write inside the plugin's configuration to access the formatted string (see the question marks in my last post)

**Comment by pfichtner** [comment]
Any news here? Is this a general issue or a plugin related issue? How can a plugin access the string formatted by ```format```? Does each plugin have to implement this by it's own?

**Comment by jpmens** [comment]
I'm losing track a bit ... Plugins get the text formatted by `format` automatically.

However: glancing at the source of the `instapush` plugin, I see it isn't being used at all; instead the author (@dgomes) is using the parameters in the target configuration, which is a bit "unusual" maybe. ;-)

If you need this quickly, you're going to have to copy `instapush.py` and call it something else (and modify it accordingly). It's not hard: the `file.py` module shows you how to get at the _text_.

**Comment by pfichtner** [comment]
Oh! Alright! No need to skelter! Sufficient to know it wasn't my fault and couldn't be fixed by me on configuration level! 
Will wait for @dgomes to fix it! 
Thank you!

**Comment by jpmens** [comment]
I could certainly "fix" it, but I don't understand the reasoning so I don't want to make break it by changing the way the payload is handled. The plugin currently hands off `event` and `trackers` from the targets configuration:

```python
data["event"] = item.addrs[0]
data["trackers"]  = item.addrs[1]
```

Time is at a premium at the moment, and I don't want to study the API; if you find an *additional* JSON value we can pass to the Instapush API, I'll gladly put that in for you quickly.

**Comment by dgomes** [comment]
Hi!

Shame on me for not supporting instapush "trackers" from the payload. But due to bias of my own setup, the device that publishes to my mqtt broker is not a json string (but a code). So I really needed to hardcode the payload in mqttwarn.ini

I just issued a pull request that solved this issue :)

BTW: how should I use "format =" to create a JSON string ?

**Comment by pfichtner** [comment]
Thanks for helping to solve that issue, guys!

**Comment by jpmens** [comment]
Thank you @dgomes. 
@pfichtner I have merged this *blindly* (something I seldom do, but ENOTIME!) without testing it. Please test, and I'd appreciate if you could report back with your success. ;-)

**Comment by pfichtner** [comment]
Works now as described. Thanks for your support!

**Comment by jpmens** [comment]
I'm glad you got it going, and apologies for it taking so long because of my confusion ;-)

**Comment by dgomes** [comment]
glad to help too! :)

And sorry for taking so long to answer/fix
