### ISSUE TITLE
.py files in .gitignore

### ISSUE THREAD

**Issue by robertvanbregt** [jpmens/mqttwarn#130]
The file ``.gitignore`` in the repo contains references to

    prowlpy.py
    pushbullet.py
    pynsca.py 
    pastebin.py

but they are required in services

Why are they in the ignore file?

**Comment by jpmens** [comment]
Some of the pip requirements don't actually have to be installed via `pip install`; it suffices to grab just the single Python file, which I do for testing / writing services. I know others do this also, ocasionally.

To ensure these aren't checked-in by mistake, I added them to `.gitignore`, which shouldn't hurt much. :)
