### ISSUE TITLE
carbon service with JSON extracts ?

### ISSUE THREAD

**Issue by chaeplin** [jpmens/mqttwarn#131]
I have found your mqtt2graphite https://github.com/jpmens/mqtt2graphite.

Could mqttwarn have another graphite/carbon service for JSON extracts ?

Thank you.

**Comment by jpmens** [comment]
I don't understand what you want. Can you please clarify, with an example?

**Comment by chaeplin** [comment]
My sensor send JSON payload like {"Temperature": 25, "Humidity": 40}.
I want send Temperature and Humidity to carbon(influxdb).

services/carbon.py takes only one metric/value/timestamp.
So I am using mqttpub to split payload with topic change then format.

I can run mqtt2graphite for specific topic but...



ex) 
[config:mqttpub]
targets = {
                # topic            qos     retain
    'temperature'   : [ 'temperature',         0,     False ],
    'humidity'      : [ 'humidity',  0,     False ],
  }

[esp8266/arduino/s02]
targets = mqttpub:temperature, mqttpub:humidity

[temperature]
targets = carbon:nemo
format = Temperature {Temperature}

[humidity]
targets = carbon:nemo
format = Humidity {Humidity}
