### ISSUE TITLE
 No targets for service `http' issue

### ISSUE THREAD

**Issue by itailewin** [jpmens/mqttwarn#137]
Hi,
I really like this project, cause it allow me to bridge the MQTT world to the HTTP one, without start coding in C.

But I have some issues with the HTTP plugin.
I am testing on local windows 7 machine
I have a running a MQTT device sending  a message every 10 sec to a test server (broker.mqttdashboard.com)
I try to forward the messages to a PHP page which simply save it to a file (for testing).

But I keep get: No targets for service `HTTP' in the log.
```
 2015-06-05 15:03:59,224 DEBUG [mqttwarn] New `http:get1' job: totolegrand
 2015-06-05 15:03:59,224 DEBUG [mqttwarn] Processor is handling: `http' for get1
 2015-06-05 15:03:59,226 ERROR [mqttwarn] No targets for service `http'
```
even with this simple settings:
```
[defaults]
hostname  = 'broker.mqttdashboard.com'
port      = 1883

; name the service providers you will be using.
launch	 = log, http ,file

[config:file]
append_newline = True
targets = {
    'log-me' : ['log.html']
   }
   
[config:log]
targets = {
    'info'   : [ 'info' ]
  }
[config:http]
timeout = 60

targets = {
                #method     #URL                 # query params or None          # list auth
  'get1'  : [ "get", "http://swat-cntrl.com/mqtt.php?", { 'xx': 'yy' }]
  }
  

[totolegrand]
targets = http:get1, log:info, file:log-me

```
log and file are ok,

my mqtt message is formated like this:
```
     {'q' :'401','heap':'10560'}
```
so I tried the follow:
```
     'get1'  : [ "get", "http://swat-cntrl.com/mqtt.php", {'q' : '{q}' , 'heap' : '{heap}' , None ]
```
 as test, I run this script:
```
import urllib2

timeout = 60
params = 'http://swat-cntrl.com/mqtt.php?q=tes123t&heap=12345678'
	
try:
		request = urllib2.Request(params)
		request.add_header('User-agent', 'my-scriptName')
		resp = urllib2.urlopen(request, timeout=timeout)
		data = resp.read()	
		print data
		
except Exception, e:
	print "Cannot GET %s: %s" % (params, str(e))
```
against this :
```
<?php
	$value = print_r($_GET,1);
	file_put_contents("mqtt.html", "<pre>".$value."\n");
	echo "Done";
?>
```
and it returns 'done'
 I might miss some basic stuff, but that where I am now.
 Itai Lewin

**Comment by jpmens** [comment]
Would you please add a blank line before your [config:http] line? I'm not sure, but it could well be the ini parser which is considering that as part of the previous config:log. Otherwise your configuration looks ok to me.

**Comment by itailewin** [comment]
Apparently, it was wrong JSON formatting that cause the problem.

must use:

 {"q":"35","heap":"10496"}

 instead of:

 {'q':'35','heap':'10496'}

the blank line doesn't affects it

Thanks

**Comment by jpmens** [comment]
I didn't see that, sorry. JSON requires double quotes.
