### ISSUE TITLE
in mqttsub, if the message doesn't meets the format requirement, it send the original

### ISSUE THREAD

**Issue by itailewin** [jpmens/mqttwarn#138]
let say I have the following:

```
[config:mqttpub]
targets = {
                # topic            qos     retain
    'main'   : [ 'totolegrandmain',         0,     False ]
    
  }
  
[totolegrand/+]
targets = mqttpub:main
format = "{id} runs {q} cycles at heap {heap}"
``` 
 if my message is missing one of the parameters, (2 instead of 3) it sends the original (raw) message.
I think it should send the formatted text with empty space holder where the variables are missing.

**Comment by jpmens** [comment]
I don't think this is a good idea. You can basically already do this yourself by using Jinja2 templates or the alldata= function in which you could add missing values before they hit format=.
