### ISSUE TITLE
Multiple MQTT topics sending based on MQTT message

### ISSUE THREAD

**Issue by davidhrbaty** [jpmens/mqttwarn#139]
Hello,
I need to use mqttwarn to parse incoming MQTT mesage. Based on incoming message I need to send different topics with different messages. Is it possible? Because  I spend some days without result.

Incoming topic is: **OSPI/zc** and incoming messages are different based on settings in my opensprinkler. For exampe: **[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]**  or  **[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]** etc ..

I need to send different topics with different messages based on imcoming **OSPI/zc** message.
For example, when I receive topic **OSPI/zc** with message **[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]**  I need to send topic **home/rfm_gw/sb/node02/dev17** with message **ON** . 

When I receive topic **OSPI/zc** with message **[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]**  I need to send different topic **home/rfm_gw/sb/node02/dev16** with message **OFF**  etc for several scenarios. Is this possible there? Thank you for your time and help.

**Comment by jpmens** [comment]
This is not possible.
