### ISSUE TITLE
varying host name and service description in [config:nsca] based on MQTT topic

### ISSUE THREAD

**Issue by cuonglv1994** [jpmens/mqttwarn#140]
Hello,
Please take a look at this: http://pastebin.com/C914JFLj
I need to monitor a lot of host and each host has a same set of service. Is there any way to parse the topic to the [config:nsca] section?
for example: the topic in config file is [monitor/+/temp]
mqttwarn received a message in topic "monitor/ubuntu/temp" , it will parse the topic so that the content of the [config:nsca] section would be read as temp: ['ubuntu',   'temp'] ; and so on with topic "monitor/centos/temp", the result is temp: ['centos',   'temp'] . Is this possible without modifying the software?
Thank you for your time and help.

**Comment by jpmens** [comment]
This should be possible by using an `alldata=` function (check the README, please). Therein, you have access to the topic and can return a `dict` of data which is later used.

**Comment by cuonglv1994** [comment]
Oh, thank you,
At the time time I open this issue and later, when I request a pull, I just couldn't understand that clear. Now all is clear to me. I will close this issue and my pull request immediately.
