### ISSUE TITLE
gss 2015-08-12 19:32:44,678 WARNING [gss] Error adding row to spreadsheet xxx-aPdC-MX8 [o4nbzcf]: no element found: line 1, column 0

### ISSUE THREAD

**Issue by kiralikbeyin** [jpmens/mqttwarn#143]
I got error gss 2015-08-12 19:32:44,678 WARNING [gss] Error adding row to spreadsheet xxx-aPdC-MX8 [o4nbzcf]: no element found: line 1, column 0

already tried od6 default sheet1, changed column names etc..

I think this service is not working?

**Comment by jpmens** [comment]
What are you talking about?

**Comment by kiralikbeyin** [comment]
https://github.com/jpmens/mqttwarn#gss

I followed in this link and spreadsheet didnt get it.

mosquitto_pub -t test/gss -m '{"a":"1", "b":"2"}'

There are only 2 columns named a and b so 2. row should be 1 and 2 but log file is : 
2015-08-12 19:32:44,678 WARNING [gss] Error adding row to spreadsheet xxx-aPdC-MX8 [o4nbzcf]: no element found: line 1, column 0

There is nothing about this log:
"gdata.service.RequestError: {'status': 400, 'body': 'We&#39;re sorry, a server error occurred. Please wait a bit and try reloading your spreadsheet.', 'reason': 'Bad Request'}"

Please can you try and confirm that is working?
