### ISSUE TITLE
Broker connection lost

### ISSUE THREAD

**Issue by systray** [jpmens/mqttwarn#145]
Hello,

i'm testing mqqtwarn <-> mosquito stack on Amazon ec2 server and there is an issue with mqqtwarn connection that i can't figure out. 
I've performed several tests and most simple one is when mqqtwarn writes data into the file.  Here is a config https://gist.github.com/systray/e344d1b0d9c118381b1a
I've subscribed to one channel from mqqt client and write a messages into it. Something like 1 message per second. mqqtwarn was able to process near 50% of messages only. For other 50% i've got next messages in the log: https://gist.github.com/systray/5c2320bd3d066bcea82c . This log output appears for each message that i've sent (right after sending it) that wasn't written to the file (failed).

I can't reproduce same bug on my local machine. Also important notice that all other clients subscribed to the same topic on ec2 mosquitto instance receives their messages without any problems. So it is only mqqtwarn who gets that many disconnects and misses messages.

Any clue how to resolve this? 

Thanks in advance.

**Comment by jpmens** [comment]
It's good you cannot reproduce on your local machine. :) 
Either the version of Mosquitto on EC2 is flakey (which version is that?) or it looks a bit as though you have multiple MQTT clients (maybe more than one mqttwarn) connected to it with the same clientID (clientIDs must be unique on connecting to MQTT brokers).

**Comment by systray** [comment]
I've checked mqtt clients loaded. Everything is ok with that. So probably you are right about mosquitto version.
EC2 mosquitto was installed through apt-get and here is it's info: https://gist.github.com/systray/a1d0452b3981cbfdb75b
Locally i'm using mac and installed mosquitto through brew. Here is the info about it: https://gist.github.com/systray/764b5246fbf7ca760823

I do believe that locally i have 1.4.2 version. EC2 version is not clear for me.

**Comment by systray** [comment]
I've updated EC2 version of mosquitto using instructions for Ubuntu from http://mosquitto.org/download/ . Now EC2 shows: https://gist.github.com/systray/8c90f5cb6eebb83049cd
Local: https://gist.github.com/systray/4833ac539a1748a6a367

Versions are the same for the moment, but problem still exists.

**Comment by systray** [comment]
Oh god, another mqttwarn client was running on my home machine for the last few days. I've stopped it and the problem is gone.

Thanks for your help!
