### ISSUE TITLE
Unwanted 'u' character appearing in JSON name and value fields processed by 'format'

### ISSUE THREAD

**Issue by rapport** [jpmens/mqttwarn#146]
When I publish humidity data to my MQTT broker...

``` python
mosquitto_pub -h 192.168.178.20 -t test/input -m '{"d":{"humidity":"62.18"}}'
```

And, then try to process with the mqttwarn mqtt service I appear to get unwanted 'u' characters in front of all the name and values which are nested inside the JSON that are processing with the default format processing  (as seen test/output below). e.g I get 'u' appearing like this

``` python
test/output "{u'humidity': u'62.18'}"
```

My mqttwarn.ini config contains the following settings:

``` python
[config:mqtt]
  hostname =  'localhost'
  port =  1883
  qos =  0
  retain =  False
  username =  None
  password =  None
  targets = {
    'o1'    : [ 'test/output' ],
  }
[test/input]
  targets = mqtt:o1
  format = "{d}"
```

I assume it is a bug that the 'u' appears in this context! It looks like it is being inserted by some processing of quotations as when publish without a quotation first instance on the 62.18 data field e.g.

``` python
mosquitto_pub -h 192.168.178.20 -t test/input -m '{"d":{"humidity":62.18}}'
```

I get no chartacter appearing in front of the 62.18 value e.g.

``` python
test/output "{u'humidity': 62.18}"
```

I am able to work around the problem by calling a custom function from format.  i.e.

``` python
   format = CustomTextTransform()
```

functions.py

``` python
def CustomTextTransform(message):
    data = json.dumps(message['d'])
    return str(data)
```

**Comment by rapport** [comment]
I just noticed when publishing value without quotations there is no extra character appearing

mosquitto_pub -h 192.168.178.20 -t test/input -m '{"d":{"humidity":62.18}}'

test/output "{u'humidity': 62.18}"

**Comment by rapport** [comment]
Seems to be a bit similar to this problem
http://stackoverflow.com/questions/12966308/decoding-json-with-python-and-storing-nested-object

**Comment by jpmens** [comment]
Please provide a reproducible example with your configuration and the published payload. (Kindly use Github's markup for formatting code & examples :-)

**Comment by rapport** [comment]
I have reformatted previous comment and hopefully the example is clearer now!

**Comment by jpmens** [comment]
Thank you for your concise report. It looks strange and honestly I don't know at this moment what to do about it ... I think your use of a custom function is currently the only solution. I will look into this a bit closer when I get an opportunity to.

**Comment by jpmens** [comment]
... unless of course, you're willing to submit a nice pull-request which fixes the issue. :-)

**Comment by jpmens** [comment]
Fixed in https://github.com/jpmens/mqttwarn/pull/282
