### ISSUE TITLE
Support for AWS IOT

### ISSUE THREAD

**Issue by vielmetti** [jpmens/mqttwarn#148]
Amazon has announced an AWS IOT system which is based on MQTT, albeit with its own flavor of certificate-based authentication. It looks like a perfectly reasonable system to integrate into mqttwarn.

From reading mqttwarn/services/mqtt.py it looks like mqttwarn uses Paho, so the necessary code changes might actually be upstream. I'd like to open up this issue to track whatever work might be necessary to make this connection work.

**Comment by jpmens** [comment]
That file actually is a publisher, but you are correct: mqttwarn uses Python Paho in its main loop as well.

**Comment by jpmens** [comment]
I am not interested in doing anything to support these non-standard things. We'd probably take a patch to do so though. Closing now.
