### ISSUE TITLE
Small typo in doku

### ISSUE THREAD

**Issue by przemas75** [jpmens/mqttwarn#152]
On the main page https://github.com/jpmens/mqttwarn#xbmc in xmbc section, there is unnecessary  '}' char in the bedroom line.

One may not notice this simply copying this like me :)

**Comment by jpmens** [comment]
Thanks

**Comment by przemas75** [comment]
BTW, same story for mythtv.

**Comment by jpmens** [comment]
Thanks; I think we have them all now. :-)
