### ISSUE TITLE
HTTP enhancement to allow json POST

### ISSUE THREAD

**Issue by seblucas** [jpmens/mqttwarn#157]
Hi,

First huge thanks for this project, it's really huge !!

Now the "issue" part, I just spent some time on using the http service to post data to firebase. Firebase need json in its POST payload and it's kind of hard to do with mqttwarn. The only reference I found is #71 and it seems too complicated for me. 

Would you accept a PR adding another parameter to specify if the query params should simply be jsonified (json.dumps) instead of only being urlencoded ?

Thanks in advance.

**Comment by jpmens** [comment]
I would accept that gladly.

**Comment by seblucas** [comment]
Closed, PR #158 was merged
