### ISSUE TITLE
File - Write only last value to file and not update the file on each new value

### ISSUE THREAD

**Issue by raymonvdm** [jpmens/mqttwarn#159]
I would like to have the possibility to only have the last MQTT value in a file. As i`m using this file as an input for my cacti graphs (read out by SNMP)

[config:file]
append_newline = True
targets = {
    'f01'       : ['/tmp/f.01'],
    'douchet'    : ['/etc/snmp/douchet.txt'],
    'douchev'    : ['/etc/snmp/douchev.txt'],
   }

[/homeseer/398/value]
topic = /homeseer/398/value
targets = file:douchet

The config lines in my SNMPd.conf

extend douchet /bin/cat /etc/snmp/douchet.txt
extend douchev /bin/cat /etc/snmp/douchev.txt

Cacti is polling the snmp string douchet to get the value of douchet

Note: In the past if have used MySQL for this but my source has a plugin for spreading MQTT messages but not for filling up a MySQL database.

**Comment by jpmens** [comment]
I have implemented code for this with the `overwrite` parameter:

```
[config:file]
append_newline = True
overwrite = True
targets = {
   'mylog'     : ['/tmp/mqtt.log'],
  }
```
