### ISSUE TITLE
MQTT to Carbon 

### ISSUE THREAD

**Issue by raymonvdm** [jpmens/mqttwarn#161]
The MQTTwarn is running fine and working as expected for some MQTT messages i`m forwarding to Carbon. 

This one is working fine

2015-12-09 23:04:50,330 DEBUG [mqttwarn] Message received on /homeseer/400/value: 58
2015-12-09 23:04:50,331 DEBUG [mqttwarn] Section [/homeseer/400/value] matches message on /homeseer/400/value. Processing...
2015-12-09 23:04:50,331 DEBUG [mqttwarn] Message on /homeseer/400/value going to file:douchev

This one seems to be to long and i don`t know how to change is since it is created by a piece of software which is out of my control

2015-12-09 23:04:40,336 DEBUG [mqttwarn] Message received on events/central_heating/otmonitor/boilerwatertemperature: 36.00
2015-12-09 23:04:44,391 DEBUG [mqttwarn] Message received on events/central_heating/otmonitor/boilerwatertemperature: 40.00

These are my config lines for both MQTT subscriptions

[/homeseer/#]
topic = /homeseer/#
targets = carbon:c1

[/events/central_heating/otmonitor/#]
topic = /events/central_heating/otmonitor/#
targets = carbon:c1

**Comment by jpmens** [comment]
What do you mean by _too long_? I'm not aware of any limitations in the code, although it may be a carbon-specific thing. The topic name is translated to a Carbon metric name (not truncated there), so this may be a Carbon issue. You'll have to do more testing, with ever-increasing topic name lengths.

**Comment by raymonvdm** [comment]
I have made some progress on this issue after some time. It looks like the topic is translated fine but the issue is with the first /

[/homeseer/#]
topic = /homeseer/#
targets = carbon:c1

[events/central_heating/otmonitor/#]
topic = events/central_heating/otmonitor/#
targets = carbon:c1

/homeseer/# is translated to .homeseer.405.value 16,5 1519663328 (which does not end up in graphite)

events/central_heating/otmonitor/# is translated to events.central_heating.otmonitor.roomtemperature 19.05 1519663353

So i need a way to remote the first / from /homeseer (since i cannot change it at the sending program)

**Comment by jpmens** [comment]
Why are your topics prefixed with a slash? That's a null, in MQTT terms, and there's no need for topics to start with a slash.

**Comment by raymonvdm** [comment]
I guess the developer decided it was a good idea or does not know that the first slash isn`t needed. But i cannot change this so i need to work around it in some sort of way

**Comment by sumnerboy12** [comment]
Regardless, it is allowed and thus should be supported :)

**Comment by jpmens** [comment]
Please test.

**Comment by raymonvdm** [comment]
I`m afraid it is not working for me. 

2018-02-26 23:46:35,030 DEBUG [carbon] Sending to carbon: events.central_heating.otmonitor.centralheating 1 1519685195
2018-02-26 23:46:59,933 DEBUG [carbon] Sending to carbon: .homeseer.1466.value 100 1519685219

**Comment by jpmens** [comment]
Did you git pull and restart mqttwarn before the test?

**Comment by raymonvdm** [comment]
I remove the folder because installed it in the past using the zip download. Now i installed it using git and therefore it is working (with the old config of course)
