### ISSUE TITLE
Using JSON Payload Variables as Service Targets

### ISSUE THREAD

**Issue by egadgetjnr** [jpmens/mqttwarn#162]
Hey There,
I just had an idea, and I was wondering if you might be able to advise if it's possible and maybe offer a possible feature in a future release.

I'm currently experimenting with the Prowl service, and I have an idea around pointing to dynamic targets.

The payload is JSON in the following format:
{ "SystemID" : "V1_001", "AlarmType" : "TempHigh", "AlarmDetails" : "Temp is 102" }

My Prowl Config is:

[config:prowl]
targets = {
        'V1_001' : ['xxx', 'Alarm'],
        'V1_002' : ['xx2', 'Alarm'] 
}

What I'm wanting to do, is have the topic section similar to the following where it allows the SystemID Variable to be used for the target instead of having to create separate topic sections just to change the target

[ProwlAlarm]
topic = 1/+/Alarm
targets = prowl:{SystemID}
title = {AlarmType}
priority = 2
format = {AlarmDetails}

Is there maybe another way I can approach this, or are you able to possibly assist?

Thanks heaps

**Comment by jpmens** [comment]
That is currently not possible: it would mean having to get the JSON payload and react on that. I have thought about that previously, but it's not implemented.

What you might try is to model after the _targets dictionary_. Please look at the README, starting at where it says `Targets can be also defined as a dictionary`

**Comment by amotl** [comment]
Hi. Apologies for the very late reply. I think this feature has now been implemented on behalf of [Templated targets].

- https://github.com/mqtt-tools/mqttwarn/pull/169

[Templated targets]: https://mqttwarn.readthedocs.io/en/latest/configure/topic.html#templated-targets
