### ISSUE TITLE
 [pushbullet] pushbullet is not installed?

### ISSUE THREAD

**Issue by martinjo** [jpmens/mqttwarn#165]
Hi,

I'm really a python newbie, so forgive me for this probably very basic question.

But, I'm trying to run mqttwarn on my rapsberry pi. I tested the file log module which output as expected to the /tmp directory.

Now when I try to enable the pushbullet module I cannot get it to work.
From what I understand I should download the pushbullet.py file from pyPushbullet and put it in the mqttwarn directory. But nevertheless I get the following log messages when publishing to my pushbullet topic

2016-01-11 21:14:51,612 WARNING [pushbullet] pushbullet is not installed
2016-01-11 21:14:51,613 WARNING [mqttwarn] Notification of pushbullet for `openhab/info' FAILED or TIMED OUT

I also installed the pyPushbullet package, but it still seems I'm missing something essential.

Any help is appreciated! :)

**Comment by jpmens** [comment]
If you copy pushbullet.py into the directory which contains mqttwarn.py this ought to work, assuming that you are launching mqttwarn.py from whithin that same directory.

On the other hand, you say you've installed the pyPushbullet package which overrides my previous sentence actually. I can't think of what's missing... Would you show us your (password-less) configuration please?

**Comment by MansM** [comment]
When I still used pushbullet with openhab ( I stopped, because I couldnt get the message in the lockscreen, only pushbullet/mqttwarn) I installed it with puppet:

python::pip { 'pyPushBullet' :
  pkgname  => 'pyPushBullet',
  ensure      => 'present',
  url             => 'https://github.com/Azelphur/pyPushBullet/archive/master.zip',
 }

Hope you can use it on way or another

With kind regards,

Mans

**Comment by martinjo** [comment]
@jpmens @MansM : Thanks for you answers! I'll show my config here as soon as I get home and can reach my raspberry again.

@MansM Could you give me a hint of how to use Puppet to install pushbullet?
When I tested Pushbullet with Domoticz I could get the notifications to my lockscreen (on iPhone). I don't remember any specific setting for this more than to allow notifications...

**Comment by MansM** [comment]
how did you install pyPushbullet? I would recommend trying to do pip install https://github.com/Azelphur/pyPushBullet/archive/master.zip <https://github.com/Azelphur/pyPushBullet/archive/master.zip'>

Puppet will be overkill if you only want to use it to install pypushbullet once.

With kind regards,

Mans

**Comment by martinjo** [comment]
@MansM That's exactly what I tried first. But for some reason I still get the "[pushbullet] pushbullet is not installed" warning when sending messages to my pushbullet target. 

I've no idea how to check if pyPushbullet actually got installed (it said it was successfully installed when running pip install git+https://github.com/Azelphur/pyPushBullet.git command). :/

**Comment by martinjo** [comment]
Ok, I figured out what was wrong now. 

I changed the import statement in /services/pushbullet.py
from "from pushbullet.pushbullet import PushBullet"
to "from pushbullet import PushBullet"

and now it's working as expected.

Thanks for your suggestions!

**Comment by jpmens** [comment]
Thanks for finding that; I've added an addition `try` to import as you say.
