### ISSUE TITLE
deal with out of control publishing

### ISSUE THREAD

**Issue by matbor** [jpmens/mqttwarn#17]
Maybe add a feature that if _x_ amount of the same messages is published within _y_ amount of time, then just send one message saying that.  Instead of publishing all the messages, then goto sleep on that message for _z_ time.  

As you could easily blow api limits on some services, or it just becomes annoying on your mobile device!

**Comment by appsxt** [comment]
Hi,

Thanks for sharing such an excellent project.

I too was wondering if there is an easy way to limit the number of repeat warnings. Consider a sensor publishing temperature readings once a minute and we're interested in receiving high temperature alarms above 50 degrees Celsius. The high temperature condition may not be resolved instantly and we don't need 60 notifications per hour.

I was able to limit publication with `datetime` in a custom filter, to in this instance only publish every 5 minutes.

```python
import datetime
def highTemperatureAlarm(topic,message):
        try:
                float(message)
                if datetime.datetime.now().minute % 5 == 0:
                        return float(message) < 50.0
                else:
                        return True
        except:
                return True
```

This however may miss some alarms altogether. Is it possible to code something like the typical Arduino `millis()` check?

```c
#define alarmDelay 300
...
int lastAlarm = 0;
...
if(millis() - lastAlarm > alarmDelay) {
	lastAlarm = millis();
	// Publish alarm
} else {
	// Don't publish alarm
}
```

I guess that would require some kind of global variable declaration. I haven't tried this yet in Python (I'm actually quite new to Python) or mqttwarn.

Cheers,

Mick

**Comment by dgomes** [comment]
Hi,

I implemented a filter like soo:


def static_var(varname, value):
	def decorate(func):
		setattr(func, varname, value)
		return func
	return decorate

@static_var("h_db", dict())
def hysteresis(topic, message):
	import time
	ts = time.time()
	if message in hysteresis.h_db:
		if ts - hysteresis.h_db[message] < 10:	#ignore for 10 secs
			return True
	hysteresis.h_db[message] = ts
	return False 


So I can use it to limit the rate of a door sensor that broadcast repeatedly the same message for a brief period of time

def doorOpen(topic, message):
        if message == "0x7F7B04": # packet = door sensor
                return hysteresis(topic, message)
        return True

**Comment by appsxt** [comment]
Thanks @dgomes. I will try your filter.
