### ISSUE TITLE
[cron] only works Once

### ISSUE THREAD

**Issue by edrizo** [jpmens/mqttwarn#173]
Hey!

I'm trying [cron] and it works only 1 time.

INI is like this

[cron]
pinger = 60.5

pinger() is a function that works fine. The thing is that after running the funcion (respecting well the sheduled time, and working properly) he app falls on the "mqttc.loop_forever()" and doesn't run the scheduled task anymore. It runs only the first time.

Using debian 7.

**Comment by edrizo** [comment]
By the way, the same code running on Windows is working perfectly.

**Comment by amotl** [comment]
We can confirm the periodic task feature works as expected with Python 2.7 on Debian 7 and Debian 8 using the example provided in #178.

Maybe you can provide some more details in this issue about the complete mqttwarn configuration used as well as the defined helper functions. This might help investigating potential side effects why your instance of mqttwarn fails on ``mqttc.loop_forever()``.

**Comment by jpmens** [comment]
@edrizo are you going to provide the requested information?
