### ISSUE TITLE
Pushover basic configuration

### ISSUE THREAD

**Issue by RitchieMatt** [jpmens/mqttwarn#175]
Excuse my ignorance with these basic configurations.

I have had no problems running MQTTWarn with Thingspeak, works a charm.  I cannot seem to get the configuration for Pushover to work at all.  I have checked pushover.py for hints on the proper configuration.

I have tried;

[config:pushover]
message = "Warning from MQTTWarn"
callback = None
targets = {
    'temp_emergency'   : ['userkey1', 'appkey2', 'sound3'],
    'temp_warning' : ['uekR......................CFfQtM7J3r', 'arXqKoErk....................ksQ5kFd']
    }

[/PDDS/FL_001/DISPENSARY/VAX/TT001/Temp_Warn]
targets = log:debug, pushover:temp_warning, thingspeak:field2, file:mqttlog

I have also tried using;
[/PDDS/FL_001/DISPENSARY/VAX/TT001/Temp_Warn]
targets = log:debug, pushover:temp_warning, thingspeak:field2, file:mqttlog
message = "Warning from MQTTWarn"

As pushover.py asserts the 'message' argument.  I have also tried without.
The logs are not showing anything appropriate.
I have loglevel debug.
I have tried running script as supervisor.

Sure this is a rookie mistake.  Can you help?

**Comment by sumnerboy12** [comment]
The `message` is the formatted payload which `mqttwarn` builds for you - you do not define that yourself. Have you added `pushover` to your `launch` list?

For comparison, my Pushover config is simply;

```
[config:pushover]
targets  = {
    'ben_phone'     : [ 'xxx', 'yyy' ],
    }

[/openhab/notification/ben]
targets  = pushover:ben_phone
title    = openHAB
priority = 0
```

Any payload published to `/openhab/notification/ben` is sent directly to my phone via Pushover.

**Comment by RitchieMatt** [comment]
Thanks Mate.

Can't believe I overlooked that.  It was 'launch'

BTW.  Love your work.  Seen you popping up more often.

**Comment by sumnerboy12** [comment]
Cheers ;).
