### ISSUE TITLE
Publish result of HTTP GET

### ISSUE THREAD

**Issue by thucke** [jpmens/mqttwarn#177]
Hi,
I like to publish the result of an HTTP-GET command to the MQTT queue.
Example:
Having the configuration
    
    [config:http]
    timeout = 60
    targets = {
        #method     #URL               # query params or None          # list auth
        'dev16get'    : [ "get", "http://localhost:8083/ZWaveAPI/Run/devices[16].instances[0].Basic.data.level", None, (<username>, <password>) ],
    }
    
    [/home/zwave/Device16/switch/get]
    targets = http:dev16get

The command 

    mosquitto_pub -t /home/zwave/Device16/switch/get -n

should result in the following post to MQTT

    {"invalidateTime":1460221477,"updateTime":1460221478,"type":"int","value":0}

This would the the respone of the webserver if doing the same request in a web browser.
Is that possible?????

**Comment by jpmens** [comment]
If I'm understanding you correctly it isn't possible. MQTTWARN listens to MQTT messages as a subscriber. Using the http service you can then issue a HTTP GET or POST request to an HTTP endpoint, which is the opposite of what you're asking.

**Comment by thucke** [comment]
Thanks for this quick response.

I see this point.
On the other hand I wonder why MQTTWARN should support GET requests without being able featuring the response to modify the MQTT message.
Anyway, I find this would be a great feature of MQTTWARN.

BTW: MQTTWARN as it is this time is just a great enhancement - thank you so far!

**Comment by jpmens** [comment]
What I think you are looking for is

```
HTTP -> MQTT
```

whereas _mqttwarn_ is the other way around. The reason we have a HTTP service which supports `GET` is in order to access HTTP endpoints which don't support `POST`.

What would definitely be possible is to have this:

```
MQTT -> MQTTWARN -> HTTP-GET -> MQTT publish
```

but, as it stands, this is not implemented (though relatively easy to implement I think). Although I also think for most this is overkill.

What you can attempt is to use a user-configurable function which is invoked on MQTT payloads, does the HTTP GET internally and modifies mqttwarn's notion of the payload before continuing. There are a couple of examples in the README

**Comment by thucke** [comment]
Yeah - that's what I was thinking about if that feature would not be possible "out-of-the-box".
Creating a user-configurabe function requires to implement the HTTP GET mechanism on my own.
Hence I'd be glad using the "ready-for-use" HTTP GET mechanisms of MQTTWARN ;-)

Perhaps you may again think about the implementation. In general I would see some benefit having "chainable" services if a service provides some output. For instance it would also be possible to chain multiple MQTT brokers whith the enhancement to modify MQTT messages of other brokers before the get published to own clients.

I would appreciate your thougts on that scenario.
You may close this issue then.
Thanks a lot!

**Comment by amotl** [comment]
Dear Thomas,

we added an example using the [periodic tasks] feature to #178, using a custom Python function which acquires remote data using a HTTP GET call and then decodes and publishes the response to the MQTT bus.

While this is not the ultimate goal of doing exactly what you described and having it defined declaratively in the configuration file, it would be a thing to eventually base the implementation upon.

Sending a trigger command to a topic like ``/home/zwave/Device16/switch/get`` to poll the value from a ZWave device feels a bit non-MQTT, but i see your point. However, what about having a periodic task which polls the values regularly from arbitrary sources and publishes a message to the MQTT bus when detecting a state change? Wouldn't that fit your needs better?

The most straight-forward way to get whole payloads from HTTP to MQTT could also be:

    curl --silent 'http://localhost:8083/ZWaveAPI/Run/devices[16].instances[0].Basic.data.level' | mosquitto_pub -t /home/zwave/Device16 -s

Even when it comes to payload data manipulation, one could think of things like:

    curl --silent https://httpbin.org/ip | jq --raw-output '.origin' | tr --delete '\n' | mosquitto_pub -t test/ip/`hostname` -s

which somehow mimics the functionality from #178. Given, this gets clunky soon so it would be more convenient having it inside mqttwarn based on its internal transformation machinery.

Let us know about your thoughts and about how much you would need the feature as proposed.

Best,
Andreas.

[periodic tasks]: https://github.com/jpmens/mqttwarn/blob/HEAD/README.md#periodic-tasks

**Comment by thucke** [comment]
Hi Andreas,

thank you very much for taking my issue and relating thoughts into account.
Using a CRON mechanism could be a good starting point for many needs and I'll take it in my mind for future use. Actually yet a periodic running task would not fit my needs, I'm afraid.

Why would I prefer an MQTTWARN integrated feature instead of an additional script?
The main reason here is because of security concerns.
The REST-service of ZWAY needs authentication. So I already put username/password in mqttwarn.ini. I aim to have less places as possible where credentials are stored. The best solution would be having only ONE place. INI-file is mandatory for some POSTs I'm doing via MQTTWARN.

The second reason is that a periodic running task would be always a compromise between time lag and system load generated if choosing the period too short. Thinking about alarm mechanisms I like to implement via my connected OpenHAB home automation a time lag which is too large could be an issue.

Greets
Thomas

**Comment by jpmens** [comment]
The feature you're looking for is out of scope for _mqttwarn_.
