### ISSUE TITLE
[mqttwarn] Cannot decode JSON object

### ISSUE THREAD

**Issue by marcelrv** [jpmens/mqttwarn#181]
I'm trying to use payload data from a sensor that is not json coded. Is there a way to avoid warnings like below in the log:

```
 2016-04-17 18:26:35,575 WARNING [mqttwarn] Cannot decode JSON object, payload=20.60: 'float' object has no attribute 'items'
```

**Comment by jpmens** [comment]
Well, it's not an error, but a warning, but I do see what you mean.

Can you confirm that the payload then is processed the way you need it (i.e. correctly given to a target), or do we have a real bug?

**Comment by marcelrv** [comment]
Indeed a warning only. 
I can confirm payload seems to go through anyway.

**Comment by marcelrv** [comment]
thanks

2016-04-18 19:09 GMT+02:00 JP Mens <notifications@github.com>:
