### ISSUE TITLE
Influxdb service 

### ISSUE THREAD

**Issue by jpmens** [jpmens/mqttwarn#183]

**Comment by justinatomatic** [comment]
I've been meaning to have a stab at writing a influxdb plugin. Unfortunately i'm about to move cities so it's unlikely I'll have time to put into it for a couple of months. Happy to test or help out if other's beat me to it.

**Comment by jpmens** [comment]
You should get your priorities right: *first* the plugin; *then* the move! ;-)

**Comment by jpmens** [comment]
@justinatomatic you may now concentrate on your move because @sumnerboy12 has built this. Thanks both of you.

**Comment by justinatomatic** [comment]
Thanks to @sumnerboy12  for the plugin i'll give it a try shortly.  I was thinking of having more options around tag keys and tag values but this is a great start.

**Comment by sumnerboy12** [comment]
Yep - it is a very basic implementation - with plenty of scope for 
improvements - feel free to enhance!
