### ISSUE TITLE
Unable to parse payload - Newbie

### ISSUE THREAD

**Issue by tangoTH** [jpmens/mqttwarn#189]
### Day 2 of learning mqttwarn and file, log, pushover are all working.  Great utility you have here.  I can’t wait to explore further what I can do with my ESP8266 systems.  hopefully I've found the right forum to ask. 

Currently, I receive a numerical value between 20-35 for a temperature reading.
I only want to generate a pushover event if the temperature is higher than 30
But I receive this error in the log

```
2016-05-09 03:42:03,859 DEBUG [mqttwarn] Section [/home/ESP8266-Sensor1/Temp] matches message on /home/ESP8266-Sensor1/Temp. Processing...
2016-05-09 03:42:03,862 WARNING [mqttwarn] Cannot invoke filter function TempPushover_filter defined in /home/ESP8266-Sensor1/Temp: 'module' object has no attribute 'TempPushover_filter'
2016-05-09 03:42:03,863 DEBUG [mqttwarn] Cannot decode JSON object, payload=26: 'int' object has no attribute 'items'
2016-05-09 03:42:03,865 DEBUG [mqttwarn] Message on /home/ESP8266-Sensor1/Temp going to file:Temp
2016-05-09 03:42:03,865 DEBUG [mqttwarn] New `file:Temp' job: /home/ESP8266-Sensor1/Temp
2016-05-09 03:42:03,866 DEBUG [mqttwarn] Message on /home/ESP8266-Sensor1/Temp going to log:warn
2016-05-09 03:42:03,867 DEBUG [mqttwarn] Processor is handling: `file' for Temp
2016-05-09 03:42:03,868 DEBUG [mqttwarn] New `log:warn' job: /home/ESP8266-Sensor1/Temp
2016-05-09 03:42:03,872 DEBUG [file] *** MODULE=services/file.pyc: service=file, target=Temp
2016-05-09 03:42:03,874 DEBUG [mqttwarn] Message on /home/ESP8266-Sensor1/Temp going to pushover:___
2016-05-09 03:42:03,876 DEBUG [mqttwarn] New `pushover:_______’ job: /home/ESP8266-Sensor1/Temp
2016-05-09 03:42:03,878 DEBUG [mqttwarn] Processor is handling: `log' for warn
2016-05-09 03:42:03,882 DEBUG [log] *** MODULE=services/log.pyc: service=log, target=warn
2016-05-09 03:42:03,883 WARNING [log] 26
2016-05-09 03:42:03,885 DEBUG [mqttwarn] Processor is handling: `pushover' for ______
2016-05-09 03:42:03,887 DEBUG [pushover] *** MODULE=services/pushover.pyc: service=pushover, target=_______
2016-05-09 03:42:03,888 DEBUG [pushover] Sending pushover notification to ____ [{'priority': 0, 'retry': 60, 'expire': 3600, 'title': 'mqttwarn'}]...
2016-05-09 03:42:04,404 DEBUG [pushover] Successfully sent pushover notification
```

Here is my mqttwarn.ini relevant components

```
[/home/ESP8266-Sensor1/Temp]
#topic = home/ESP8266-Sensor1/Temp
targets = file:Temp, log:warn, pushover:TangoS6
filter = TempPushover_filter()
```

Attemp #1
```
def TempPushover_filter(topic, message):
#    data = dict(json.loads(message).items()) 
#    if data['message'] > 30
    if payload > 30
    return True
```
Attempt #2
def TempPushover_filter(topic, message):
   return message.find(<30) == -1

Attempt #3
def TempPushover_filter(topic, message):
   return message.payload(<30) == -1

Tried looking here
https://github.com/jpmens/mqttwarn/wiki/Filtering

My questions are
1)  a) Is this a concern “Cannot decode JSON object, payload=26: 'int' object has no attribute 'items’”
    b) Must I format to JSON 
    c) Can I use the raw payload?
2) If #1c is true, then something is wrong with my filter above. I’ve tried a few attempts but cannot seem to find a working config

**Comment by jpmens** [comment]
(Please learn how to format code in a github issue like I've now done for you: three backticks on a line; it makes reading much easier)

Do you have a 

```
functions = 'myfuncs'
```

line to load your functions from a file?

As to your questions: JSON is not mandatory. Make sure to study the README for some examples.

**Comment by tangoTH** [comment]
Thank you for the guidance.  Wasn't aware of the `, in fact I had to go hunting on my keyboard for it.

the functions i have was from the sample ini as
```
functions = 'samplefuncs'
```
I just had a look at the samplefuncs.py file and nope, never modified this and not sure that i know how.

I think I made a mistake that I put the above "Attempt's Into the mqttwarn.py and not into the functions file. 

Do you have some more documentation on how to do this.  Like I said, I was able to get mqttwarn with file, log and pushover running within about 4 hours without ever having touched it, which is a good job by you.

So, I pulled out the following code and placed it into a "myfuncs.py" which is called from the mqttwarn.py

```
def TempPushover_filter(topic, message):
return message.find(<30) == -1
```

This is the error I receive now, probably because I have no idea how to format.  I would just like to parse raw text.

```
2016-05-09 08:33:01,136 WARNING [mqttwarn] Cannot invoke filter function TempPushover_filter defined in /home/ESP8266-Sensor1/Temp: expected an indented block (myfuncs.py, line 12)
2016-05-09 08:33:01,137 DEBUG [mqttwarn] Cannot decode JSON object, payload=26: 'int' object has no attribute 'items'
```

**Comment by jpmens** [comment]
That looks much better, but please note that it's Python code, as the diagnostic message `expected an indented block` tells you.

Within your function, use `print message` so that you see what you're receiving, on the console. I think that will put you in the right direction.

**Comment by tangoTH** [comment]
Just came back to edit my message saying I indented the block in myfuncs.py

I have also used the 'print message' in my function and that appears to be working as seen below

```
root@TH345357:/home/mqttwarn# ./mqttwarn.py
26
36
```
What i'm attempting to do (and failing, but learning) is to perform a pushover notification if the value exceeds 30.

Trying this now
```
def TempPushover_filter(topic, message):
    print message
    # return message.payload(<30) == -1
    if message.payload is > 30
    return True
```

**Comment by jpmens** [comment]
You may have noticed by now, that `message` doesn't contain JSON, but rather your int value as a string. In other words, this should be what you're looking for:

```python
def TempPushover_filter(topic, message):
    temperature = int(message)
    if temperature > 30:
        return False

    return True  # suppress notification
```

Use it with something like this in `mqttwarn.ini`:

```ini
[tt]
filter = TempPushover_filter()
targets = log:info
format = Warning: temperature is above {payload}
```

**Comment by tangoTH** [comment]
Excellent. That was precisely what the problem was.  I was toying around with copying the content to other variables but that wasn't doing anything.

Here is the my final function

```
def TempPushover_filter(topic, message):
    temperature = int(message)
    if temperature <= 30:
        print "supressing notification of %s" % temperature
        return True
```

Now I need to figure a cleaner way to have separate filters and multiple filters as the data returned may not always be a plain integer.  

Wondering if maybe I could assist with the documentation as it wasn't clear to me, as a newbie.

Lastly, if the mqtt message was a phrase such as "The Temperature is 36"  is there a way I can give it an offset or look for a certain string in that phrase?

Phenomenal work. This is a great product and I'd like to contribute if I could.

**Comment by jpmens** [comment]
>  if the mqtt message was a phrase such as "The Temperature is 36" is there a way I can give it an offset or look for a certain string in that phrase

Definitely not. This would be a rather awkward payload IMO. (Just think internationalization, and you'll get my point, quite aside from "why do that? why isn't 36 sufficient in the context of a proper MQTT topic?")

> if maybe I could assist with the documentation as it wasn't clear to me

Patches to improve code and particularly documentation are *always* welcome. ;-)

**Comment by tangoTH** [comment]
Sorry for late reply.  

I'm not sure I understand why a MQTT message cannot be parsed for a string?

What if the MQTT message had more data such as

"Temp 36,  LAT -5.129291, LON 40.21019,  Power Consumption 5" or something like that and I just wanted to rip out a particular part of the message?

Lastly, I cannot help with patches, but maybe help with some documentation on examples?

**Comment by jpmens** [comment]
The message can be parsed for a string, but mqttwarn doesn't do that, though you can do so in your filter function. 

What I'd do, if I had control of the publisher, is to produce JSON
{"temp":36, "lat":-5.12, "lon":40.2, "power":5}

And yes, documentation patches are fine; I thought I made that clear. :)

**Comment by tangoTH** [comment]
Thank you for the help.  I'll figure out how to help (new to github) with docu/examples and revert back.
