### ISSUE TITLE
A question about possible mqttwarn use

### ISSUE THREAD

**Issue by kaushalender** [jpmens/mqttwarn#190]
Please bear with me if it looks foolish  but very new bigner to mqtt

I am building a client which will read the information from the device and  send the readings it to mosquito broker where application will be connected to get the readings,when connection is idle it will send a heartbeat between client and broker, but in my environment there is disconnection happens because of N number of problem.So I was thinking to enable LWT functionality.

I am trying to use mqttwarn as client and trying to simulate, when mqttwarn recieve LWT message on topic, it should also publish local time in the file, so that I can see from how long connection is broken.

Also I am trying to  simulate following,

 I am generating a sequence number to check that node is down due to network connectivity or  got down due to power issues .When there is mismatch in the sequence between connection broke and connection restored than it is a network problem but if sequence number is in sequence  between connection broke and connection restored than most likely device got shutdown

Please Help me  and thanks in advance

**Comment by jpmens** [comment]
You might be able to do this using custom made functions within mqttwarn; they are documented in the README.
