### ISSUE TITLE
Microsoft SQL plugin for message storage?

### ISSUE THREAD

**Issue by TommySharpNZ** [jpmens/mqttwarn#200]
Hi guys, I'm trying to get data out of my OpenHAB instance and store the item state changes in a MS SQL database. This is my preference as I work with MS SQL servers all day.....

Is this something that could be developed some day as an addin for mqttwarn?

**Comment by jpmens** [comment]
It _could_ be done, I suppose, but we won't. If you or somebody else contribute code & documentation, I'd probably take it.

**Comment by sumnerboy12** [comment]
Shouldn't be too hard to implement with something like http://www.pymssql.org/en/latest/...

**Comment by TommySharpNZ** [comment]
Thanks guys!
At the moment I'm looking into the JDBC persistence binding for OpenHAB which could potentially allow me to persist data directly to an MSSQL database.
