### ISSUE TITLE
gss example are not working for me

### ISSUE THREAD

**Issue by johnypony3** [jpmens/mqttwarn#205]
Hi all, this project is very promising, thank you for your hard work.
The gss example I could not get to work. I believe its an authentication issue. Follow allong as we go full circle. :D 
`

> [config:gss]
> username    = your.username@gmail.com
> password    = yourpassword
> targets     = {
>                # spreadsheet_key                               # worksheet_id
>     'test': [ 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',  '**od6**']
>     }
> `
> I have no idea how to get the worksheet id for that sample. Throughout the internet there are conflicting reports of the value 'od6' not being usable anymore as the default sheet. I have tried many combinations of values none worked for me, which is why I believe it to be an authentication issue. Can someone confirm that they were able to get this example to work?

**Comment by jpmens** [comment]
dup of #206
