### ISSUE TITLE
gss2 example is not working for me

### ISSUE THREAD

**Issue by johnypony3** [jpmens/mqttwarn#206]
I followed the steps to get all of the keys, everything works, the `oauth2.store` was automatically created and this as well as the log means that everything is set up properly. I do have the client.secrets file and the `oauth2_code` is retrieved from the url in the log. Speaking of the log, here I am trying to send these 3 values to a spread sheet:

`{
    "time": "22600",
    "photocell": "276",
    "ledbrightness": 0
}`

Spreadsheet with these values in a1-c1: `time   photocell   ledbrightness` 

Here is what my log looks like, it specifically is saying that the row was added, yet when I open the sheet, it only has the headers.

Am I missing something? I think that the values are going into lala land....
Thanks!

> 2016-07-24 00:28:37,484 DEBUG [mqttwarn] Message received on /ota/mkr1k/report: { "time":"135187", "photocell":"273", "ledbrightness":0}
> 2016-07-24 00:28:37,485 DEBUG [mqttwarn] Section [/ota/mkr1k/report] matches message on /ota/mkr1k/report. Processing...
> 2016-07-24 00:28:37,485 DEBUG [mqttwarn] Message on /ota/mkr1k/report going to file:mylog
> 2016-07-24 00:28:37,485 DEBUG [mqttwarn] New `file:mylog' job: /ota/mkr1k/report
> 2016-07-24 00:28:37,485 DEBUG [mqttwarn] Message on /ota/mkr1k/report going to log:info
> 2016-07-24 00:28:37,485 DEBUG [mqttwarn] Processor #0 is handling:`file' for mylog
> 2016-07-24 00:28:37,485 DEBUG [mqttwarn] New `log:info' job: /ota/mkr1k/report
> 2016-07-24 00:28:37,486 DEBUG [file] *** MODULE=services/file.pyc: service=file, target=mylog
> 2016-07-24 00:28:37,486 DEBUG [mqttwarn] Message on /ota/mkr1k/report going to gss2:test
> 2016-07-24 00:28:37,487 DEBUG [mqttwarn] New`gss2:test' job: /ota/mkr1k/report
> 2016-07-24 00:28:37,488 DEBUG [mqttwarn] Job queue has 2 items to process
> 2016-07-24 00:28:37,488 DEBUG [mqttwarn] Processor #0 is handling: `log' for info
> 2016-07-24 00:28:37,488 DEBUG [log] *** MODULE=services/log.pyc: service=log, target=info
> 2016-07-24 00:28:37,488 INFO  [log] { "time":"135187", "photocell":"273", "ledbrightness":0}
> 2016-07-24 00:28:37,490 DEBUG [mqttwarn] Job queue has 1 items to process
> 2016-07-24 00:28:37,490 DEBUG [mqttwarn] Processor #0 is handling:`gss2' for test
> 2016-07-24 00:28:37,490 DEBUG [gss2] **\* MODULE=services/gss2.pyc: service=gss2, target=test
> **2016-07-24 00:28:37,490 DEBUG [gss2] Adding row to spreadsheet https://docs.google.com/spreadsheets/d/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/edit [Sheet2]**...
> 2016-07-24 00:28:37,491 DEBUG [gss2] Trying to use credentials from file 'oauth2.store'.
> 2016-07-24 00:28:37,493 INFO  [connectionpool] Starting new HTTPS connection (1): spreadsheets.google.com
> 2016-07-24 00:28:38,099 DEBUG [connectionpool] "GET /feeds/spreadsheets/private/full HTTP/1.1" 200 None
> 2016-07-24 00:28:38,324 DEBUG [connectionpool] "GET /feeds/worksheets/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/private/full HTTP/1.1" 200 None
> 2016-07-24 00:28:38,715 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full?range=A1%3AZ1&return-empty=true HTTP/1.1" 200 None
> 2016-07-24 00:28:39,060 DEBUG [connectionpool] "GET /feeds/worksheets/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/private/full/oe2pvc5 HTTP/1.1" 200 None
> 2016-07-24 00:28:39,259 DEBUG [connectionpool] "PUT /feeds/worksheets/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/private/full/oe2pvc5/-u3c64o HTTP/1.1" 200 None
> 2016-07-24 00:28:39,468 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C1 HTTP/1.1" 200 None
> 2016-07-24 00:28:39,664 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C2 HTTP/1.1" 200 None
> 2016-07-24 00:28:39,858 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C3 HTTP/1.1" 200 None
> 2016-07-24 00:28:40,032 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C4 HTTP/1.1" 200 None
> 2016-07-24 00:28:40,231 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C5 HTTP/1.1" 200 None
> 2016-07-24 00:28:40,438 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C6 HTTP/1.1" 200 None
> 2016-07-24 00:28:40,625 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C7 HTTP/1.1" 200 None
> 2016-07-24 00:28:40,818 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C8 HTTP/1.1" 200 None
> 2016-07-24 00:28:41,237 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C9 HTTP/1.1" 200 None
> 2016-07-24 00:28:41,414 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C10 HTTP/1.1" 200 None
> 2016-07-24 00:28:41,632 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C11 HTTP/1.1" 200 None
> 2016-07-24 00:28:41,813 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C12 HTTP/1.1" 200 None
> 2016-07-24 00:28:41,990 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C13 HTTP/1.1" 200 None
> 2016-07-24 00:28:42,164 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C14 HTTP/1.1" 200 None
> 2016-07-24 00:28:42,345 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C15 HTTP/1.1" 200 None
> 2016-07-24 00:28:42,518 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C16 HTTP/1.1" 200 None
> 2016-07-24 00:28:42,698 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C17 HTTP/1.1" 200 None
> 2016-07-24 00:28:42,878 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C18 HTTP/1.1" 200 None
> 2016-07-24 00:28:43,047 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C19 HTTP/1.1" 200 None
> 2016-07-24 00:28:43,216 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C20 HTTP/1.1" 200 None
> 2016-07-24 00:28:43,411 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C21 HTTP/1.1" 200 None
> 2016-07-24 00:28:43,596 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C22 HTTP/1.1" 200 None
> 2016-07-24 00:28:43,796 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C23 HTTP/1.1" 200 None
> 2016-07-24 00:28:43,979 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C24 HTTP/1.1" 200 None
> 2016-07-24 00:28:44,164 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C25 HTTP/1.1" 200 None
> 2016-07-24 00:28:44,372 DEBUG [connectionpool] "GET /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/R1100C26 HTTP/1.1" 200 None
> 2016-07-24 00:28:44,749 DEBUG [connectionpool] "POST /feeds/cells/1DQWVTuCjdsQfzMgvQqe1r96G9zEo7OBBw6MNjQorg0Q/oe2pvc5/private/full/batch HTTP/1.1" 200 None
> **2016-07-24 00:28:44,754 DEBUG [gss2] Successfully added row to spreadsheet**
> 2016-07-24 00:28:44,788 DEBUG [mqttwarn] Job queue has 0 items to process

**Comment by jpmens** [comment]
I see `Successfully added row to spreadsheet` and the previous `POST` returns 200. Where's the problem?
