### ISSUE TITLE
Multiple Devices Sending Same Topic

### ISSUE THREAD

**Issue by tony7881** [jpmens/mqttwarn#207]
I like mqttWarn. Thank you for this work. I'm trying to have multiple devices publish a topic using the same topic name. mqttWarn is setup to send the topic data to mysql. With one device, all works. With more than one it's failing. Should mqttWarn be able to handle this or will I need to use unique topics / targets?

**Comment by jpmens** [comment]
You don't say what "failing " means. I'm guessing your devices are using
same Mqtt clientid which means the broker will kick one of them out.

**Comment by tony7881** [comment]
Sorry for a cryptic issue. You were dead on with your reply. I had both devices using the same client ID. Modified code and works perfectly. Thank you for your help.
