### ISSUE TITLE
Dealing with high availability 

### ISSUE THREAD

**Issue by sylvek** [jpmens/mqttwarn#218]
How do you deal with high availability aspect? 
May it be possible to launch several mqttwarn over a same mqtt broker?

**Comment by jpmens** [comment]
You can launch as many mqttwarn as you like. If they connect to the same broker, make sure you use different _clientid_s. Do keep in mind though, that your mqtt broker will then become the SPOF.

**Comment by sylvek** [comment]
Good, but every instance of mqttwarn should receive the same messages?

**Comment by jpmens** [comment]
If they should receive the same message, configure them the same way. If they should not, then don't.

**Comment by sylvek** [comment]
okay, thks :)
