### ISSUE TITLE
formatmap functions

### ISSUE THREAD

**Issue by przemas75** [jpmens/mqttwarn#219]
Hi,
There is something strange with formatmap functions. If i fetch clear mqttwarn from github, install fresh mosquitto (all new, as its new virtual machine), and adjust mqttwarn.ini file to have very simple config:

> functions = 'samplefuncs'
> launch    = file, log
> [config:file]
> append_newline = True
> targets = {
>     'f01'       : ['/tmp/f.01'],
>     'log-me'    : ['/tmp/log.me'],
>     'mqttwarn'  : ['/tmp/mqttwarn.err'],
>     }
> [hello/1]
> targets = file:f01, file:log-me
> ;format = u'{name}: {number} => {_dthhmm}'
> datamap = OwnTracksTopic2Data()
> format  = OwnTracksConvert()

These are the things i adjusted, all others are untouched.
So i want to have a topic with two targets (services) - or even more like twitter, xbmc etc.. But for simplicity its just two and its 'file' type.
Then, i publish example message:

> mosquitto_pub -t hello/1  -m '{"_type":"transition","tid":"pa","acc":30.991833,"desc":"mylocation","event":"enter","lat":xx.371446666,"lon":ss.62864,"tst":1479304407,"wtst":1458970888,"t":"c"}'

And in those two files coming from services/targets i will receive outputs:

> cat /tmp/f.01
> unknown unknown 2016-11-16 13:53:27 at location xx.3714490167,ss.6286274

This comes from the first target, it is correct one.
And from the second target (and third, fourth if existing) the output looks like:

> cat /tmp/log.me
> OwnTracksConvert()

It is because tst changes from  epoch time to converted one, but im not sure if the behavior is correct.
The log file with debug of mqttwarn:

> 2016-11-17 20:44:53,230 DEBUG [mqttwarn] Message on hello/1 going to file:f01
> 2016-11-17 20:44:53,230 DEBUG [mqttwarn] New `file:f01' job: hello/1
> 2016-11-17 20:44:53,230 DEBUG [mqttwarn] Message on hello/1 going to file:log-me
> 2016-11-17 20:44:53,230 DEBUG [mqttwarn] New `file:log-me' job: hello/1
> 2016-11-17 20:44:53,230 DEBUG [mqttwarn] Processor #0 is handling: `file' for f01
> 2016-11-17 20:44:53,231 DEBUG [file] *** MODULE=services/file.pyc: service=file, target=f01
> 2016-11-17 20:44:53,232 DEBUG [mqttwarn] Job queue has 1 items to process
> 2016-11-17 20:44:53,232 DEBUG [mqttwarn] Processor #0 is handling: `file' for log-me
> 2016-11-17 20:44:53,233 WARNING [mqttwarn] Cannot invoke OwnTracksConvert(): invalid literal for int() with base 10: '2016-11-16 13:53:27'
> 2016-11-17 20:44:53,234 DEBUG [file] *** MODULE=services/file.pyc: service=file, target=log-me
> 2016-11-17 20:44:53,235 DEBUG [mqttwarn] Job queue has 0 items to process

Shouldn't be better format function run only once?
It's just my observation.

**Comment by jpmens** [comment]
This sounds like a bug. I would apprecate you creating a minimal environment & configs to demonstrate that it's a bug.

**Comment by egraaf** [comment]
I think I ran into the same thing. function OwnTracksConvert in samplefuncs.py gets called twice, once for target log:info, and once for target file:f01 in the example config

Since OwntracksConvert modifies the data dict, the second time the function is called it gets a formatted date instead of a unix timestamp.

I changed OwntracksConvert to the following to stop it modifying the global dict:

(I also imported the copy module)

def OwnTracksConvert(data):
    if type(data) == dict:
        datacopy = copy.copy(data)
        tst = data.get('tst', int(time.time()))
        datacopy['tst'] = time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime(int(tst)))
        # Remove these elements to eliminate warnings
        for k in ['_type', 'desc']:
            datacopy.pop(k, None)

        return "{username} {device} {tst} at location {lat},{lon}".format(**datacopy)

**Comment by shymega** [comment]
@egraaf That fixed it for me; thanks!

**Comment by amotl** [comment]
With the update referenced above, this issue might be closed after merging.
