### ISSUE TITLE
not sent to syslog server

### ISSUE THREAD

**Issue by skythink** [jpmens/mqttwarn#222]
hi guys.. btw nice project for this. so awesome ! .

i have a little trouble to sent to syslog server. i have configured like this 

[config:syslog]
title = mqtt-debian
priority = -2
targets = {
        'user' : ['user','debug', 'pid'],
        'kernel' : ['kernel','info', 'pid'],
    }

and i see in log mqttwarn.log a subscribed have a message from publisher, but when i see a syslog server listen 127.0.0.1:514 (UDP or TCP) not any message from mqttdwrn. 

anyone help ??? 
thanks :)

**Comment by egadgetjnr** [comment]
Hi @skythink,

I love the project! I think @jpmens has done an amazing job!
A common issue I've seen people run into is not declaring the Modules to use under the .ini file.

Have you set the following in your ini?

```
; name the service providers you will be using.
launch    = file, log, syslog
```

(anyone, please feel free to stop me if I'm wrong)

**Comment by skythink** [comment]
thanks @egadgetjnr  for the reply. im try to add syslog to launch. but result same. 

maybe u can share you're config file to sent syslog in mqtt.ini ?
im tail in server rsyslog in same machine with mqttd-warn and broker too, results still same :'(

**Comment by jpmens** [comment]
Make sure that the syslog messages for the priority and facility you are using are actually configured to be stored somewhere; it may be quite possible that, say, rsyslog or syslog-ng or whichever are silently dropping these messages because their configuration tells them to.

**Comment by skythink** [comment]
@jpmens  thanks man u'r awesome ... im fix a problem when i see your iot conference in youtube... its helpfull ... 

god bless you :)
