### ISSUE TITLE
Can't load telegram service (services/telegram.py)

### ISSUE THREAD

**Issue by skythink** [jpmens/mqttwarn#225]
hi guys... i have problem with log like this 

Can't load telegram service (services/telegram.py): No module named requests

im using freebsd 11.x amd64. i see in folder services a module telegram.py , but when im installing in linux no problem. can help me ??

thanks

**Comment by jpmens** [comment]
Have you read the diagnosting? It says "no module named requests".  
Install it.

**Comment by skythink** [comment]
damn i'm so stupid... 

thanks @jpmens  ... i know you mean a "requests" module, it turns out that module python :'(

soved with command in freebsd 11.x
pkg install py27-requests 

thanks
