### ISSUE TITLE
NMA dynamic config

### ISSUE THREAD

**Issue by marcelbohmer** [jpmens/mqttwarn#226]
Hi

Is it possable to pass json data from the message paload to the config section of NMA.

eg:
message payload: {"app" : "test" , "event" : "info", "msg" : "This is a test msg" }
config line: 'testphone' : ['api key' , payload.app, payload.event ]

Thanks in advance

**Comment by jpmens** [comment]
No, this is not possible. It's not a bad idea though, if you want to submit code for it.
