### ISSUE TITLE
Add html support PushOver

### ISSUE THREAD

**Issue by seaside1** [jpmens/mqttwarn#227]
Hi!

Would be very nice to add html support to PushOver
See:

https://pushover.net/api#html

**Comment by psyciknz** [comment]
What happens if the payload contains the html formatting codes now?  Do they get stripped out, or do they survive and take effect.

I assume that is what the OP is after?

**Comment by jpmens** [comment]
Closing now. Feel free to re-open when/if you have added the functionality to the service plugin.
