### ISSUE TITLE
Unable to use slack service using python2

### ISSUE THREAD

**Issue by seaside1** [jpmens/mqttwarn#230]
Hi!

I get

2017-01-31 22:16:32,384 DEBUG [slack] *** MODULE=services/slack.pyc: service=slack, target=habbot
2017-01-31 22:16:32,385 ERROR [slack] slacker module missing

When trying to use the slacker service.

Running this simple py

```
from slacker import Slacker
slack = Slacker('my-api-key')
# Send a message to #general channel
slack.chat.post_message('#general', 'Hello fellow slackers!')

```
works, when doing this:

python3 test.py 

but not with python2.7
python2 test.py

My mqttwarn.service
xecStart=/bin/sh -c "/opt/mqttwarn/.venv27/bin/python /opt/mqttwarn/mqttwarn.py ${MQTTWARN_OPTIONS} >>${STDOUT} 2>>${STDERR}"

So it seem to run python2.7

slacker was install with
pip install slacker

Is it possible to resolve this conflict with versions?

Regards, S

**Comment by seaside1** [comment]
Sloved by .venv27/bin/pip install slacker
Me failing to understand how to add dependencies to mqttwarn.

**Comment by jpmens** [comment]
Install the module with Python2
