### ISSUE TITLE
[Feature Request] Parse Platform Module

### ISSUE THREAD

**Issue by egadgetjnr** [jpmens/mqttwarn#233]
Unfortunately I'm not to good with Python and I'm wondering if you or someone could possibly help me.

I'm currently playing around with a [Parse Server](https://github.com/ParsePlatform/parse-server) and would like to integrate this with some MQTT devices.

Are you possibly able to help me with creating a connector/module/plugin to push a payload to an Parse Server API based on topics?

**Comment by jpmens** [comment]
Closing for apparent lack of interest
