### ISSUE TITLE
Request for assistance

### ISSUE THREAD

**Issue by flick116** [jpmens/mqttwarn#239]
This isn't an issue, but a request for some assistance.  I am using mqttwarn to email / notify me of updates from my alarm system.  It's working perfectly, in that I am receiving the relevant message via SMTP no problem.  But, I would like to be able to format the outgoing message better based on what is in the payload.

The payload is as follows:

{"client_ip": "xxx.xxx.xxx.xxx", "value_type": "User", "extra_text": "name", "area": 1, "account": xxxx, "timestamp": "21:05:40 on Wednesday 05 April 2017", "client_port": xxxxx, "value": 2, "event": "System has been armed"}

What I would like to be able to do is update some of the values based on what was received, so for example, if "value" equals 2 and "value_type" equals "User", then add a new variable "newvalue" to be "Some text" and if "value" equals 3 and "value_type" equals "User", change "newvalue" to be "Different text", and if "value" equals 2 and "value_type" equals "Zone", then change "newvalue" to be "Some more text".  I can then use "newvalue" in the outgoing message, which should make the formatting look a lot better.  Is this possible?  I'm not a coder so apologies if this is a stupid question.  I did go through the documentation, but couldn't see how to do the above.

Kind regards...

**Comment by dummylabs** [comment]
Jinja templates feature is what you want. It gets json payload of your message as set of variables allowing you to format output message using any logic you need. For example data above jinja template could be: 
```
{% if value == "2" and value_type == "User" %}
  {"newvalue":"Some text", "value":"{{value}}", "value_type":"{{value_type}}"}
{% elif value == "3" and value_type == "User" %}
  {"newvalue":"Different text", "value":"{{value}}", "value_type":"{{value_type}}"}
{% elif value == "2" and value_type == "Zone" %}
  {"newvalue":"Some more text", "value":"{{value}}", "value_type":"{{value_type}}"}
{% endif %}
```
Within Jinja template condition block you'd put formatted ouput message as you need it. Tip: you can skip value and value_type data in output message if you don't need it anymore.

Then name this file mytemplate.j2 and put it into `Templates` folder in your mqttwarn installation.
In `mqttwarn.ini` section of your service add template=mytemplate.j2

I didn't tested this example but you got the idea. For jinja templates documentation refer to http://jinja.pocoo.org/
