### ISSUE TITLE
[Feature Request] Should run as daemon process in background

### ISSUE THREAD

**Issue by openbufo** [jpmens/mqttwarn#241]

**Comment by jpmens** [comment]
Not necessary at all; there are plenty of launchers which'lld o this (eg. supervisord)

**Comment by amotl** [comment]
Dear @openbufo,

please have a look at https://github.com/jpmens/mqttwarn/tree/master/etc, there you will find appropriate launcher definition files, e.g. for [systemd], [SysV init], [procd] and [supervisor].

With kind regards,
Andreas.

[systemd]: https://github.com/jpmens/mqttwarn/blob/master/etc/mqttwarn.service
[SysV init]: https://github.com/jpmens/mqttwarn/blob/master/etc/mqttwarn.init
[procd]: https://github.com/jpmens/mqttwarn/blob/master/etc/OpenWRT.init
[supervisor]: https://github.com/jpmens/mqttwarn/blob/master/etc/supervisor.ini
