### ISSUE TITLE
how to insert timestamp to mysql ?? 

### ISSUE THREAD

**Issue by skythink** [jpmens/mqttwarn#247]
i have apps to sent every minutes data. but i need query to calculate data in my apps. i need type data time for do that . when im create field with type data timestamp and device send to mqtt then mqttwarn input to mysql. i see a value null like this . 

+---------------------+-----------+--------------+------+------+------------+---------------+
| time_stamp          | device_id | device_alias | lng  | lat  | heart_rate | interval_rate |
+---------------------+-----------+--------------+------+------+------------+---------------+
| 2017-06-07 10:19:16 | NULL      | NULL         | NULL | NULL |       NULL |          NULL |
+---------------------+-----------+--------------+------+------+------------+---------------+

any suggest ?? thank you

**Comment by jpmens** [comment]
Please learn about MySQL; this is not the place for that.
