### ISSUE TITLE
rrdtool service will always use "now" as timestamp 

### ISSUE THREAD

**Issue by otdftr** [jpmens/mqttwarn#248]
Great idea to link mqtt and rrd, but my use case involves using **retained data** (mosquitto_pub -r option) for a "last known good" appoach and **manually submitting older data with distinct timestamps**. As rrdtool simply drops / ignores updates with a timestamp encountered before, replays and duplicate submission will not cause any harm to the rrd database.

Unfortunately, mqttwarn's rrd service always adds an N: in front of the submitted data, which will break all my above use cases. I would need a rrdtool call like
`rrdtool.update(item.addrs + text.split())`
for the update. This would require the 'N:' to be present in the format= parameter of mqttwarn.ini if needed - which would break existing configurations.

So I suggest the following amendment / enhacement to the rrdtool service (patch is here: [rrdtool.py.patch.zip](https://github.com/jpmens/mqttwarn/files/1072479/rrdtool.py.patch.zip)):
````
-        rrdtool.update(item.addrs, "N:" + text)
+       # mofified by otfdr @ github to accept abitray arguments with
+       # the payload and to not always add the 'N' in front
+       # 2017-06-05
+       if re.match( "^\d+$", text ):
+               rrdtool.update(item.addrs, "N:" + text)
+       else:
+               rrdtool.update(item.addrs + text.split())
````

This will treat plain numeric msg/text as before - prefixing it with 'N:' - but will also provide for passing timestamed data such as `1497375249:68` and would leave it to the configurator's discretion whether to place extra parameters in the `[config:rrdtool]` section _or_ in the `format =` of the event config.

### Use case / application note

![battery gauges through owntracks mqtt mqttwarn rrdtool](https://user-images.githubusercontent.com/1713611/27098184-f9f32cfe-5076-11e7-8410-268fd2721085.png)

With the amendment, my mqttwarn.ini for a hook-up owntracks > mqtt > rrd goes like
````
; [...]

[config:mqttpub]
targets = {
    'batt' : [ 'datalog/sensors/batt/{device}', 0, True ],
    }

; now, batt gauge writing to - as we will have retained = old data, the standard N:<message> of
; the standard rrdtool service will not help -> tweak rrdtool to not add the N: and thus allow 
; timestamps for historic data. duplicates are no problem, because rrdtool will discard them

[config:rrdtool]
targets = {
        # 'battsensor': [ '/srv/rrd/sensors/{sensor_id}.rrd', '-t', 'batt' ],
        # -> aah, no: use the format= an put everything there
        'battsensor': [ ],
        }

; [...]

[owntracks-battery-log]
topic = owntracks/+/+
targets = log:info, mqttpub:batt
datamap = OwnTracksTopic2Data()
filter  = OwnTracksBattFilterOS()
format  = OwnTracksBattFormatOS()
; extract mobile device's batt info from owntracks messages,
; create payload containing {sensor_id} {ts} {batt} ( timestamp / battery 
; gauge ) publish as topic datalog/sensors/batt/{device}
; !! function params must be function() w/o params, called with dictionary of data

[datalog-battery-log]
topic = datalog/sensors/batt/+
targets = log:info,rrdtool:battsensor
format = /srv/rrd/sensors/{sensor_id}.rrd -t batt {ts}:{batt}
; push battery gauge data to rrd

; [...]
````

**Comment by otdftr** [comment]
forked & applied patch: https://github.com/jpmens/mqttwarn/commit/64aa0ad29202a97c460b600c116bd0fae3dc5707

**Comment by jpmens** [comment]
I will take a PR for this.

**Comment by otdftr** [comment]
sent you 
https://github.com/otdftr/mqttwarn/pull/1
https://github.com/otdftr/mqttwarn/pull/2
(sorry, 2 requests - one for code, one for doc)

regards
olaf

**Comment by jpmens** [comment]
those are patches on your fork; you need to create a pull request to *this* repository

**Comment by otdftr** [comment]
ooops, should be done now

**Comment by jpmens** [comment]
Closing via #250
