### ISSUE TITLE
mysql topic column

### ISSUE THREAD

**Issue by solucionesmipc** [jpmens/mqttwarn#252]
hi;

is there a way to store topic in a column when using mysql?

ex:    i am storing all mesasge under topic /device/xxxxxxx

if so, which file should i modify?

thanks´

luis

**Comment by solucionesmipc** [comment]
hi:

i added a second sql query in mysql.py but i dont know the "topic" variable

**Comment by jpmens** [comment]
Changing the `.py` is fine if you're aware it'll be overwritten when you upgrade ...

Look at `alldata=()` and functions in the README.

**Comment by solucionesmipc** [comment]
hi JP, thanks for your help, i need a little more help

i added following to samplefuncs.py file 


def topico(topic):
    if type(topic) == str:
        try:
            #command/deviceid
            parts = topic.split('/')
            deviceid = parts[1]
        except:
            deviceid = 'unknown'
   return dict(device=deviceid)
   return None


i added in mqttwarn.ini

[devices]
topic = command/#
targets = mysql:m2
alldata = topico()

[config:mysql]
host  =  'localhost'
port  =  3306
user  =  'xxxxx'
pass  =  'xxxxxx'
dbname  =  'database_name'
targets = {
          # tablename  #fallbackcolumn #deviceid
 'm2'   : [ 'a_activity',   'full'  , 'device'          ]
  }

mysql table is ready with columns created

please guide me what else should i make now?


thanks a lot


luis

**Comment by jpmens** [comment]
Closed due to inactivity.
