### ISSUE TITLE
pushbullet multiple targets

### ISSUE THREAD

**Issue by modestos** [jpmens/mqttwarn#255]
I try to push messages to multiple targets (dev1, dev2) using pushbullet.
I use the following in my mqtt:
[config:pushbullet]
targets = { 'dev1' : [ 'aaaaaaaaaaaaaaa', 'bbbbbb' ],  'dev2' : [ 'cccccccccccccccc', 'dddddd' ] }

[test/+]
targets = pushbullet:dev1, pushbullet:dev2, file:mylog, log:info 

It only pushes messages to dev2. (API keys & dev IDs are correct, dev1 works perfect on its own)

Regards,
mod

**Comment by jpmens** [comment]
Is the data in `file:mylog` and `log:info`? Show me what happens with debugging enabled.

**Comment by modestos** [comment]
Hi JP,

Thanks for the quick reply.
I found out that the following syntax worked (notice the difference on the trailing comma).
```
targets = { 'dev1' : [ 'aaaaaaaaaaaaaaa', 'bbbbbb' ], 'dev2' : [ 'cccccccccccccccc', 'dddddd' ], }

[test/+]
targets = pushbullet:dev1, pushbullet:dev2, file:mylog, log:info
```

mod
