### ISSUE TITLE
transformation of JSON messages

### ISSUE THREAD

**Issue by dkeipp** [jpmens/mqttwarn#261]
At moment I'm playing around with an ESP8266 with esp-link firmware attached to a arduino.
The esp-link firmware itself produces mqtt messages which are JSON formatted:
Topic: device/subdevice/esp Message:{"rssi":-46, "heap_free":15856}

I want to deliver the values of rssi and memory (heap) to grafite with the carbon plugin and use the topic as metric name (like normal..)
The values should be delivered to graphite like this: device.subdevice.esp.rssi -46 [timestamp]

I'm not able to solve this by myself using the documentation. I also don't know if it is possible to transform the data like I described.
So its a documentation issue or a feature request :-)

**Comment by jpmens** [comment]
Show us what you've tried so far. (I don't want to do your homework. :-)

**Comment by jpmens** [comment]
Closed due to inactivity.
