### ISSUE TITLE
Filtering topic by payload

### ISSUE THREAD

**Issue by psyciknz** [jpmens/mqttwarn#262]
If I have a topic that is very well used.  It's essentially a state of an alarm, and every state is posted on this one topic.

Now I could update the source and make it into a defined topic (and I may just do that), but is there a way that I can get mqttwarn to filter the topic based on the payload string?

```
Example payload messages:
Event:Zone open;SubEvent:Zone 4
Event:Zone OK;SubEvent:Zone 4
**Event:Button C pressed on remote;SubEvent:Remote control number 4**
Event:Zone open;SubEvent:Zone 4
Event:Partition status;SubEvent:Entry delay started
Event:Zone open;SubEvent:Zone 11
```

So technically, the event I want to trap is that Button C one.  The subevent part of the string I want ignored.

Can I do this in config, or should I write a format script that looks for certain text?

**Comment by jpmens** [comment]
I think you're wanting a `grep`-type thing, but we don't have that. Your best bet is to write a function to do that (see `functions` in the README.)
