### ISSUE TITLE
Multiple mysql targets: two table to fill from 2 different topics

### ISSUE THREAD

**Issue by CarloP1967** [jpmens/mqttwarn#263]
At first thanks for your great job made with mqttwarn.
I had a problem configure mysql plugin to save data from two different queue in two different mysql tables: below my config 

[config:mysql]
host  =  'localhost'
port  =  3306
user  =  'user'
pass  =  'pass'
dbname =  'MyHome'
targets = {
  'Alarms'      : [ 'Alarms', 'Event' ]
        }
        ,
          {
  'TempUmid'    : [ 'Ambience_Parameters', 'Value' ]
        }

[MyHome/Studio01/ParametriAmbientali]
targets = mysql:TempUmid
[MyHome/Alarms]
targets = mysql:Alarms

Starting the script it's hang when connecting to the broker (with one targets work like a charm)

Sure it's a config problem, pleae can me give me some suggest?
Thanks a lot

**Comment by jpmens** [comment]
Please provide a full minimal configuration so that I can attempt to reproduce the issue.

**Comment by jpmens** [comment]
Closed due to inactivity.
