### ISSUE TITLE
Error in functions file, not logged, and config is ignored

### ISSUE THREAD

**Issue by psyciknz** [jpmens/mqttwarn#264]
I've found an issue, that is there's a coding error in the functions python file, eg an else missing the :
Then the config for mqttwarn does not complete, none of the topics are subscribed.  But in doing so, there's no warning or error listed in log that an issue has been found.

**Comment by jpmens** [comment]
Show me exactly where the problem is.

**Comment by jpmens** [comment]
Closed due to inactivity.
