### ISSUE TITLE
SMTP module does not work, username/password has to be cast as string

### ISSUE THREAD

**Issue by daballiemo** [jpmens/mqttwarn#268]
When using SMTP the following is logged and the email is not send:

2017-10-10 12:08:31,596 WARNING [smtp] Error sending notification to SMTP recipient xxx, addresses: ['xxx.yyyy@wwww.nl']. Exception: character mapping must return integer, None or unicode
2017-10-10 12:08:31,607 WARNING [mqttwarn] Notification of smtp for `home/messages/email' FAILED or TIMED OUT

smtp.py has to be changed were its calls smtplib with username/password because these have to be passed as string

        if username:
            server.login(str(username), str(password))
        server.sendmail(sender, smtp_addresses, msg.as_string())

**Comment by jpmens** [comment]
Show me a minimal, reproducible config please.

**Comment by daballiemo** [comment]
user@OpenHAB2:/opt/mqttwarn$ cat mqttwarn.ini
[defaults]
hostname  = 'localhost'
port      = 1883
username     = None
password     = None
clientid     = 'mqttwarn'
lwt          = 'clients/mqttwarn'  ; lwt payload is '0' or '1'
skipretained = True
cleansession = False

; logging
logformat = '%(asctime)-15s %(levelname)-5s [%(module)s] %(message)s'
logfile   = '/var/log/mqttwarn.log'

; one of: CRITICAL, DEBUG, ERROR, INFO, WARN
loglevel     = DEBUG

; path to file containing self-defined functions for formatmap, alldata, and datamap
; omit the '.py' extension
;functions = 'myfuncs'

; name the service providers you will be using.
launch	 = file, log, smtp, telegram

; the cd is performed before loading service plugins, so it should
; contain a `services/' directory with the required service plugins.
directory = '/opt/mqttwarn/'

[config:file]
append_newline = True
targets = {
    'mylog'     : ['/tmp/mqtt.log']
	}

[config:log]
targets = {
    'info'   : [ 'info' ]
	}

[config:telegram]
timeout = 60
parse_mode = 'Markdown'
token = 'xxxxxxxxxxxxxxxxxxx'
use_chat_id = True
targets = {
	'j01' : ['123456789']
	}

[config:smtp]
server  =  'xxxxxxxxxxxx:587'
sender  =  "MQTTwarn <user@domain.nl>"
username  =  xxxxxxxxx
password  =  yyyyyyyyy
starttls  =  True
# Optional send msg as html or only plain text
htmlmsg   =  False
targets = {
    '1'     : [ "user1@domain1.nl" ],
    '2'  : [ "user2@domain2.nl"]
	}

[home/notification/email/1]

targets = smtp:1

[home/notification/telegram/#]
targets = telegram
user@OpenHAB2:/opt/mqttwarn$

**Comment by jpmens** [comment]
Thank you.
