### ISSUE TITLE
Parsing data array into mysql

### ISSUE THREAD

**Issue by rweller59** [jpmens/mqttwarn#271]
I've got the mysql plugin working fine with a 'standard' json format. I'm trying to figure out how I can parse a data array into a db table. Json looks like this:  {"reading":[10, 87, 325, 46]}.

Is there any way to parse the data so that each table column has the value inserted relative to its position in the array? i.e., In this example, the value '10' is inserted into column 1, value '87' is inserted into column 2, etc.

**Comment by jpmens** [comment]
That is not possible.
