### ISSUE TITLE
Unable to decode json with null terminating char

### ISSUE THREAD

**Issue by rweller59** [jpmens/mqttwarn#272]
I don't have control over the incoming json message. Messages received are null terminated. Is there any way to manage this? All messages received error with Cannot Decode JSON object, extra data at end of message

**Comment by jpmens** [comment]
null-terminated JSON isn't JSON. You'll have to modify mqttwarn.py to strip those nulls from the incoming payload. It's easy to do.

Have you asked yourself *why* your data is null-terminated?

**Comment by rweller59** [comment]
Unfortunately I do not have control over the sending device code. I'm using a couple of other mqtt apps apps that handle json messages with and without a null terminator so apparently they are ignoring any characters received after the closed bracket. I was hoping there was a configuration switch I could set since I've never worked with python. But, guess not so I'll try to figure out mqttwarn.py

**Comment by jpmens** [comment]
@rweller59 I have pushed an update which strips nul from end of strings. Please note this is *tentative*: if people complain it breaks things for them, I'll have to revert.

**Comment by rweller59** [comment]
thanks for providing the code - would have taken me awhile I imagine. The 'cannot decode' error is now gone but I've got another error that replaced it. Without the change, I got the 'cannot decode' error but the message was put into the 'full' column field without data being parsed into columns. With the line of code to strip, nothing is logged to sql and I get the following error...

WARNING [mysql] Cannot add mysql row: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'1, test, full) values (46.6, 70.5, \'{\\"test\\":70.5,\\"1\\":46.6}\')\' at line 1')

The JSON received is {"test":70.5,"1":46.6}

I'm using MySql with a single table that is pretty simple. Columns test, 1, full
If I should open a separate issue I will. Or if you can give me some hints on where to look for what's going on that would be great.

Everything worked a couple of weeks ago with a different device sending the mqtt data

**Comment by rweller59** [comment]
Got everything working. The terminating null character gets stripped and things now logging to DB. Did discover an issue with mysql column headings causing an error - headings with names equal to numbers (e.g. 1,2,etc) don't work. MySQL doesn't seem to have a problem with them but the sql statements used in mysql.py seem to.
