### ISSUE TITLE
mqtt to http  ( from owntracks to traccar)

### ISSUE THREAD

**Issue by scube38** [jpmens/mqttwarn#274]
Hello, 
Finally asking for some help to setup http service to bridge owntracks to traccar , started from mqttwarn.ini example and trying to add basic http service

````
[config:http]
timeout = 4
targets = {
   'post1'    : [ "post", "http://192.168.1.36:5140", None, True ],
  }

[owntracks-traccar]
topic = owntracks/+/+
targets = log:info, http:post1
```

message is correctly received and processed in section [owntracks-traccar] but mqttwarn entering infinite reconnect state. 

```
2017-11-29 01:27:45,418 DEBUG [mqttwarn] New `http:post1' job: owntracks/xx/xx
2017-11-29 01:27:45,419 WARNING [mqttwarn] MQTT server disconnected, trying to reconnect each 5 seconds
2017-11-29 01:27:50,425 WARNING [mqttwarn] MQTT server disconnected, trying to reconnect each 5 seconds
2017-11-29 01:27:55,431 WARNING [mqttwarn] MQTT server disconnected, trying to reconnect each 5 seconds
```

I know current http service post1 is not realizing the expected fonction but current struggling to understand current issue with this MQTT disconnection,    changing  timeout of http request does not help

**Comment by jpmens** [comment]
Why don't you use Traccar's owntracks input to save pain?

**Comment by scube38** [comment]
This is my current testing setup in place and working as a charm  ( Thanks for your great jobs ) . But direct owntrack to traccar is loosing some feature like friends, and local mysql recording in my local mqtt network.
Limitation will disapear if mqtt to traccar bridge done via the ( excelent ) mqttwarn

**Comment by jpmens** [comment]
Please try to determine whether mqttwarn really is being disconnected from your broker (check its logs).

**Comment by jpmens** [comment]
Closed due to inactivity
