### ISSUE TITLE
transform using a nested json value

### ISSUE THREAD

**Issue by kkplein** [jpmens/mqttwarn#275]
This question is very basic, but part of my payload looks like this:

>     "inverterType": 3, 
>     "isDTSeries": false, 
>     "isOnline": true, 
>     "lastSeen": 1512028792882, 
>     "runningInfo": {
>         "eDay": 0.0, 
>         "eTotal": 10970.1, 
>         "errorMessage": [], 
>         "fac1": 50.03, 
>         "fac2": 50.02, 
>         "fac3": 50.02, 
>         "function": 129, 
>         "gcfiFault": 32, 
>         "hTotal": 4953, 
>         "iac1": 0.6, 
>         "iac2": 0.9, 
>         "iac3": 1.1, 
>         "ipv1": 0.6, 
>         "ipv2": 0.5, 
>         "line1FFault": 62.85, 
>         "line1VFault": 0.0, 
>         "line2FFault": 31.22, 
>         "line2VFault": 0.0, 
>         "line3FFault": 0.0, 
>         "line3VFault": 0.0, 
>         "pac": 80, 
>         "pv1Fault": 0.0, 
>         "pv2Fault": 0.0, 
>         "temp": 28.2, 
>         "tempFault": 121.2, 
>         "timestamp": "20171130075952", 
>         "vac1": 234.1, 
>         "vac2": 237.4, 
>         "vac3": 235.5, 
>         "vpv1": 275.1, 
>         "vpv2": 544.3, 
>         "workMode": 1
>     }, 
> 

...

I can use the 'first level' values in a transform (lastSeen, isOnline, etc) but I also would like to use the 'subvalues' values values from runningInfo, and I am not sure how to 'address' those... Tried runningInfo/vac2 but (of course...) that doesn't work.
Could anyone tell me how to use the value of vac2 in a transform?
Thanks!

**Comment by kkplein** [comment]
After doing more research I know now that what I'm looking for is to access a nested json array. In python like this:
`print j['runningInfo'][1]['vac1']`
Question remains: how can I use this in a mqttwarn transform operation?

**Comment by jpmens** [comment]
I think you'll have to use a custom Python function for that. See the README for how that works.

**Comment by kkplein** [comment]
Hi Jan Piet,
bedankt voor je antwoord.

**Comment by rgitzel** [comment]
In case anyone else finds this and wonders how the "custom Python function" works, I think I have it figured out.  The key is to provide an `alldata` function, which seems to be the only way to _change_ a payload.

For example, my goal right now is to convert messages from two different temperature sensors running [Tasmota](https://github.com/arendst/Sonoff-Tasmota/) into [InfluxDB line format](https://docs.influxdata.com/influxdb/v1.6/write_protocols/line_protocol_tutorial/).

The JSON will look like [this](https://github.com/arendst/Sonoff-Tasmota/wiki/JSON-Status-Responses#dht11) or [this](https://github.com/arendst/Sonoff-Tasmota/wiki/JSON-Status-Responses#ds18b20).

Here's the code (I'm _not_ a Python developer):
```
import ast
import time
from datetime import datetime

def tasmota_values(topic, payload):
    ts = datetime.strptime(payload["Time"], "%Y.%m.%d %H:%M:%S")
    millis = long(time.mktime(ts.timetuple()) * 1000)
    return dict( Topic = topic, Timestamp = millis )

def dht11_values(topic, data, srv=None):
    payload = ast.literal_eval(data["payload"])
    d = tasmota_values(topic, payload)
    d.update(Temperature = payload["DHT11"]["Temperature"])
    d.update(Humidity = payload["DHT11"]["Humidity"])
    return d

def ds18b20_values(topic, data, srv=None):
    payload = ast.literal_eval(data["payload"])
    d = tasmota_values(topic, payload)
    d.update(Temperature = payload["DS18B20"]["Temperature"])
    return d

```

And the topics in `mqttwarn.ini`:
```
[tasmota/temp/dht/+]
targets = log:info
alldata = dht11_values()
format  = mqttwarn,Topic={Topic} Temperature={Temperature},Humidity={Humidity} {Timestamp}

[tasmota/temp/ds/+]
targets = log:info
alldata = ds18b20_values()
format  = mqttwarn,Topic={Topic} Temperature={Temperature} {Timestamp}
```

**Comment by jpmens** [comment]
Why comment on an old issue? If you think the documentation can be improved upon, and documentation can always be improved upon, we'd appreciate your time and effort to contribute to it. Feel free to propose a pull-request which explains this more in depth.

**Comment by rgitzel** [comment]
This is the only page I found _anywhere_ that even hinted at a solution to what I was doing, so I wanted to leave more information for the next person who arrived here.

I wanted to get it down while it was still fresh, and I didn't have much time yesterday. Better here than not at all?

I might have some time today, will look at moving the bulk of the comment to the documentation.
