### ISSUE TITLE
Supervisor will not run MQTTWarn 

### ISSUE THREAD

**Issue by semaf** [jpmens/mqttwarn#279]
Supervisor wont let me start mqttwarn.

```
[program:mqttwarn]
directory = /home/pi/services/mqttwarn
command = /home/pi/services/mqttwarn/mqttwarn.py
user = pi
environment= MQTTWARNINI="/home/pi/services/mqttwarn/mqttwarn.ini"
```

> 2017-12-25 02:27:13,724 INFO spawned: 'mqttwarn' with pid 17432
> 2017-12-25 02:27:14,104 INFO exited: mqttwarn (exit status 1; not expected)
> 2017-12-25 02:27:15,112 INFO spawned: 'mqttwarn' with pid 17437
> 2017-12-25 02:27:15,481 INFO exited: mqttwarn (exit status 1; not expected)
> 2017-12-25 02:27:17,686 INFO spawned: 'mqttwarn' with pid 17442
> 2017-12-25 02:27:18,081 INFO exited: mqttwarn (exit status 1; not expected)
> 2017-12-25 02:27:21,367 INFO spawned: 'mqttwarn' with pid 17448
> 2017-12-25 02:27:21,732 INFO exited: mqttwarn (exit status 1; not expected)
> 2017-12-25 02:27:22,734 INFO gave up: mqttwarn entered FATAL state, too many start retries too quickly
> backoff - Exited too quickly (process log may have details)

**Comment by amotl** [comment]
Hi there,

can you try to start mqttwarn manually or add the directive `loglevel = debug` to the supervisor configuration and see what this tells you? See also http://supervisord.org/logging.html.

Thanks,
Andreas.

**Comment by semaf** [comment]
I figure it out by adding to the command line sudo python

**Comment by amotl** [comment]
All right, so it was a permission issue? Probably mqttwarn.py was not able to read its configuration file? However, i think you can close this, @jpmens. Happy you figured this out, @semaf.

**Comment by jpmens** [comment]
@semaf prefixing command lines with `sudo` is not a good idea unless you know exactly what a program is doing. Mqttwarn doesn't require superuser rights so I assume you have, as @amotl says, a permission problem somewhere else. It would be worth your while to find that.

Closing as this is not an mqttwarn issue.
