### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3

### ISSUE THREAD

**Issue by semaf** [jpmens/mqttwarn#280]
I have used in my Text "Wohnungstür" and it seems that the "ü" is a problem.

```
Traceback (most recent call last):
  File "mqttwarn.py", line 1122, in <module>
    connect()
  File "mqttwarn.py", line 1062, in connect
    mqttc.loop_forever()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1481, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1003, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1284, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1849, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2305, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2500, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2647, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "mqttwarn.py", line 609, in on_message
    logging.debug("Message received on %s: %s" % (topic, payload))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
```

**Comment by amotl** [comment]
Bummer! We will probably have to get better regarding Unicode awareness.

I just gave this a quick try by doing
`echo '{"name": "Wohnungstür", "number": 42}' | mosquitto_pub -h localhost -t hello/1 -l`

while running `mqttwarn.py` using the `mqttwarn.ini.sample` and it properly said
`2017-12-25 14:12:32,551 DEBUG [mqttwarn] Message received on hello/1: {"name": "Wohnungstür", "number": 42}`.

Can you tell us what you did exactly to be able to reproduce this? Please also tell us which _Python_ and _paho-mqtt_ versions you are using and whether you use _Mosquitto_ or any other MQTT broker. Thanks!

**Comment by semaf** [comment]
Well reproducing it, is a little bit complicated. I am using OpenHAB which post the message `VT_Notify_Alarm.postUpdate("Wohnungstür Licht EIN")` to mosquitto  at `/openhab/notification/`

My mqttwarn.ini:
```
[config:slack]
token = 'xoxb-1234567890-XXXXXXXXXXXXXX'
targets = {
	#  #channel/@user   username, icon
	'mqtt-client'  : [ '@semaf', 'openhab',   ':slack:']}

[/openhab/notification/]
targets = file:mylog, log:info

[#]
targets = slack:mqtt-client 
```
And if mqttwarn get the message, supervisor can not restart mqttwarn and its down. Trying to start manually I am getting the error like above.

Log of OpenHAB:

> VT_Notify_Alarm changed from Wohnungstür Licht EIN to Wohnungstür Licht AUS

Python 2.7
Mosquitto:
1514209026: mosquitto version 1.3.4 (build date 2017-05-29 22:25:09+0000)

**Comment by amotl** [comment]
Thanks, we will have to investigate further. Currently, this does not harm anything when trying to simulate the scenario on my machine:

`echo 'Wohnungstür Licht EIN' | mosquitto_pub -h localhost -t hello/1 -l`
gives
`2017-12-25 15:02:17,697 DEBUG [mqttwarn] Message received on hello/1: Wohnungstür Licht EIN`
without any error.

FYI:
- `import paho.mqtt; print(paho.mqtt.__version__)`
  `1.1`
- Mac OS X 10.7.5 (very old, i know); Python 2.7.13; mosquitto version 1.4.8

**Comment by amotl** [comment]
Update: I do recognize the most recent version of the Eclipse Paho MQTT Python client library is actually "paho-mqtt 1.3.1" and also that there is #276, which might be related to this issue. I will get back to this later!

**Comment by amotl** [comment]
... i can confirm your problem after upgrading to "paho-mqtt 1.3.1" and "mqttwarn HEAD" using the simple `echo | mosquitto_pub` command mentioned above. Thanks again, we will have a look under the hood later.

**Comment by amotl** [comment]
Hello again,

until this gets merged, you might want to incorporate these changes manually in order to continue your experiments.

With kind regards,
Andreas.

**Comment by jpmens** [comment]
Fixed in https://github.com/jpmens/mqttwarn/pull/281
