### ISSUE TITLE
how to setup mysql plugin in mqttwarn

### ISSUE THREAD

**Issue by sruthi1985** [jpmens/mqttwarn#283]
we need to create a tables in mysql using mqttwarn. how we have to setup mysql plugin 
[config:mysql]
host  =  'localhost'
port  =  3306
user  =  'jane'
pass  =  'secret'
dbname  =  'test'
targets = {
          # tablename  #fallbackcolumn ('NOP' to disable)
 'm2'   : [ 'names',   'full'            ]
  }
can anyone explain  me that?

**Comment by jpmens** [comment]
You _might_ be able to create a table via a plugin function you write, but I think that'll be a bit messy. Other than that, there's no provision for doing that: the mysql service needs the table when it's used.
