### ISSUE TITLE
Pushover now supports image attachments - would be grand to add this to mqttwarn

### ISSUE THREAD

**Issue by sumnerboy12** [jpmens/mqttwarn#284]
https://updates.pushover.net/post/170043375237/pushing-images-with-pushover-30

**Comment by jpmens** [comment]
Make it happen, Ben! :-)

**Comment by amotl** [comment]
Dear Ben and Jan-Piet,

we just created the basic [mqttshot] program for publishing messages containing text and a single image to the MQTT bus. It currently has these properties:

- Use base64 for encoding the image, it feels safer than binary and can be used to encapsulate the image into a message container.
- Use JSON as message container format, as one usually might want to send other data along.
- The image acquisition from different sources is already quite flexible, you can choose from File, URL and STDIN.

Please consider this as a proposal about a convention of _how to_ send basic messages containing images over MQTT. We will be happy if this can help anyone tackling the proposed implementation for mqttwarn/pushover.

Cheers,
Andreas.

[mqttshot]: https://github.com/daq-tools/mqttshot

**Comment by jpmens** [comment]
That looks very good, Andreas. I think for _mqttwarn_ we'd need to be able to configure the JSON element containing the image data, but otherwise that's a fine job. FWIW, I fully agree with not sending binary images: base64-encoding fits the bill perfectly.

**Comment by powermik** [comment]
I use a similar approach for images over mqtt but prepend the base64 string with a datauri:
data:image/png;base64,000000000000...
so i can display the picture in a browser just using mqtt over websocket.

Please add at least a field with filetype for that use case

**Comment by psyciknz** [comment]
I think I have updated the pushover to support this.  Works with json payloads, it can accept either an imageurl parameter which it will download the image and include it, or a base64 encoded image.

My development machine (with github) is out of action today, but I'll try to add the code in the next day or two.

regarding @amotl above, I use "image" as the binary base64 image, and "imageurl" for an image to be downloaded, as it looks like they use the same tag.

**Comment by jpmens** [comment]
The PR for this is being addressed in https://github.com/jpmens/mqttwarn/pull/304

**Comment by sumnerboy12** [comment]
Implemented via #304
