### ISSUE TITLE
funcs.py - loading config items?

### ISSUE THREAD

**Issue by psyciknz** [jpmens/mqttwarn#285]
I've got a service which allows the sending of sms messages via the android app rest sms gateway (https://play.google.com/store/apps/details?id=com.perfness.smsgateway.rest&hl=en - I can publih the service if someone wishes.

Inside the mqttwarn.ini I've got the host and port set, and the service is reading that.
As part of the app, there's a way of reading teh inbox and outbox for messages. To do this, I'm thinking something like the call to def publish_public_ip_address(srv=None): in the sample_funcs.py which goes out and gets a status periodically.

But there doesn't seem to be an example of getting settings into the function file from the ini file (in my case it's that host and port again).

Any guidance?

**Comment by jpmens** [comment]
No, we don’t have that. I’d take a PR for it probably.
Until then I’d recommend you use environment variables (`MY_HOST=`) to pass your config values into the functions.

**Comment by psyciknz** [comment]
Actually...it is possible.  This code segment works in a function:
```
try:
        fullconfig = srv.mwcore['cf']
        config = fullconfig.config('config:' + "asterisk")
        host = config['host']
        port = config['port']
        user = config['username']
        password = config['password']
    except Exception, e:
        srv.logging.error("Error: %s" % str(e))
```

For a config section of `[config:asterisk]' in the mqttwarn.ini file.  So it is possible to re-use configuration options.
