### ISSUE TITLE
Retained topic state - reading from the funcs.py?

### ISSUE THREAD

**Issue by psyciknz** [jpmens/mqttwarn#286]
I'm still in the funcs.py....and have a list of messages to parse.
I've managed to figure out the highest one based on an id, and post that to a topic.

Inside the funcs.py, can I query that topic, so before I read the messages i get get the highest id, and only deal with messages with an higher id?

**Comment by jpmens** [comment]
That is not possible. You’d probably have to use some sort of store into which you put messages and then do whatever with them. I think that’s beyond the sope of mqttwarn.
