### ISSUE TITLE
want some examples of service execute  and pipe 

### ISSUE THREAD

**Issue by 12019** [jpmens/mqttwarn#293]
this is a great program. we like it so much.  what I am trying to do is 
when receive mqtt messages, I need put some data which in json messages into argument of bash a script.

can you share some insight on this?

; name the service providers you will be using.
launch   = pushover, execute

[config:execute]
targets = {
    'json'  : [ 'touch', '/tmp/{roomname}'],
    }

but in /tmp directory I got this.

-rw-r--r-- 1 root root   0 Mar  3 23:31 {phonenum}
-rw-r--r-- 1 root root   0 Mar  3 23:58 {roomname}

**Comment by jpmens** [comment]
You are trying to use JSON expansion during the configuration phase. That is not possible.

I believe the documentation is quite clear:

> To pass the published data (text) to the command, use `[TEXT]` which then gets replaced

Should it not be, please say how we can improve on that.
