### ISSUE TITLE
XMPP plugin fails

### ISSUE THREAD

**Issue by hagenbauer** [jpmens/mqttwarn#295]
I am trying to setup a simple xmpp example

 `[config:xmpp]`
 `sender ='someuser@caserio.de'`
 `password = 'correctpassword' `
 `targets = {  'admin' : 'hagen.bauer@caserio.de'   } `
 `[hello/1] `
 `targets = log:info, xmpp:admin `

This is the error I can see
`DEBUG [xmpp] *** MODULE=services/xmpp.py: service=xmpp, target=admin `
 `DEBUG [xmpp] Sending XMPP notification to admin, addresses: hagen.bauer@caserio.de `
 `WARNING [mqttwarn] Notification of xmpp for hello/1 FAILED or TIMED OUT `
  `DEBUG [mqttwarn] Job queue has 0 items to process `
 `ERROR [xmpp] Error sending message to admin: Client instance has no attribute 'Dispatcher'`

DNS should be ok. 

`host -t SRV _xmpp-client._tcp.caserio.de `
 `_xmpp-client._tcp.caserio.de has SRV record 5 0 5222 chat.caserio.de. `
`
Other  xmpp Clients are working.  Anything I am doing wrong?

**Comment by jpmens** [comment]
That appears to be a problem in the upstream XMPP package. This service requires `http://xmpppy.sourceforge.net` so you'll have to dig around that code for the error message please.

(BTW: here on github it's best to format code between two lines consisting of three backticks each.)

**Comment by jpmens** [comment]
@fabaff I note you contributed this service to _mqttwarn_. Any idea what's going on?

**Comment by jpmens** [comment]
@hagenbauer have you been successful?

**Comment by hagenbauer** [comment]
@jpmens unfortunately no. My python knowhow is not good enough for this type of investigations

**Comment by amotl** [comment]
I can remember we selected the wrong "xmpp" package at the first hand when giving the XMPP transport a shot. We finally succeeded with

    pip install 'xmpppy==0.5.0rc1'

Hope this helps.

**Comment by jpmens** [comment]
@hagenbauer could you please test what @amotl suggests and report back please? If you report success, I would amend our documentation accordingly.

**Comment by hagenbauer** [comment]
yes. I will try tomorrow or Monday

**Comment by hagenbauer** [comment]
still no luck.  The only "enhancement" is the there is no "dispatcher" error message any longer. 
```
2018-04-23 08:21:37,476 DEBUG [mqttwarn] New `xmpp:admin' job: hello/1
2018-04-23 08:21:37,478 DEBUG [log] *** MODULE=services/log.pyc: service=log, target=info
2018-04-23 08:21:37,478 INFO  [log] Hello
2018-04-23 08:21:37,479 DEBUG [mqttwarn] Job queue has 1 items to process
2018-04-23 08:21:37,479 DEBUG [mqttwarn] Processor #0 is handling: `xmpp' for admin
2018-04-23 08:21:37,483 DEBUG [xmpp] *** MODULE=services/xmpp.pyc: service=xmpp, target=admin
2018-04-23 08:21:37,484 DEBUG [xmpp] Sending XMPP notification to admin, addresses: hagen.bauer@caserio.de
2018-04-23 08:21:47,484 WARNING [mqttwarn] Notification of xmpp for `hello/1' FAILED or TIMED OUT
2018-04-23 08:21:47,484 DEBUG [mqttwarn] Job queue has 0 items to process
2018-04-23 08:23:44,704 ERROR [xmpp] Error sending message to admin: Client instance has no attribute 'Dispatcher'


```

**Comment by amotl** [comment]
Dear @hagenbauer,

i can remember @einsiedlerkrebs and me also having problems when starting with the pyxmpp whatnot library. We will have a look at our setup, maybe we can find what made it work for us again, so please stay tuned.

With kind regards,
Andreas.

**Comment by jpmens** [comment]
Closing as stale.

**Comment by amotl** [comment]
I know that we also had issues with the xmpp service. So, I would like to reopen this to keep it as a reference.

**Comment by clarkspark** [comment]
I've been trying to switch from the github version of mqttwarn to the pypi version and was not able to get mqttwarn to run outside of a virtual enviroment (trying with both pip and pip3).  Is this expected, or should I open an issue with details ?

I am running into the same issue 'dispatcher' issue when installing from pypi in a virtual enviroment.  I changed a line in service/xmpp.py to:
connection = xmpp.Client(jid.getDomain()) #,debug=[])
and I saw this message:
DEBUG: Debug created for /home/admin1/mqtt/.venv2/local/lib/python2.7/site-packages/xmpp/client.py
DEBUG:  flags defined: always,nodebuilder
DEBUG: socket       start Plugging <xmpp.transports.TCPsocket instance at 0x7f712c9c61e0> into <xmpp.client.Client instance at 0x7f712c9c6140>
DEBUG: socket       warn  Could not load one of the supported DNS libraries (dnspython or pydns). SRV records will not be queried and you may need to set custom hostname/port for some servers to be accessible.\n
DEBUG: socket       error Failed to connect to remote host ('example.com', 5222): Connection refused (111)

As I do use SRV records for XMPP this made sense.  I installed pydns and then I got a message that looks like it had already been fixed:
Error sending message to aqua: '_ssl._SSLSocket' object has no attribute 'issuer'

I could keep trying to troubleshoot if more information is needed.

Thanks

**Comment by clarkspark** [comment]
installing this version of xmpppy:
pip install https://github.com/ArchipelProject/xmpppy/archive/master.zip

as per: 
https://stackoverflow.com/questions/37017181/gcm-notifications-with-python-xmpp

does resolve my issue with the mqttwarn xmpp service.

**Comment by amotl** [comment]
Dear @clarkspark,

thank you so much for revisiting this issue and for sharing your outcome!

I would like to take the opportunity to solve this sustainably for the mqttwarn community. So, I've investigated the [network of forks of xmpppy](https://github.com/normanr/xmpppy/network) and found that @lilmike has the fork with the most recent commits [1]: Latest commit https://github.com/lilmike/xmpppy/commit/a81dafee5f4824e695cb0a0cd6017c7d15971272 on Sep 23, 2019.

So, I am humbly asking you to check if installing this module will also work flawlessly. If this is true, I would deliberately go forward to publish this module to PyPI as `xmpppy2` in order to improve the installation experience for all others. From what I can see, this version will support Python3 already which might not be the case for the fork by @ArchipelProject with the most recent commits by @CyrilPeponnet.

If it doesn't work out of the box, we might want to cherry-pick appropriate patches from other forks in order to come to a contemporary version which works flawlessly on Python3.

We also might ask/inform the original author [Alexey Nezhdanov](snakeru@users.sourceforge.net) first, otherwise let's just proceed on this.

Thanks already and with kind regards,
Andreas.

[1] https://github.com/lilmike/xmpppy

**Comment by snakeru** [comment]
Hi.

I would only welcome if someone uploads/publishes a new version of
python-xmpp library or even takes over the maintenance. The last maintainer
was Normann Rasmussen, but I am not sure if he is still doing that.

Best regards,
Alexey Nezhdanov

Am Do., 20. Feb. 2020 um 20:53 Uhr schrieb Andreas Motl <
notifications@github.com>:

**Comment by snakeru** [comment]
+Norman Rasmussen <normanr@gmail.com>

Am Do., 20. Feb. 2020 um 21:00 Uhr schrieb Alexey Nezhdanov <
snakeru@gmail.com>:

**Comment by amotl** [comment]
Dear @snakeru,

thanks for your quick answer. According to [1], @normanr's latest commits have been around 2015 already. While I can't promise to be able to bring in sustained maintenance, I would try to put in some efforts to reintegrate some cherries from the community and release a version on PyPI.

With kind regards,
Andreas.

[1] https://github.com/normanr/xmpppy/commits/master

**Comment by clarkspark** [comment]
Dear @amotl,
    I tried to verify that https://github.com/lilmike/xmpppy works but I'm not sure how to do so.  I followed the various instructions in its README.md but I'm getting an error on the
```
import xmpp
ImportError: No module named xmpp
```
I'm not sure how to modify the import to get mqttwarn to use the downloaded github library.

Thanks,
    Ryan

**Comment by amotl** [comment]
Dear Ryan,

I just did the same within a Python virtualenv you have been doing to install the other fork:
```
pip install https://github.com/lilmike/xmpppy/archive/master.zip
python
>>> import xmpp
```

Cheers,
Andreas.

**Comment by clarkspark** [comment]
Andreas,
I had been using a python 2 venv:
```
virtualenv --python=python2 .venv2
```
and was able to install (from pip) and use pydns to get XMPP to work.  

But with the python3 venv I can't install pydns from pip:
```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wtwtb_kp/pydns/setup.py", line 12, in <module>
        import DNS
      File "/tmp/pip-install-wtwtb_kp/pydns/DNS/__init__.py", line 14, in <module>
        import Type,Opcode,Status,Class
    ModuleNotFoundError: No module named 'Type'
```

So I tried installing the dnspython package (also from pip) and the debug of the xmpp package on failure is:
```
  DEBUG: socket       error Socket error while sending data
Traceback (most recent call last):
  File "/home/admin1/mqttwarn/.venv3/lib/python3.7/site-packages/xmpp/transports.py", line 244, in send
    self.DEBUG(raw_data,'sent')
  File "/home/admin1/mqttwarn/.venv3/lib/python3.7/site-packages/xmpp/client.py", line 88, in DEBUG
    self._owner.DEBUG(self.DBG_LINE,text,severity)
  File "/home/admin1/mqttwarn/.venv3/lib/python3.7/site-packages/xmpp/debug.py", line 399, in Show
    msg=msg.replace('\r','\\r').replace('\n','\\n').replace('><','>\n  <')
TypeError: a bytes-like object is required, not 'str'
DEBUG: client       stop  Disconnect detected
DEBUG: socket       error Socket operation failed
```

So in summary it seems like pydns in a python2 virtual environment works.  But I can't verify any alternate XMPP library in a python3 virtual environment as the pydns package doesn't install and the alternate dnspython package seems to have an issue.

Just trying to help, let me know if this can wait until the xmpppy2 package is further along.

Thanks,
Ryan

**Comment by normanr** [comment]
see https://github.com/normanr/xmpppy/issues/16 for updates on project "maintenance", effectively I don't have any time and would love someone else to help maintain the project.

**Comment by normanr** [comment]
I got this reply from github support:

> xmpppy/xmpppy, doesn't have any issues or PRs, and no forks of its own, so the smoothest option would be to delete it. Then you could transfer normanr/xmpppy across to the xmpppy org, and it would take all of its issues, PRs and forks with it.

So I'm going to try that.

**Comment by snakeru** [comment]
The repo was transferred. Thanks, Norman!

Andreas, I just invited you to be a maintainer on the project.

Best regards,
Alexey Nezhdanov

Am Fr., 21. Feb. 2020 um 02:49 Uhr schrieb Norman Rasmussen <
notifications@github.com>:

**Comment by amotl** [comment]
Dear @snakeru,

thanks a bunch. I will see what I can do there. In order to push new releases to PyPI, will you also add me as a maintainer to [1]?

With kind regards,
Andreas.

[1] https://pypi.org/project/xmpppy/

**Comment by snakeru** [comment]
Sure.

I just did that - could you please verify that it worked?

Best,
Alexey.

Am Fr., 21. Feb. 2020 um 10:18 Uhr schrieb Andreas Motl <
notifications@github.com>:

**Comment by amotl** [comment]
Hi @snakeru,

I've received an email from PyPI saying

> You have been added as Maintainer to the PyPI project xmpppy by snakeru.

So, I am assuming it worked. Thanks!

With kind regards,
Andreas.

**Comment by normanr** [comment]
I've also invited amotl to the xmpppy org on github.com.

**Comment by clarkspark** [comment]
Andreas (@amotl),
    To try to get the xmpp service re-working in XMPP I would:
1. Fork the repo you cited here [1].
2. Create a new branch.
3. Cherry pick your cited commits in [1] (or others).
4. Verify stability.
5. Report further issues to [1] or submit a pull request to [1]?

Is there ever an issue with licensing which covers a particular commit?

Thanks for the info,
    Ryan

[1] https://github.com/zerotired/xmpppy/issues/1

**Comment by amotl** [comment]
Dear Ryan,

thanks for following up on this. Thanks for your offer, I will appreciate your contributions. As I received permissions for the canonical repositories [1,2] from @normanr and @snakeru, I will be happy to accept your pull requests directly on [1] and will push out releases to [2] after some dust might have settled.

With kind regards,
Andreas.

[1] https://github.com/xmpppy/xmpppy
[2] https://pypi.org/project/xmpppy/

**Comment by amotl** [comment]
We have been able to revamp the `xmpppy` library and just released version 0.6.0 on PyPI. It has critical bugfixes and humble support for Python3. @clarkspark is currently testing it - thanks already!

**Comment by amotl** [comment]
@clarkspark reported

> The xmpppy 0.6.0 in pypi is not stable in python2 though.
```
DEBUG: socket       sent  <message to="example@example.com" id="15">
  <body>Script 'aqua_therm_avg_aq75g-1' has not received a parameter from topic 'dims/sensor/inventory/TMP-2/all' or 'dims/sensor/inventory/TMP-5/all' in 180 seconds, exiting...</body>
  </message>
Invalid debugflag given: always
Invalid debugflag given: nodebuilder
DEBUG: 
DEBUG: Debug created for /srv/mqttwarn/.venv2/local/lib/python2.7/site-packages/xmpp/client.py
DEBUG:  flags defined: always,nodebuilder
DEBUG: socket       start Plugging <xmpp.transports.TCPsocket instance at 0x7fb5cb573960> into <xmpp.client.Client instance at 0x7fb5cb5738c0>
Invalid debugflag given: always
Invalid debugflag given: nodebuilder
DEBUG: 
DEBUG: Debug created for /srv/mqttwarn/.venv2/local/lib/python2.7/site-packages/xmpp/client.py
DEBUG:  flags defined: always,nodebuilder
DEBUG: socket       start Plugging <xmpp.transports.TCPsocket instance at 0x7fb5cbdcc820> into <xmpp.client.Client instance at 0x7fb5cbdccb40>
DEBUG: socket       warn  An error occurred while looking up _xmpp-client._tcp.example.com
DEBUG: socket       error Failed to connect to remote host (u'example.com', 5222): Network is unreachable (101)
Traceback (most recent call last):
  File "/srv/mqttwarn/.venv2/local/lib/python2.7/site-packages/xmpp/transports.py", line 159, in connect
    self._sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 101] Network is unreachable
DEBUG: socket       stop  Plugging <xmpp.transports.TCPsocket instance at 0x7fb5cb573960> out of <xmpp.client.Client instance at 0x7fb5cb5738c0>.
```

**Comment by amotl** [comment]
Dear Ryan,

thanks for reporting back.

### 1. Just a warning
Probably not relevant, as these might be warnings only. However, is the behavior new to you?
```
Invalid debugflag given: always
Invalid debugflag given: nodebuilder
```
vs.
```
DEBUG:  flags defined: always,nodebuilder
```

### 2. The real error
```
DEBUG: socket       error Failed to connect to remote host (u'example.com', 5222): Network is unreachable (101)
Traceback (most recent call last):
  File "/srv/mqttwarn/.venv2/local/lib/python2.7/site-packages/xmpp/transports.py", line 159, in connect
    self._sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 101] Network is unreachable
```

This is probably because you are trying to connect to `example.com` here and `xmpppy` just tells the truth about it?

With kind regards,
Andreas.

**Comment by clarkspark** [comment]
@amotl,
    I was opening the issue at [xmpppy](https://github.com/xmpppy/xmpppy/issues) but you beat me to it here.  The issue happens after multiple successful messages being sent, sometimes a few sometimes maybe 5-10.  Then it throws the Errno 101.  I just gave a few lines before the error for context.

**Comment by clarkspark** [comment]
Andreas,
    Since it seems to die on the SRV DNS record lookup it could potentially be an issue with the related pydns pypi package which is required by xmpppy in cases where the server uses a SRV record.  I could try to enable debug in that package and see if it reveals anything.

    I wanted to take up less of your time and I seem to be taking up more.  How about I look further and post an update.  But if there is interest for implementing "Apprise" maybe that would be the way to go.

Thanks,
    Ryan

**Comment by amotl** [comment]
> `warn  An error occurred while looking up _xmpp-client._tcp.example.com`
>
> Since it seems to die on the SRV DNS record lookup [...]

Now I am seeing it, thanks! Maybe you should try `dnspython` instead of `pydns`? The most recent update time of `dnspython` is 2018, while `pydns` feels pretty dated with the most recent update being 2012.

> I could try to enable debug in that package and see if it reveals anything.

Thanks!

> But if there is interest for implementing 'Apprise' maybe that would be the way to go.

https://github.com/jpmens/mqttwarn/issues/400 is a first attempt to that. The most recent mqttwarn 0.14.0 includes this plugin already. However, I've experienced problems with its XMPP plugin which is based on [sleekxmpp](https://pypi.org/project/sleekxmpp/), see also https://github.com/caronc/apprise/issues/213.

**Comment by amotl** [comment]
> I was opening the issue at [xmpppy](https://github.com/xmpppy/xmpppy/issues) but you beat me to it here.

We might really create an issue there for the sake of completeness and finally close this one, as the issue of the original poster should have been resolved through xmpppy 0.6.0 already.

**Comment by clarkspark** [comment]
Andreas,
    I plan to open an issue at [xmpppy](https://github.com/xmpppy/xmpppy/issues) in the next day or two.

Thanks,
Ryan

**Comment by amotl** [comment]
Dear Ryan,

I've diverted the issue about "[Errno 101] Network is unreachable" to #403 and will deliberately close this issue. Please feel free to reopen when appropriate.

With kind regards,
Andreas.

**Comment by Neustradamus** [comment]
@amotl: I am very happy to see that xmpppy is developped a new time!
Please look all changes in all current forks!
