### ISSUE TITLE
Announce: additional committer for mqttwarn

### ISSUE THREAD

**Issue by jpmens** [jpmens/mqttwarn#298]
I have the pleasure to announce that Andreas Motl (@amotl) has, with this message, become a full committer to the _mqttwarn_ project.

Andreas has in the past provided us with high-quality patches, and he probably meanwhile understands _mqttwarn_'s innards better than I do.

Andreas is going to begin on the gargantuan task of converting _mqttwarn_ to a Pypi project (#127) in order that we can then all benefit from a simple `pip install mqttwarn`, and he's also found a solution for being able to install _mqttwarn_ services just as easily with all their dependencies!

I'm very glad to have him aboard and look greatly forward to his further contributions.

**Comment by amotl** [comment]
Dear JP,

thanks a bunch for your warm welcome. We will try our best to finally make _mqttwarn_ a native citizen on PyPI and (hopefully) improve some other minor details along the lines. While working on that, we will always be happy to receive supportive feedback from the community.

Looking forward to mqttwarn 1.0! ⁴²

Cheers,
Andreas.

⁴² ... aber immer langsam mit den jungen Pferden ;]

**Comment by sumnerboy12** [comment]
Welcome @amotl - great to have on board!
