### ISSUE TITLE
examples/hiveeyes did not work as expected.

### ISSUE THREAD

**Issue by 12019** [jpmens/mqttwarn#301]
hit several problems run the hiveeyes example.
1. need changed hiveeyes.ini  to the following.

; path to file containing self-defined functions
; for hiveeyes-schwarmalarm machinery
functions = './examples/hiveeyes/hiveeyes.py'

2. seems global value of hdata can not accessed by function hiveeyes_more_data()  always has empty value.
when print the hdata value like the following,

  located in hiveeyes_more_data()
('got hdata address from global?', <hiveeyes.HistoricData object at 0x7fb1154cc4d0>)
 address in hiveeyes_schwarmalarm_filter()
('got hdata address from filter()?', <hiveeyes.HistoricData object at 0x7fb1154cc210>)

3. what I am trying to do/to address
  my mqtt broker sends the same topic  at 50 or less seconds  I need find a way to 'cache' these topics
say collect all 300 seconds topics and send them to another topic.

please help me, I am stucking at this for almost 2 weeks.

**Comment by amotl** [comment]
Hi there,

thanks for writing in, good to hear you are using _mqttwarn_ in an advanced scenario - let me see whether we can help.

----
> 1. need changed hiveeyes.ini to the following.

Currently, i don't know about your environment. Good to hear you have been able to make it work!

----
> 2. seems global value of hdata can not accessed by function hiveeyes_more_data() always has empty value. [when printing the `hdata` variable, i get responses like]
>
>        <hiveeyes.HistoricData object at 0x7fb1154cc4d0>

I don't see any problems here. The `hdata` variable contains a reference to an instance of a `HistoricData` object. To see what's in there, you should print one of its attributes like `hdata.fragments`, `hdata.history`, `hdata.states` or `hdata.moments`.

----
> 3. what I am trying to do/to address
my mqtt broker sends the same topic at 50 or less seconds I need find a way to 'cache' these topics say collect all 300 seconds topics and send them to another topic.

Actually, `hiveeyes_schwarmalarm_filter` implements similar mechanics to suppress any messages not triggering a certain condition. While the conditional logic is likely different within our Hiveeyes scenario (`if delta_nosign >= threshold`), you could step in there to apply the conditions matching your requirements. Interesting use case, good luck!

**Comment by 12019** [comment]
thank you for looking into this. 

clarify for question 2.

what I means  these 2 hdata have different memory address

('got hdata address from global?', <hiveeyes.HistoricData object at 0x7fb1154cc4d0>)
address in hiveeyes_schwarmalarm_filter()
('got hdata address from filter()?', <hiveeyes.HistoricData object at 0x7fb1154cc210>)

if it is the same value/class/object,  the address should be the same right? 

anyway  seems I find a way out and it seems so ugly.

I put  class HistoryData into another file called  historydata.py like the following,

import re
import copy
import time
import sqlite3
import json
from datetime import datetime
from pprint import pformat, pprint
from collections import deque, defaultdict


class HistoricData(object):

    # How many data points to remember
    backlog = 20

    def __init__(self):
        series_factory = lambda: deque(maxlen=HistoricData.backlog)

        # Some data containers for remembering ...

        # Inbound data payload fragments
        self.fragments = defaultdict(series_factory)

        # All attributes aggregated across consecutive data payload fragments
        # This is actually used for threshold comparison
        self.history = defaultdict(series_factory)

        # Arbitrary node states like "data-loss"
        self.states = defaultdict(dict)

        # Most recent moment of data acquisition per node
        self.moments = {}

# A single data container instance to rule them all
hdata = HistoricData()

then I import it in hiveeyes.py

and put "historydata" before all the 'hdata'. then it works. something like this.


    # Get current and previous measurements
    fragments = condition.copy()
    try:
        fragments['current'] = historydata.hdata.fragments[origin][-1]
    except IndexError:
        pass
    try:
        fragments['previous'] = historydata.hdata.fragments[origin][-2]
    except IndexError:
        pass


anyway thanks again for the help.
Bruce Lee.
