### ISSUE TITLE
Introducing an image from somewhere else (via functions) for possible inclusion

### ISSUE THREAD

**Issue by psyciknz** [jpmens/mqttwarn#302]
Hoping that issue #284 gets implemented and looking forward.
I'm hoping that upon message received (ie a garage door opening received on a topic) that in the funcs.py I could pull an image from a camera via http and use that as a pushover payload.

Is that a possible usecase?

**Comment by psyciknz** [comment]
So I've looked at updating the slack.py channel to post an image at the moment from a json payload where if imageurl: "url goes here" exists, it will download and post the image.

But now I need to figure out how to turn a topic with a useless payload of "ON" into a json string ie:
{'message': "ALERT Garage Door being Opened/Closed", 'imageurl': "http://192.168.10.204/image.jpg"}

So basically I need the incoming payload replaced with a custom one, I tried the format command (with the above string, but I don't think that is created as a json string.

Would I use a format = MakeJSONMethod() where I return a json string?

**Comment by sumnerboy12** [comment]
You need to manipulate the `data` dictionary in a [datamap](https://github.com/jpmens/mqttwarn#incorporating-topic-names-into-transformation-data) function. 

So you receive a simple `ON` payload, then have a function which can manipulate this to add extra fields or update existing fields. I.e. add an `imageurl` and reformat the payload to JSON.

Another option could be to use [templating](https://github.com/jpmens/mqttwarn#producing-json).

**Comment by psyciknz** [comment]
Not using the format = formatmethod()?

I've kinda got that working, in that it's creating a json payload that is including the image....but I can't actually access the original payload.

```
def PushoverAddImageUrl(topic=None, data=None, srv=None):

    text = "unknown"
    if data is not None and type(data) == dict:
       data = copy.copy(data)
       if srv is not None:
          srv.logging.debug('Data retrieved and is in dict format')
          srv.logging.debug(data)
       text = data['payload']
    else:
       if srv is not None:
           srv.logging.debug('Data retrieved and is in message format')
       if data is not None:
           text = data

    payload = {
         'message': text,
         'imageurl': "http://192.168.10.204/image.jpg"
    }

    if srv is not None:
        srv.logging.debug('New payload constructed:')
        srv.logging.debug(json.dumps(payload))

    return json.dumps(payload)
```

**Comment by psyciknz** [comment]
So using the same method in the datamap instead of format gets me that original payload (ON), but it doesn't give the service the json object it expects which is the message and imageurl strings...  Seems it one or the other.

**Comment by sumnerboy12** [comment]
You are right - doing it in the `format` function probably makes more sense. I assume you have changed the Slack service to check for a JSON payload and handle differently to a simple text payload?

You should be able to access the original payload via `data["payload"]'.

**Comment by psyciknz** [comment]
yeah it doesn't seem to give me that original payload.  In that code you can see I am checking each object for none before trying ot use it, and they all seem to be null.  So it's defaulting to that text.....oh and I update the pushover function not slack....since I didn't seem to be able to create a private slack channel.

**Comment by jpmens** [comment]
```python
print "********", data
```

I'm quite sure @sumnerboy12 is right: it's in there somewhere

**Comment by psyciknz** [comment]
print rather than trying to use the srv.logging (which also doesn't seem to be populated)?

What would have been nice was is I could just post a format as a json string, eg:
format  = {'message': "ALERT Garage Door being Opened/Closed", 'imageurl': "http://192.168.10.204/image.jpg"}

Just seems to make sense to me as it means the one config file knows the mapping between the topic and the external device, where at the moment its in a functions script.

I'll try that print.

**Comment by psyciknz** [comment]
Hmm so still getting none:
******** <__main__.Service object at 0x7f565e515d50>
******** None
******** <__main__.Service object at 0x7f565e515d50>
******** None

**Comment by psyciknz** [comment]
Ahh but the topic object....
-------- {'_dtepoch': 1522961508, '_dtiso': '2018-04-05T20:51:48.233638Z', 'topic': 'ParadoxMonitor/Event/Garage Door', '_dthhmm': '08:51', '_ltiso': '2018-04-06T08:51:48.233652', 'payload': 'ON', '_dthhmmss': '08:51:48'}

**Comment by jpmens** [comment]
They're the wrong way 'round.

**Comment by sumnerboy12** [comment]
See https://github.com/jpmens/mqttwarn#using-functions-to-replace-incoming-payloads.

**Comment by psyciknz** [comment]
it was the signature.  

I just had a quick look and I didn't see anything that show for a format method use def method(data) or def(method data, srv) for a datamap use xyz.

So now I'll just add something to the function to look at the topic and if garage door, then set message to the ALERT etc, and the imageurl to the url...

Then I can try and figure out your json payload with binary data.

**Comment by sumnerboy12** [comment]
Might be a worthy addition to the README - a section detailing all function signatures... PRs welcomed! ;)

**Comment by psyciknz** [comment]
yeah just thinking that. :) 

So for this I'll have an updated slack.py (had to change it to requests from urlib to add the image download via http....pity I can't figure out a way of making that more dynamic...but smalls steps.

**Comment by sumnerboy12** [comment]
Will close this as think we have proven/shown how to make it work.
