### ISSUE TITLE
mqttwarn is logging to mqttwarn.ini

### ISSUE THREAD

**Issue by dlangille** [jpmens/mqttwarn#307]
I'm finding that my configuration file is being appended to by mqttwarn 0.9.0

In the code, I find this in mqttwarn/commands.py 

```
    # Load configuration file
    config = load_configuration(name=scriptname)

    # Setup logging
    setup_logging(config)
```

But I can't that code in this repo.

Interesting that the tarball does not resemble this repo:

```
[dan@pro02:~/tmp/mqttwarn-0.9.0] $ ls -l
total 152
-rw-r--r--@  1 dan  staff    1628 Apr 12 21:41 CHANGES.rst
-rw-r--r--@  1 dan  staff   14197 Apr 12 21:41 LICENSE
-rw-r--r--@  1 dan  staff     126 Apr 12 21:41 MANIFEST.in
-rw-r--r--@  1 dan  staff    1352 Apr 12 21:41 Makefile
-rw-r--r--@  1 dan  staff  103470 Apr 12 21:41 README.md
-rw-r--r--@  1 dan  staff    4548 Apr 12 21:41 README.rst
drwxr-xr-x@ 27 dan  staff     864 Apr 12 21:41 assets
drwxr-xr-x@  4 dan  staff     128 Apr 12 21:41 doc
drwxr-xr-x@  9 dan  staff     288 Apr 12 21:41 etc
drwxr-xr-x@  7 dan  staff     224 Apr 12 21:41 examples
drwxr-xr-x@ 11 dan  staff     352 Apr 13 11:06 mqttwarn
-rw-r--r--@  1 dan  staff      49 Apr 12 21:41 requirements-release.txt
-rw-r--r--@  1 dan  staff    4615 Apr 12 21:41 setup.py
drwxr-xr-x@  4 dan  staff     128 Apr 12 21:41 templates
drwxr-xr-x@  4 dan  staff     128 Apr 12 21:41 vendor
```

**Comment by amotl** [comment]
Hi Dan,

thanks for writing in!

> mqttwarn is logging to mqttwarn.ini
> I'm finding that my configuration file is being appended to by mqttwarn 0.9.0

Thanks for reporting that. Bummer, this is of course not intentional! May we ask how you exactly start _mqttwarn_ to be able to reproduce the problem?

Regarding the code, the refactoring and preparation work for an upcoming mqttwarn 0.15.0 to be published on PyPI is all happening in the "develop" branch of this repository. Depending on where you got the tarball from, all things should be perfectly aligned.

What we can see from the directory listing you shared above: Yes, this is the file system layout of the new, refactored code base. You can find its sources when switching to the "develop" branch.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Here's the culprit:
https://github.com/jpmens/mqttwarn/blob/develop/mqttwarn/commands.py#L116

Thank you very much for reporting this. We will fix it right away.

**Comment by dlangille** [comment]
I think that line should be
```
setup_logging(config.logfile)

**Comment by dlangille** [comment]
After I made the above change to my code, it no longer logs to the ini file.

But now it's balking on:

```
*** /var/log/mqttwarn/mqttwarn-stderr.log ***
Traceback (most recent call last):
  File "/usr/local/bin/mqttwarn", line 11, in <module>
    load_entry_point('mqttwarn==0.9.0', 'console_scripts', 'mqttwarn')()
  File "/usr/local/lib/python2.7/site-packages/mqttwarn/commands.py", line 61, in run
    setup_logging(config.logfile)
  File "/usr/local/lib/python2.7/site-packages/mqttwarn/commands.py", line 93, in setup_logging
    LOGLEVEL = config.loglevelnumber
AttributeError: 'str' object has no attribute 'loglevelnumber'
Traceback (most recent call last):
  File "/usr/local/bin/mqttwarn", line 11, in <module>
    load_entry_point('mqttwarn==0.9.0', 'console_scripts', 'mqttwarn')()
  File "/usr/local/lib/python2.7/site-packages/mqttwarn/commands.py", line 61, in run
    setup_logging(config.logfile)
  File "/usr/local/lib/python2.7/site-packages/mqttwarn/commands.py", line 93, in setup_logging
    LOGLEVEL = config.loglevelnumber
AttributeError: 'str' object has no attribute 'loglevelnumber'
```

I'm happy to open another issue as I work through this.

**Comment by amotl** [comment]
No worries, the fix is almost ready. No need to open further issues for this specific problems. Thanks for staying with us!

**Comment by amotl** [comment]
Hi Dan,

we just published mqttwarn 0.10.0 which should fix the issue you were running into. Thanks again!

With kind regards,
Andreas.

**Comment by dlangille** [comment]
I got it, downloaded it, got it installed.  About to open another issue.  ;)

**Comment by amotl** [comment]
> I got it, downloaded it, got it installed.

So we can consider this very problem as resolved?

> About to open another issue. ;)

Sure, go ahead. We will be away from the keyboard for the weekend but will be happy to work on further issues next week. Thanks again for giving the new code base a try already and for spotting these kinds of edge cases.

Have fun!

**Comment by dlangille** [comment]
Yes, resolved. Thank you.
