### ISSUE TITLE
Update license to Eclipse Public License 2.0 (EPL-2.0)?

### ISSUE THREAD

**Issue by amotl** [jpmens/mqttwarn#309]
Dear @jpmens,

while working on #127, we (almost) bumped the license used by _mqttwarn_ to the Eclipse Public License version 2.0.

To make this happen, we also voted for inclusion of this license into the [list of Trove classifiers for PyPI](https://pypi.python.org/pypi?%3Aaction=list_classifiers), see also https://github.com/pypa/warehouse/issues/3660.

May we humbly ask you if you actually approve that?

Thanks,
Andreas.

**Comment by jpmens** [comment]
I'm accepting this proposal, because [the FSF states](https://www.fsf.org/blogs/licensing/eclipse-public-license-version-2-0-added-to-license-list-1):

> In terms of GPL compatibility, the Eclipse Public License version 2.0 is essentially equivalent to version 1.0. The only change is that it explicitly offers the option of designating the GNU GPL version 2 or later as a "secondary license" for a certain piece of code.

**Comment by amotl** [comment]
Thanks for doing further investigations about this topic, @jpmens! And good to hear about the outcome.
