### ISSUE TITLE
Icinga2 service fails (how to install requests module)

### ISSUE THREAD

**Issue by juey90** [jpmens/mqttwarn#312]
Hi,

i tried using the icinga2-check, but my messages are only being forwarded to other services (file and log),
the log says 

"DEBUG [icinga2] *** MODULE=services/icinga2.pyc: service=icinga2, target=check-service
ERROR [icinga2] Missing module: requests"

How do i get the requests module ?

My mqttwarn.ini
```
[defaults]
hostname     = 'mymqttbroker.domain'  ; default
port         = 1883
username     = None
password     = None
clientid     = 'mqttwarn'
lwt          = 'clients/mqttwarn'
skipretained = False
cleansession = True
protocol     = 3

; logging
logformat = '%(asctime)-15s %(levelname)-5s [%(module)s] %(message)s'
logfile   = 'mqttwarn.log'

; one of: CRITICAL, DEBUG, ERROR, INFO, WARN
loglevel  = DEBUG

; path to file containing self-defined functions for formatmap and datamap
functions = 'samplefuncs.py'

; name the service providers you will be using.
launch    = file, log, icinga2

[config:file]
append_newline = True
targets = {
    'f01'       : ['/tmp/f.01'],
    'log-me'    : ['/tmp/log.me'],
    'mqttwarn'  : ['/tmp/mqttwarn.err'],
    'mqttlog'   : ['/home/mqttwarn/test.log'],
    }

[config:log]
targets = {
    'debug'  : [ 'debug' ],
    'info'   : [ 'info' ],
    'warn'   : [ 'warn' ],
    'crit'   : [ 'crit' ],
    'error'  : [ 'error' ]
  }

[test/alarm]
targets = file:mqttlog, icinga2:check-service

[config:icinga2]
host = 'https://icingahost'
port = 5665
username = 'icingaapiusername'
password = 'icingaapipassword'
targets = {
   'check-service' : [ 'host.domain', 'mqtt', 'mqttwarn' ],
  }
; special config for 'failover' events
[failover]
targets = log:error, file:mqttwarn
```

**Comment by jpmens** [comment]
pip install requests

**Comment by juey90** [comment]
Thank you! Now it works. 
For someone with zero knowledge in python, its hard to figure out what happened, maybe the Wiki oder the Icinga2 section of the README should be updatet.

**Comment by jpmens** [comment]
I think a light search would have solved your issue. :-) Glad you got it working.

**Comment by amotl** [comment]
> For someone with zero knowledge in python, its hard to figure out what happened, maybe the Wiki oder the Icinga2 section of the README should be updated.

#127 will also solve this gap by providing the "requests" module as one of the default dependencies which will get installed together with mqttwarn itself.
