### ISSUE TITLE
mysql_remap - Could not prevent insert into MySQL-DB

### ISSUE THREAD

**Issue by DerManni** [jpmens/mqttwarn#313]
Hello.

I am trying to check, if an entry for a sensor is writtin within the last 60 seconds. If yes the MySQL-Insert should be aborted, if no it should be done. I tried using the recommended "alldata"-Option like the manual said.

- mqttwarn.ini

 > ...
> functions = 'functions.py'
> launch    = log, mysql_remap
> ...
> [config:mysql_remap]
> host  =  'localhost'
> port  =  3306
> user  =  'phpmyadmin'
> pass  =  'secret'
> dbname  =  'sensors'
> targets = {
>          't1'   : [ 'rtl_433',
>                             {
>                               'time': 'time',
>                               'id': 'sensor_id',
> 							  'channel': 'sensor_channel',
> 							  'battery': 'sensor_battery_status',
> 							  'temperature_C': 'temperature',
> 							  'humidity': 'humidity',
>                             },
>                             {
>                               'description' : 'Oregon Scientific THGR122N'
>                             }
>                   ]
>          }
> ...
> [RTL_433_p12]
> targets = mysql_remap:t1
> alldata = mysql_check_insert()

- functions.py

> import time
> from datetime import datetime
> from datetime import timedelta
> import copy
> import ast
> import MySQLdb
> import sys
> 
> def mysql_check_insert(topic, data, srv=None):
>     # Get the actual datetime
>     print "--------------------New Reading--------------------"
>     now = datetime.now()
>     print "Now: ",now
> 
>     # parse json payload (the message)
>     payload = ast.literal_eval(data["payload"])
>     
>     ### --- Got comparison data from MySQL  
>     pl_id = payload["id"]
>     pl_temperature = payload["temperature_C"]
>     pl_humidity = payload["humidity"]    
> 
>     ### --- Get the comparison data from MySQL
>     # open a database connection
>     # be sure to change the host IP address, username, password and database name to match your own
>     connection = MySQLdb.connect (host = "localhost", user = "phpmyadmin", passwd = "phpmyadmin#1985", db = "sensors")
> 
>     # prepare a cursor object using cursor() method
>     cursor = connection.cursor ()
> 
>     # execute the SQL query using execute() method.
>     cursor.execute ("select sensor_id, time, temperature, humidity from rtl_433 where sensor_id = %s order by row_id desc limit 1", (pl_id,))
> 
>     # fetch all of the rows from the query
>     data = cursor.fetchall ()
> 
>     # print the rows
>     for row in data :
>         print row[0], row[1], row[2], row[3]
> 
>     # close the cursor object
>     cursor.close ()
> 
>     # close the connection
>     connection.close ()    
>     
>     print "DB-Time:",row[1]
>     #pl_time = datetime.strptime(pl_time, '%Y-%m-%d %H:%M:%S')
>     #print "DT-Object  :",pl_time
>     tdelta = now - row[1]
>     print "Time between",tdelta.total_seconds()
>     payload['time'] = now.strftime('%Y-%m-%d %H:%M:%S')
>     if tdelta.total_seconds() > 60:
>         print "Entry will be written"
>         print payload
>         return payload
>     else:
>         print "No entry"
>         return None  

The functions.py works flawlessly. I got the result I like to have. But it seems that the mqttwarn ignores my returned payload and uses instead the RAW-Data from the broker.

Could it be a bug or did I missed something important?

Thanks in advance.
Manni

**Comment by jpmens** [comment]
It's a pity you've added code as quotes ... placing code between lines of three backtics each, makes it readable.

If you would please show an example publish with the data you expect to see, I'll have a look at it.

**Comment by jpmens** [comment]
Closing for lack of response
