### ISSUE TITLE
an official Docker image?

### ISSUE THREAD

**Issue by rgitzel** [jpmens/mqttwarn#318]
I've been running `mqttwarn` in Docker on my laptop to experiment, and now plan to run it for real in Docker on my Synology NAS.  (I've got all my automation tools running in Docker: Mosquitto, Home Assistant, Node-Red; even InfluxDB and Grafana run just fine on the NAS.)  It's worked quite well, however, I've had to create my own Docker image. 

So I propose a `Dockerfile` be added to this project, and an image be published to Dockerhub whenever a new version is released.

There seems to be interest in such a thing, as there are 11 images [already in Dockerhub](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=mqttwarn&starCount=0), unfortunately most of them were one-offs and/or are quite old.

Fortunately, a good `Dockerfile` does already exist:  https://github.com/pfichtner/docker-mqttwarn  He just doesn't publish the images.

If @pfichtner agrees, his file could be added here. The only changes I would suggest is (1) to build the image from a GitHub tag, rather than from `master`, and (2) to include all the optional Python packges (like `jinga2`).  I can change the `Dockerfile` to take the tag as a parameter, making it easier to publish when `mqttwarn` is versioned.

**Comment by pfichtner** [comment]
Please feel free to use and change my Dockerfile as needed

**Comment by pfichtner** [comment]
Perhaps beside the tagged versions (foobar:version) you could also push master builds (foobar:latest) to docker hub?

**Comment by amotl** [comment]
We will also provide pip-installable Python sdist packages on PyPI, see #127. We are almost there, i will try to push things further.

Just FYI: This might have an impact on how Docker images are built, specifically because we will employ solid versioning and repository tagging after this has been merged.

**Comment by rgitzel** [comment]
@pfichtner I wasn't thinking straight:  now that the Dockerfile is in the same repo as the application, the Github tag doesn't matter.  The Docker image will always be built from master, and then tagged with the version (including `latest`) when it's deployed to Dockerhub

**Comment by rgitzel** [comment]
I've created a PR: https://github.com/jpmens/mqttwarn/pull/320

For now, this is the @pfichtner Dockerfile, with a change to use the files currently checked out, rather than from Github directly.

This will work for the current version, and the Docker image can be published to Dockerhub for the existing release (0.10.1).

I will also work on a version of it based on the new `pip` work in `develop`.

**Comment by rgitzel** [comment]
@jpmens Thanks for the merge! :-)

Feel like deploying it up to Dockerhub?  I could give the published image a try on my NAS over the weekend....

**Comment by jpmens** [comment]
This will happen when the time comes.

**Comment by rgitzel** [comment]
@jpmens Okay. That means the README is incorrect, but I've submitted a PR to handle it.

**Comment by rgitzel** [comment]
Tada!

**Comment by jpmens** [comment]
Thank you, again, @rgitzel, for your great help on getting this done.
