### ISSUE TITLE
Change the default title of outbound messages

### ISSUE THREAD

**Issue by robdejonge** [jpmens/mqttwarn#333]
**Current behavior**
When no `title` is defined in a topic section of the INI file, outbound messages have `mqttwarn` as a title. 

**Proposed behavior**
When no `title` is defined, outbound messages have the MQTT topic as a title.

**Comment by jpmens** [comment]
Would `mqttwarn <topic>` be okay too, in order to identify it? I'm thinking of people getting something titled `k05/c/room` and thinking it may be spam from some country or other. :-)
