### ISSUE TITLE
InfluxDB service: Format  string

### ISSUE THREAD

**Issue by HillNet** [jpmens/mqttwarn#338]
Hi,

Further to my post [https://github.com/jpmens/mqttwarn/issues/294#issuecomment-426038966](url) I'm trying to add an additional tag into the line protocol for my "un-nested" JSON bundle.

The code (influxdb.py) looks like it constructs the data point as:
`measurement,tag_set field_set timestamp` and I'd like `measurement,tag_set,tag_set field_set timestamp`

My attempts to do this with either adjustments to my function (un-nesting JSON) or adding tags as per this example fail.

> ```
> [environment/temperature/basement]
> targets = influxdb:temperature
> format = room=basement,entity=sensor2 temperature={payload}
> ```

I'm not a coder (but happy to try), so would appreciate some guidance how this might be achieved.

--
Thanks,

Roland

**Comment by rgitzel** [comment]
Is it that your extra tag isn't being added at all? Or that a variable isn't being replaced?

Do you have an example of your `format` and what it results in?

**Comment by HillNet** [comment]
**[SOLVED]**
@rgitzel refer [https://github.com/jpmens/mqttwarn/issues/294#issuecomment-426828725](url) for the solution.

My version of mqttwarn was old.

--
Roland
