### ISSUE TITLE
Publish the official Docker image

### ISSUE THREAD

**Issue by rgitzel** [jpmens/mqttwarn#341]
@jpmens it would seem from https://github.com/jpmens/mqttwarn/pull/339 that another user has had to create their own image in Docker Hub, one that works slightly differently from the image defined at https://github.com/jpmens/mqttwarn/blob/master/Dockerfile

Could you publish the "official" image?  If nothing else, it would make it easier to support issues from Docker users

**Comment by jpmens** [comment]
Look: all by myself! :-) 

![jmbp-4843](https://user-images.githubusercontent.com/60706/47616025-8466cc80-dab7-11e8-81bf-6b08c9b01e96.png)

**Comment by jpmens** [comment]
Thanks to your work on the Dockerfile, etc. of course!

```
Removing intermediate container 5b8190284989
---> e57c8a34345f
Successfully built e57c8a34345f
Successfully tagged jpmens/mqttwarn:latest
Pushing index.docker.io/jpmens/mqttwarn:latest...
Done!
Build finished
```

Can you test the result for us, @rgitzel ?

**Comment by rgitzel** [comment]
Congrats!!! :-)

I'll give it a try when I'm not tethered to my phone. 

The next trick will be adding a version tag.  Did you publish from your command line, or using the automated build?  Neat trick, I haven't tried that one before.

**Comment by rgitzel** [comment]
Unfortunately I didn't link to the manual instructions, here, that might have saved you some time:  https://github.com/jpmens/mqttwarn#build-the-image

I'm a bit leery of automatically publishing the image on a commit to the master branch, as it would update the `latest` image even for a simple typo fix in the README. 

The typical thing to do for Docker images is to explicitly give them a version tag (e.g. "1.7") as the associated applications are released.  Then the tag `latest` is applied to the most recent image (essentially acting as an alias to the version).   

Each version tag is considered immutable, but only by convention, as Dockerhub will let you move any tag to any image.  As code changes are made and the application version changes, new images are published with _new_ tags (e.g. "1.7.1", "1.8").  The existing tags all remain in place, except for `latest` which is moved to the image that should be considered the current release.

So... in this case, rather than republishing the image automatically on a Git commit, it is probably clearer to do the build/tag/push steps manually when a new version of the app is released.   Probably the Dockerhub automation could do that, but that might be more complicated to set up than it's worth?  When the `dev` version is ready, it could become part of the process that publishes the Pip artifact?  (i.e. push the image to Docker Hub, instead of Docker Hub pulling it from Git).

Hopefully that's not too confusing. ;-)

**Comment by rgitzel** [comment]
@tomhoover could you give `jpmens/mqttwarn` a go?  

I tried a few things, it seems to work.  However in practice I'm running the `dev` version in Docker.  I guess that will be the next step?

**Comment by rgitzel** [comment]
@jpmens  Do you have a list of tests you execute on each release to make sure everything is working?

**Comment by jpmens** [comment]
@rgitzel we do not yet but hope to get that setup in the dev branch; input welcome.

**Comment by jpmens** [comment]
@rgitzel I've changed the build rule as follows:

![jmbp-4845](https://user-images.githubusercontent.com/60706/47674865-9d0adb80-dbb8-11e8-963e-d19ebc7904d5.png)

I will now push a tag to see whether this does what you're suggesting, without me having to "carry docker around with me", i.e. without requiring access to CLI tools.

**Comment by jpmens** [comment]
Does this look ok to you?

```
Successfully built f040f60a4e7b
Successfully tagged jpmens/mqttwarn:release-0.10.2
Pushing index.docker.io/jpmens/mqttwarn:release-0.10.2...
Done!
Build finished
```

**Comment by rgitzel** [comment]
Cool. :-)

Are you using Docker Hub to do this?  That doesn't look like the automated build page I just brought up.

**Comment by jpmens** [comment]
Docker cloud, it's called. [https://cloud.docker.com/repository/docker/jpmens/mqttwarn/](https://cloud.docker.com/repository/docker/jpmens/mqttwarn/)

**Comment by rgitzel** [comment]
Nice, hadn't seen that before.  

I gave it a go with my branch, to see if I could get it to do both the version and 'latest' tags... tried creating TWO autobuilds, but that created two images.

Hmmm.

Well, there's nothing like reading the documentation:   https://docs.docker.com/docker-cloud/builds/automated-build/#create-multiple-docker-tags-from-a-single-build

![image](https://user-images.githubusercontent.com/688749/47678930-2e119080-db80-11e8-98fd-874747d4dafd.png)

So looks like adding `,latest` to your "Docker Tag" setting will create both tags on the same image.

**Comment by jpmens** [comment]
I hugely appreciate you doing my homework for me! :-) This is what the result looks like:

![jmbp-4846](https://user-images.githubusercontent.com/60706/47679645-055fba00-dbc5-11e8-9ed9-59db802e6423.png)

**Comment by rgitzel** [comment]
You're welcome! 

And....  pull it down by version....
```
$ docker pull jpmens/mqttwarn:release-0.10.3
release-0.10.3: Pulling from jpmens/mqttwarn
bc9ab73e5b14: Already exists
193a6306c92a: Already exists
e5c3f8c317dc: Already exists
a587a86c9dcb: Already exists
72744d0a318b: Already exists
23bf491a4f84: Already exists
7f3410abb2aa: Already exists
08c5081d43e2: Already exists
80a779c2daa3: Already exists
a05d8e0d7f9f: Pull complete
ea95d9a2beaa: Pull complete
b2150cdd9a7d: Pull complete
1b7d359f6676: Pull complete
de9457de73de: Pull complete
Digest: sha256:66d2202fcb236026a3a23c47be5fd88678606d3a8df8c93d2a3dcfac7ba7d57f
Status: Downloaded newer image for jpmens/mqttwarn:release-0.10.3
```

Then `latest`...
```
$ docker pull jpmens/mqttwarn:latest
latest: Pulling from jpmens/mqttwarn
Digest: sha256:66d2202fcb236026a3a23c47be5fd88678606d3a8df8c93d2a3dcfac7ba7d57f
Status: Downloaded newer image for jpmens/mqttwarn:latest
```
The second `pull` didn't download anything, and the SHA is the same.  So it's the same image.  Success!!

**Comment by tomhoover** [comment]
> @tomhoover could you give `jpmens/mqttwarn` a go?
> 
> I tried a few things, it seems to work. However in practice I'm running the `dev` version in Docker. I guess that will be the next step?

Changed to the 'official' Docker image (on my unRAID server), with:

    docker run --name=mqttwarn -e MQTTWARNINI=/opt/mqttwarn/conf/mqttwarn.ini -e MQTTWARNLOG=/opt/mqttwarn/conf/mqttwarn.log -v /mnt/cache/appdata/mqttwarn:/opt/mqttwarn/conf jpmens/mqttwarn

Thanks!

**Comment by rgitzel** [comment]
@tomhoover Try leaving out the `MQTTWARNINI` variable, as it's already set in the Docker image.

Logging is something I want to improve; I'd like to configure the Docker image so that all of the app logs go to `stdout`, then `docker logs -f mqttwarn` will display what's going on in the container.

In the meantime, I `docker exec` into the running container and `tail` the log file there, when I need to know what's going on.

**Comment by amotl** [comment]
Thanks for your efforts guys, i've been following your progress a bit. Kudos!

> @rgitzel: However in practice I'm running the dev version in Docker. I guess that will be the next step?

> @rgitzel: Do you have a list of tests you execute on each release to make sure everything is working?
> @jpmens: we do not yet but hope to get that setup in the dev branch; input welcome.

Always wanted to perform the probably tricky rebase of develop onto master in order to prepare the final integration of each other since weeks, but various obligations regarding production issues and real life keep intervening constantly. I feel sad about this and also want to apologize about not being able to make any progress there. Sorry for that.

If you switch to the develop branch while ignoring everything which arrived in master since branching off, running `"make test"` should make you smile.

**Comment by amotl** [comment]
> I'd like to configure the Docker image so that all of the app logs go to `stdout`

_mqttwarn_ should be able to accept things like `logfile = stream://sys.stderr` already - even in the master branch.

**Comment by egadgetjnr** [comment]
Hey All,
So very happy that this is now on Docker Hub. This is a huge achievement and a great step towards world domination of MQTTWarn!

@jpmens just my 2 cents, and you can completely disregard it if you want, but do you think it would be better to just have the tag without `release-` to follow consistency of all other docker images (they usually just have the version number as the tag, so it would be `jpmens/mqttwarn:0.10.3` instead)?

**Comment by jpmens** [comment]
@egadgetjnr done as requested: I've changed `Docker tag` to `{sourceref},latest`.

```
Successfully built 7e844eacc9d5
Successfully tagged jpmens/mqttwarn:0.10.4
Pushing index.docker.io/jpmens/mqttwarn:0.10.4...
Done!
Build finished
```

**Comment by amotl** [comment]
Hi there,

after making #127 finally happen, we might want to think about amending these lines within the `Dockerfile`.

https://github.com/jpmens/mqttwarn/blob/1aaf291182ae253646fb080436ecb40b853175db/Dockerfile#L25-L30

Instead, after adding it to the `pip install` command,

https://github.com/jpmens/mqttwarn/blob/1aaf291182ae253646fb080436ecb40b853175db/Dockerfile#L6

it might be invoked through
```
CMD mqttwarn
```

already.

**Comment by amotl** [comment]
Dear @tinuva, @rgitzel, @tomhoover, @egadgetjnr, @psyciknz and all Docker lovers,

#127 and #336 have come pretty far that we might think about improving the Dockerization once more.

> Do you think it would be better to just have the tag without the `release-` prefix in order to follow consistency of all other docker images? They usually just have the version number as the tag, so it would be `jpmens/mqttwarn:0.10.3` instead.

I would like to second that comment by @egadgetjnr for the next round of published Docker images.

The best thing would be to automate the release process of producing and publishing Docker images through the CI system. We went for CircleCI [1] and would really appreciate any contributions for making that happen.

With kind regards,
Andreas.

[1] https://circleci.com/gh/jpmens/mqttwarn

**Comment by psyciknz** [comment]
I think with proper manifests now,  the architecture designation is less relevant.   Ie jpmens/mqttwarn:arm32v7-0.1.3

I have cross build scripts for the 3 architectures I was using.    And know at the time I looked at it (early this year) that travis could not use qemu for arm/arm64 builds.    Will have to see if circleci can.

**Comment by psyciknz** [comment]
So further thoughts now that I am not phone based.    I know with my docker image I build here at home I have to add slacker to the pip command for slack.  This comes back to the issue of what to include in the official image.....

I believe a way to solve it would be to have 
```
pip install paho-mqtt requests jinja2 
```
in the DockerFile.

But then change the 
```
CMD python mqttwarn.py 
```
run command to 
```
# run process
CMD ["/bin/bash" , "run.sh"]
```

This can allow the user to set their own pip before calling the main mqttwarn.py
eg: https://github.com/psyciknz/mqttwarn/blob/local-services/run.sh

**Comment by amotl** [comment]
Dear @koenvervloesem,

thanks a bunch for your contribution from #422. It would also be cool to switch to Python 3 here, see #416. I would prefer `python:3.8.2-slim-buster` [1] if nobody has any objections.

Following up on that, we might also look into what @lenny1972 outlined within #419:
a) How do you specify the configuration file?
b) Where do you put custom functions into?

With kind regards,
Andreas.

[1] https://hub.docker.com/_/python

**Comment by koenvervloesem** [comment]
I have this in my `docker-compose.yml`:

```
  mqttwarn:
    image: mqttwarn 
    container_name: mqttwarn
    restart: always
    volumes:
      - /home/pi/containers/mqttwarn:/opt/mqttwarn/conf/
      - /etc/localtime:/etc/localtime:ro
```

I put `funcs.py` in `/home/pi/containers/mqttwarn`. And then I define its location in `mqttwarn.ini`:

`functions = '/opt/mqttwarn/conf/funcs.py'`

This correctly runs my custom functions.

**Comment by amotl** [comment]
Dear Koen,

thanks a bunch for sharing your `docker-compose.yml`, I appreciate your responsiveness on that topic. In order to improve things for the community, can I humbly ask you to add this file to the root directory of this repository?

I would like to suggest a minor update in order to finally move away from the installment into `/opt/mqttwarn` introduced the other day: Why not have the mqttwarn configuration and custom functions file at these locations?
- `/etc/mqttwarn/mqttwarn.ini`
- `/etc/mqttwarn/funcs.py`

Thanks already and with kind regards,
Andreas.

---

P.S.: I don't know if it's possible to place comments within the YAML file. If this works out, we could add this guideline straight into it like:
```
# Define the location to the custom functions file within "mqttwarn.ini":
functions = '/etc/mqttwarn/funcs.py'
```

**Comment by koenvervloesem** [comment]
Sure, I'll test these changes and send another PR afterwards.

Comments in the Docker Compose file are perfectly possible, I do it all the time to document non-trivial service configurations.

**Comment by koenvervloesem** [comment]
@amotl Where exactly do I comment these guidelines you showed? I only found a 'default' mqttwarn.ini in [mqttwarn/examples/basic/mqttwarn.ini](https://github.com/jpmens/mqttwarn/blob/master/mqttwarn/examples/basic/mqttwarn.ini). Is that the place to add this?

**Comment by amotl** [comment]
Dear Koen,

thanks for #423 already! I've suggested to just put this snippet directly into the `docker-compose.yml` file. However, as I'm not an expert on this, I might well miss some point here.
```
# 1. Acquire "docker-compose.yml":
# wget https://raw.githubusercontent.com/jpmens/mqttwarn/master/docker-compose.yml
#
# 2. Define the location to the custom functions file within "mqttwarn.ini":
#
# functions = '/etc/mqttwarn/funcs.py'
```

Cheers,
Andreas.

**Comment by koenvervloesem** [comment]
Ok, I was just a bit confused whether it should be in mqttwarn.ini or docker-compose.yml, but you're right it should be in the latter. I put your suggested documentation in there now and I expanded it a bit further.

**Comment by lenny1972** [comment]
Thanks Koen for your docker-compose snippet example.

I've copied your configuration on my docker-compose.yml file but in the
mqttwarn.log file I always get the same error (for what I've opened the
issue).

The only one modification to your snippet is the change iof the host folder
location. This is my docker-compose.yml section regarding mqttwarn service

  mqttwarn-full:
    container_name: mqttwarn
    restart: always
    image: rgitzel/mqttwarn-full
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/opt/mqttwarn/conf:/opt/mqttwarn/conf/'
      - '/opt/mqttwarn/log/mqttwarn.log:/opt/mqttwarn/mqttwarn.log'

And that's the part of the mqttwarn.ini file where I've defined my custom
function path (my function is called my_carbon.py) as per your suggestion

functions = '/opt/mqttwarn/conf/my_carbon.py'

So I've saved in my host at location /opt/mqttwarn/conf folder my function
my_carbon.py (below a screenshot of the host folder containing both the
mqttwarn.ini file and my custom function)

[image: host folder.gif]


But when I run the docker compose file it ends up with this error


2020-05-05 08:49:49,232 INFO  [mqttwarn] Starting mqttwarn

2020-05-05 08:49:49,232 INFO  [mqttwarn] Log level is DEBUG

2020-05-05 08:49:49,235 DEBUG [mqttwarn] Service file loaded

2020-05-05 08:49:49,236 DEBUG [mqttwarn] Service log loaded

2020-05-05 08:49:49,237 DEBUG [mqttwarn] Service carbon loaded

2020-05-05 08:49:49,237 ERROR [mqttwarn] Can't load my_carbon service
(services/my_carbon.py): [Errno 2] No such file or directory:
u'services/my_carbon.py'

It seems that the main process (mqttwarn.py) is still searching for
the custom function file in the default directory (services) and not
in the path I've defined in the mqttwarn.ini configuration file
(/opt/mqttwarn/conf/my_carbon.py).

Can you please help me in understand?

Which docker image are you using?

Thanks in advanced,

Leonardo



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno lun 4 mag 2020 alle ore 19:34 Koen Vervloesem <
notifications@github.com> ha scritto:

**Comment by koenvervloesem** [comment]
@lenny1972 I used the official `jpmens/mqttwarn` image.

**Comment by amotl** [comment]
@tinuva has a nice [Dockerfile](https://github.com/tinuva/mqttwarn/blob/049e1539c7de3898e3cc4bbf00b87ecf5c41b6a0/Dockerfile) with some extended dependencies for serving more service plugins out of the box.

**Comment by lenny1972** [comment]
Thanks Andreas, I'll take a look at he dockerfile of @tinuva
;)

Inviato dal mio OnePlus 3T

Il dom 5 lug 2020, 03:24 Andreas Motl <notifications@github.com> ha scritto:

**Comment by amotl** [comment]
Hi again,

I believe this ticket can also be closed. Please let me know if there are still issues about the topics discussed here.

With kind regards,
Andreas.
