### ISSUE TITLE
Update to slack - adding images

### ISSUE THREAD

**Issue by psyciknz** [jpmens/mqttwarn#346]
Hi  more a query.  As you know I added image support to pushover (and a new PR out today with some updates).  I'm thinking of doing the same for slack.

Are you ok if I use the same system for posting images.   Ie either imagebase64 for base 64 encoding images in the mqtt payload, or imageurl for a url where to get the image?

If so then I'll start on it.

**Comment by jpmens** [comment]
What other systems for posting images to Slack are there? What do people use?
While you're at it: you might also please compare whether your changes would be suitable for our `mattermost` plugin.

**Comment by psyciknz** [comment]
Sorry I mean are you happy if  usethe same code fragment that i posted for pushover, for the slack plugin.

Eg imageurl, imagebase64 and the new auth modes.   Gives users the options of slack or pushover for posting images from mqtt sources.

Are you wanting me to look at doing the same fro mattermost?

**Comment by jpmens** [comment]
We'll take similar modifications with documentation for the `slack` service. If you can, it would be good to add that capability to the `mattermost` service as well.

**Comment by psyciknz** [comment]
Ok.   Definitely should be able to slack.  And I’d use that myself.

Mattermost I’ll investigate.   I’ve not used that service

**Comment by psyciknz** [comment]
#345 #347 
Added image support to pushover
