### ISSUE TITLE
execute service issue

### ISSUE THREAD

**Issue by smartandsafe** [jpmens/mqttwarn#357]
Hi

i am having problem trying to execute php command 

i have this in my config

`[config:execute]
targets = {
             # argv0 .....
   'llamada' : [ '/usr/bin/php', '/opt/llamadas.php ABCDEQpalzM123 3137122940' ]
   }
`
and i get this message, i see an extra 'u' character before command, i have not idea how to solve it.

2019-01-16 17:27:02,226 WARNING [execute] Cannot execute [u'/usr/bin/php', u'/opt/llamadas.php ABCDEQpalzM123 3137122940'] because Command '[u'/usr/bin/php', u'/opt/llamadas.php ABCDEQpalzM123 3137122940']' returned non-zero.......

thank you

**Comment by jpmens** [comment]
Don't worry about the `'u'`; it's ugly but just means unicode string.

The issue you are seeing is described further on: 

> because Command '[u'/usr/bin/php', u'/opt/llamadas.php ABCDEQpalzM123 3137122940']' returned non-zero

Does your `/opt/llamadas.php` script `exit(0);` ?

**Comment by smartandsafe** [comment]
i can run the script  /opt/llamadas.php from command line without issues

i have tried changing own for script without success, same warning message

**Comment by jpmens** [comment]
Run it from the command line and then immediately:

```bash
$ /opt/llamadas.php ABCDEQpalzM123 3137122940
$ echo $?
```

and tell me the output of the `echo`

**Comment by smartandsafe** [comment]
$ /opt/llamadas.php ABCDEQpalzM123 3137122940
$ echo $?
$ 2

**Comment by jpmens** [comment]
> because Command '[u'/usr/bin/php', u'/opt/llamadas.php ABCDEQpalzM123 3137122940']' returned non-zero..

Unix utilities return `0` when they indicate success, non-zero for failure. Your PHP script exited with a failure, hence the warning, but the program was executed.

This is not an mqttwarn issue.

**Comment by smartandsafe** [comment]
Thankyou
