### ISSUE TITLE
function string type with mqttwarn in container

### ISSUE THREAD

**Issue by przemas75** [jpmens/mqttwarn#358]
Hello,
Im a user of owntracks and tried to move mqttwarn to container.
However 'datamap' with a function OwnTracksTopic2Data() (i have used default one) does not work, it throws me  a warning:

`WARNING [mqttwarn] Cannot format message: u'username' `

This goes also for deviceid from topic.
I have found in docker container the topic is not type string but unicode.

**Comment by rgitzel** [comment]
Hi @przemas75, 

"move to container" means running this in Docker? https://hub.docker.com/r/jpmens/mqttwarn

What version of `mqttwarn` were you using before?  It's odd the validation logic would have changed.

Thanks.

**Comment by przemas75** [comment]
Yes, i meant running this in Docker (actually i build this myself, but also tested official container).
And unfortunately, my previous mqttwarn was VEEERY old... probably 3 years... 

After seeing this not working (in docker container) i run it from tar.gz, then checked official container. For me it was not working. 
But this function did not change since these years.

**Comment by jpmens** [comment]
@przemas75 Sorry, but I am a bit confused. Does this or does this not work when you run it outside of Docker? Which version of Python?

**Comment by przemas75** [comment]
It does work without container. In a container it showed the errors i posted (for function OwnTracksTopic2Data).
Default python in Debian 2.7.13 and in container i believe it was 2.7.15.

**Comment by doebi** [comment]
I am having the exact same issue, either with or without docker. Trying to extract information from the topic to use it as tags for influxdb.

Any help appreciated.

Python v2.7.16 outside of docker

**Comment by rgitzel** [comment]
Christoph,

Is this showing up when you use the Dockerfile in the repo?  Or are you
making your own?

rodney

**Comment by doebi** [comment]
Hi rodney, thanks for your reply.

I am using docker-compose with "jpmens/mqttwarn:latest" as image definition.
I ust checked, the latest image was built 9 months ago.

Is the docker image in public repos up to date?

**Comment by doebi** [comment]
well yeah. I just removed the line with type check: https://github.com/jpmens/mqttwarn/blob/master/samplefuncs.py#L12

...and now it's working. Why did you check for simple strings in that example func anyway?

**Comment by jpmens** [comment]
I don't know. Would you be so kind as to make a PR which changes that?

**Comment by doebi** [comment]
Ok. I just thought, maybe there is some reason or deeper meaning to it.
