### ISSUE TITLE
Send warning when there is no payload message for long time from a sensor

### ISSUE THREAD

**Issue by jpduyx** [jpmens/mqttwarn#361]
How can I configure MQTT warn to send a warning when the topic doesn't have any expected payload for longer than <variable_setting> minutes ?

**Comment by jpmens** [comment]
You cannot using mqttwarn.

What you probably want to do is record a timestamp whenever you get a particular payload and then, independently, using a monitoring system, evaluate that.

**Comment by jpmens** [comment]
As I say: that's a task for monitoring; I don't think we'll add this.

**Comment by amotl** [comment]
Hi there,

thanks for writing in.

## Introduction
What you are talking about resonates very well with us when it comes to monitoring data acquisition systems in production. While I totally agree with @jpmens that this would be better to implement with a real monitoring system, there is one particular functionality in _mqttwarn_ which made us try just that the other day, the [periodic tasks](https://github.com/jpmens/mqttwarn#periodic-tasks) feature.

It works well for us, but is really stretching _mqttwarn_ to one of its boundaries regarding what you actually **should** do with it (or not). Saying that, there **are** use-cases where a full-blown monitoring system would not fit, e.g. when aiming to deploy to a standalone [SBC](https://en.wikipedia.org/wiki/Single-board_computer). Hello RaspberryPi.

To quote @jpmens, the task of such a **data loss sensor** (which can well be used from real monitoring systems as well) is to
> record a timestamp whenever you get a **particular payload** and then **independently [...] evaluate** that.

## Data-loss monitoring with mqttwarn
In this context, I'd like to point you to 588ddca6, used to implement [data-loss event notifications within the Hiveeyes system](https://hiveeyes.org/docs/system/schwarmalarm-mqttwarn.html#data-loss-events) with _mqttwarn_. 

- The aspect of **independently evaluating** the system state is done by a service function  scheduled by the _periodic tasks_ feature of _mqttwarn_.

- The aspect of checking what a **particular payload** which should reset the TTL **actually is**, is a matter of the implementation of this service function.


## A little howto
Besides the actual sensor implementation [`hiveeyes_dataloss_monitor`](https://github.com/jpmens/mqttwarn/blob/a67347c9/examples/hiveeyes/hiveeyes.py#L252), there will be two parameters to configure this little guy.

- The monitoring interval, thus defining the granularity of the sensor, is defined in `mqttwarn.ini` by configuring the service function like
  ```ini
  [cron]
  ; Monitor all seen devices for data loss events.
  hiveeyes_dataloss_monitor = 60.0; now=true
  ```

- The TTL value for configuring after which time an actual data loss should trigger a notification event is currently defined in Python land like:
  ```python
  # Trigger a data-loss event when not receiving any fresh
  # data after 20 minutes from a device already seen before.
  data_loss_timeout = 20 * 60
  ```

Remark: The specific implementation `hiveeyes_dataloss_monitor` is designed for monitoring particular data acquisition nodes in a multi-device scenario.

## Conclusion
So, to reiterate »_It works well for us, but is really stretching _mqttwarn_ to one of its boundaries_«: While we added [all things required](https://github.com/jpmens/mqttwarn/pulls?q=author%3Aamotl+created%3A<%3D2016-07) to spawn a multi-tenancy micromonitoring system with _mqttwarn_ the other day, you should really know what you are doing to make everything fit together, especially when it comes to the corresponding constraints of that system.

However, it will give you a lightweight, single-process, multi-tenant data-loss monitoring and notification system without having to spin up larger beasts. From this perspective, _mqttwarn_ again fills a good niche for us. Kudos again!

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear @jpduyx,

may we humbly ask if you had a chance to review my answer already? I believe the data-loss sensor/notification as outlined above is the best you will be able to achieve with mqttwarn, and honestly, this is quite something.

With kind regards,
Andreas.

**Comment by jpmens** [comment]
Closing as answered.
