### ISSUE TITLE
My coding error in a function doesn't indicate it's a coding error

### ISSUE THREAD

**Issue by dlangille** [jpmens/mqttwarn#362]
I'm opening this issue in the hopes of helping future novices.  mqttwarn 0.10.4

I was amending a functions file today and when I got the field names wrong, I got a warning:

```
2019-01-19 16:11:36,751 WARNING [mqttwarn] Cannot invoke filter function logging_filter defined in logging/hare: 'rhostname'
```

I had:

```
if data['rhostname'] ==  'foo'     and data['host'] in ['bar', ...]
```

I had copy pasted and tried to reverse the fields. This is what I needed:

```
if data['rhost'] ==  'foo'     and data['hostname'] in ['bar', ...]
```

I interpreted the message as: cannot invoke this function ... because I can't find it. But wait, ... it's right there, what's going on?

I didn't realize it was more like a syntax error or a field which mqttwarn could not access.

Yes, I see now that 'rhostname' is mentioned in the message, but that didn't help me understand that I was "doing it wrong".  I was chasing the wrong thing.

Thank you.

**Comment by jpmens** [comment]
I think I understand the confusion. Would it have helped you if the error message had been longer and had contained

`possibly a syntax error within the function`

tacked onto the end of it?

**Comment by dlangille** [comment]
It is not quite a syntax error though. It is a logical error?

`rhostname` was an invalid field.

**Comment by jpmens** [comment]
Nothing can help you find logical errors: Consider

```
a = 1
a = a + 3
```

but you wanted to add `2`... Exaggerated but I'm trying to prove a point.

**Comment by jpmens** [comment]
I suppose what we could do is to attempt to load the Python file and see what the parser returns and pass that back to the user (user in this case is the admin who is configuring mqttwarn), but I don't really think this is worthwhile doing.

Unless, of course, you feel like contributing such code. :-)

**Comment by dlangille** [comment]
For what it's worth, when I was debugging the issue, I ran `python myfile` on my functions file, and it passed. So I incorrectly concluded it was not the problem but my configuration was at stake.

The errors messages are different if it's a syntax error, which I introduced for the purposes of this reply:

```
2019-01-19 20:17:45,203 WARNING [mqttwarn] Cannot invoke filter function logging_filter defined in logging/hare: invalid syntax (my-functions.py, line 9)
```

**Comment by jpmens** [comment]
I will add a note to the documentation.
