### ISSUE TITLE
Using a function within a config section

### ISSUE THREAD

**Issue by dka2** [jpmens/mqttwarn#364]
Hello  JP,
I like MqttWarn and I make a try with last week (you have done a good job). 
I want to know if I can use code in config:xxx sections, 
actually I want to build message and/or change addresses (eg email) using my python functions.

**Comment by jpmens** [comment]
It is currently not possible to use code within the configuration. You can, however, use code while creating output formats using the, say, `alldata` functions as described in the README. These allow you to obtain message payloads, act on them, and transform before further processing.

**Comment by jpmens** [comment]
Closing as answered.
