### ISSUE TITLE
Execute using quotes

### ISSUE THREAD

**Issue by solucionescol** [jpmens/mqttwarn#367]
Hi:
I have been trying without success to use the following target 
`[config:execute]
targets = {
   'smstodos' : [ 'printf', '"it is a test first line text\nsecond line text\nHello World">/tmp/test.txt' ]
   }
`
i can run with success from command line 
`$ printf "it is a test\n0\nHello World">test.txt
$ echo $?
$ 0`

i supose it is an issue with quotes inside args, i have tried escaping quotes without success, please give me a push in right way to use it

thankyou

**Comment by jpmens** [comment]
The right way to do this is to put that in a short shell script and execute that. :)

**Comment by solucionescol** [comment]
:) it is right
Thankyou
