### ISSUE TITLE
Prompt whether I can configure mqttwarn to have constant connection to three MQTT servers?

### ISSUE THREAD

**Issue by trinetron** [jpmens/mqttwarn#371]
Hi!
Prompt whether I can configure mqttwarn to have constant connection to three MQTT servers?
If it is possible then where can I find out how to do it.

Thanks.

**Comment by jpmens** [comment]
That is not possible.

**Comment by trinetron** [comment]
Thanks

**Comment by slavino** [comment]
> Hi!
> Prompt whether I can configure mqttwarn to have constant connection to three MQTT servers?
> If it is possible then where can I find out how to do it.
> 
> Thanks.

Just write a simple consumer in preferred programming language that subscribes to all MQTT servers and publishing can be done the same way by using either of the servers. Or consider using some type of MQ (message queue) instead if you need more robust solution.
