### ISSUE TITLE
Binary payloads not supported?

### ISSUE THREAD

**Issue by nak1090** [jpmens/mqttwarn#374]
I might be missing something. Where we are converting the buffer to a utf8 string? but it seems binary payloads are not supported. 

The error I received is: **_'utf8' codec can't decode byte 0xce in position 7: invalid continuation byte'_** at def on_message

**Comment by jpmens** [comment]
I don’t think we’ve ever tried binary payloads, at least not on purpose.
Can you provide an example payload, maybe base64-encoded so it fits in here?

**Comment by amotl** [comment]
Dear @nak1090,

I would also be interested to investigate your issue and humbly ask for an example to assist that.

With kind regards,
Andreas.

**Comment by jpmens** [comment]
Closing as stale.
