### ISSUE TITLE
TLS issues with mosquitto-1.6.4

### ISSUE THREAD

**Issue by dlangille** [jpmens/mqttwarn#378]
I recently (2 days ago) upgraded from mosquitto upgraded: 1.5.8 -> 1.6.4

No configuration changes were made after the upgrade.  Both mosquitto and mqttwarn run on the same FreeBSD jail. There was a reboot of the host after the upgrade. There was no mqtt issue then.  Which makes the following all the more surprising.

I have confirmed the mosquitto cert is not expired: `Not After : Dec 22 02:19:10 2019 GMT`

```
$ openssl version
OpenSSL 1.1.1a-freebsd  20 Nov 2018
```

Today, mqttwarn refuses to connect to mosquitto:

`ERROR [mqttwarn] Cannot connect to MQTT broker at mqtt01.example.org:8883: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:727)`

I also tried sslv3, just in case, but that is not any fun either:

`[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure`

Any ideas? Are you on Mosquitto 1.6.4

Oh oh, it looks like Moquitto dropped support for tlsv1 in release 1.6 : https://mosquitto.org/blog/2019/04/version-1-6-released/

That seems to be supported by these /var/log/messages entries:

```
Oct 17 20:01:17 mqtt01 mosquitto[74183]: OpenSSL Error: error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol
Oct 17 20:01:17 mqtt01 mosquitto[74183]: Socket error on client <unknown>, disconnecting.
```

**Comment by jpmens** [comment]
@dlangille I've been away for three weeks and am still a bit woozy. Have you been able to solve this?

**Comment by dlangille** [comment]
No, I have not. I concluded `mqttwarn` needed new code to do newer TLS.

**Comment by jpmens** [comment]
That is very doubtful, as we don't "do" TLS. We use the Paho Python libraries.

**Comment by dlangille** [comment]
I am using py27-paho-mqtt-1.4.0

I might as well try Python 3.6

**Comment by dlangille** [comment]
Build failures.  I think this is why the FreeBSD port restricts mqttwarn to Python 2.7:

https://services.unixathome.org/poudriere/data/120amd64-default-master-list/2019-11-02_17h20m58s/logs/errors/py36-mqttwarn-0.10.4_1.log

**Comment by jpmens** [comment]
I don't think we yet fully support Python 3

**Comment by jpmens** [comment]
I see Paho is currently at paho-mqtt 1.5.0; do you have that for FreeBSD?

**Comment by dlangille** [comment]
Where do you see

> I don't think we yet fully support Python 3

EOL is 1 Jan.

**Comment by dlangille** [comment]
> I see Paho is currently at paho-mqtt 1.5.0; do you have that for FreeBSD?

I was just at https://www.eclipse.org/paho/downloads.php and saw only 1.4

Where are you seeing 1.5?

**Comment by jpmens** [comment]
https://pypi.org/project/paho-mqtt/

**Comment by dlangille** [comment]
I will try that later today. Thank you.

**Comment by jpmens** [comment]
Could you try configuring this in `mqttwarn.ini`?

```
tls_version = 'tlsv1_2'
```

**Comment by dlangille** [comment]
Tried.  Same issue.  Hmm.

**Comment by dlangille** [comment]
Tried again.

It worked.

**Comment by dlangille** [comment]
I conclude I didn't really try the first time.

**Comment by jpmens** [comment]
What worked? Configuring tls_version?

**Comment by dlangille** [comment]
Yes, tlsv1_2 worked.
