### ISSUE TITLE
Running on raspberryPi 4 with docker-compose

### ISSUE THREAD

**Issue by Louis-Demers** [jpmens/mqttwarn#388]
(sorry if this is trivial, i'm new at docker stuff)
Direct usage of your image/container generates the following error  since it seems configured only for x86-64.

`standard_init_linux.go:211: exec user process caused "exec format error"`

So i tried your suggestion to clone the repository locally and build an image but when i start  the container, i get the following error

`python: can't open file 'mqttwarn.py': [Errno 2] No such file or directory`

thanks for a great tool (use it without docker on other api) and for any help.

**Comment by amotl** [comment]
Dear Louis,

a few days ago, we've released mqttwarn on PyPI, so if you are running Python2 on the RaspberryPi and you are lucky, you might be able to install it using "pip install mqttwarn".

With kind regards,
Andreas.

On 28 November 2019 19:29:20 WET, Louis-Demers <notifications@github.com> wrote:
>(sorry if this is trivial, i'm new at docker stuff)
>Direct usage of your image/container generates the following error 
>since it seems configured only for x86-64.
>
>`standard_init_linux.go:211: exec user process caused "exec format
>error"`
>
>So i tried your suggestion to clone the repository locally and build an
>image but when i start  the container, i get the following error
>
>`python: can't open file 'mqttwarn.py': [Errno 2] No such file or
>directory`
>
>thanks for a great tool (use it without docker on other api) and for
>any help.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jpmens/mqttwarn/issues/388

-- 
Sent from my mind. This might have been typed on a mobile device, so please excuse my brevity.

**Comment by Louis-Demers** [comment]
Hi Andreas, i am running mqttwarn successfully on some rpi by cloning the repository and locally build/installing it without much trouble. For this new installation, I would have preferred to go through docker. If i fail, i'll go back to the manual route. I just figured that since it was available for x86-64 and that it's a python based, it would not be too difficult to target another architecture like arm.

best regards

**Comment by jpmens** [comment]
I don't think we've done anything dockery on ARM, so good luck :)
Please note that the error message you are seeing `No such file or directory` indicates that `mqttwarn.py` is missing; I assume you've noticed that.

This may be due to a problem with the `Dockerfile` ...

**Comment by Louis-Demers** [comment]
Hi jpmens, yes i noticed. mqttwarn.py is present in my local clone. During the docker build step, there are no errors (other than a warning about upcoming deprecation of python 2.7).

**Comment by jpmens** [comment]
IMO there's a bug in the Dockerfile. It now says

```
# run process
CMD python mqttwarn.py
```

but I think that ought to be

```
# run process
CMD python /opt/mqttwarn/mqttwarn.py
```

because all the files from current directory are copied into that directory.

Could you try that?

**Comment by Louis-Demers** [comment]
it's one of the numerous things i tried without success. But, finally got it working. A code 18 error... 18 inches infant of the screen. My inexperience with docker mainly. I was trying to map /opt/mqttwarn instead of the suggested /opt/mqttwarn/conf. Because I wanted to send the log files in there as well.  Coupled with the fact the the permissions were not properly set in the remapped volumes prevented the copy of the mqttwarn.py files produced the failures.

So here is my recipe to get it working for others that might be interested. Pretty much what you had proposed in your documentation....

```
git clone https://github.com/jpmens/mqttwarn.git
cd mqttwarn 
docker build -t mqttwarn-local .
cd ..
touch ./volumes/mqttwarn/mqtt.log
chmod 666 ./volumes/mqttwarn/mqtt.log

```
my docker-compose.yaml file is
```
  mqttwarn:
    image: mqttwarn-local
    container_name: mqttwarn
    volumes:
      - ./volumes/mqttwarn/conf:/opt/mqttwarn/conf
      - ./volumes/mqttwarn/:/opt/mqttwarn/log

```
and in my test mqttwarn.ini

```
targets = {
    'mylog'     : ['/opt/mqttwarn/log/mqtt.log']
    }

```
thanks for the help
