### ISSUE TITLE
Upgrade the service plugin for connecting to Azure IoT ("iothub")

### ISSUE THREAD

**Issue by amotl** [jpmens/mqttwarn#391]
The `iothub` service plugin is currently defunct as `iothub-client==1.1.2.0` is deprecated. This plugin should probably be renamed to `azure-iot` and based on the _Azure IoT SDKs for Python_ available from https://pypi.org/project/azure/.

**Comment by mortenf** [comment]
I will look into this over the coming weeks.

**Comment by amotl** [comment]
Thanks to @mortenf, we can close this issue.
