### ISSUE TITLE
"mqttwarn make-config" croaks with UnicodeEncodeError on Python 2

### ISSUE THREAD

**Issue by Gulaschcowboy** [jpmens/mqttwarn#393]
Invoking `mqttwarn make-config > mqttwarn.ini` croaks under Python2:
```
Traceback (most recent call last):
  File "/usr/local/bin/mqttwarn", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/mqttwarn/commands.py", line 50, in run
    print(payload)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 2731: ordinal not in range(128)
```

**Comment by amotl** [comment]
Thanks for reporting!

**Comment by amotl** [comment]
We are probably running into [Overcoming frustration: Correctly using unicode in python2 » Frustration #3: Inconsistent treatment of output](https://pythonhosted.org/kitchen/unicode-frustrations.html#frustration-3-inconsistent-treatment-of-output) here.

> The C locale doesn’t understand any characters outside of ASCII so naturally attempting to display those won’t work. Now why does redirecting to a file cause problems? It’s because print() in python2 is treated specially.

> Whereas the other file-like objects in python always convert to ASCII unless you set them up differently, using print() to output to the terminal will use the user’s locale to convert before sending the output to the terminal. When print() is not outputting to the terminal (being redirected to a file, for instance), print() decides that it doesn’t know what locale to use for that file and so it tries to convert to ASCII instead.
