### ISSUE TITLE
from mqtt to zabbix from JSON format.

### ISSUE THREAD

**Issue by catfish34** [jpmens/mqttwarn#394]
I have device with tasmota firmware https://github.com/arendst/Tasmota.
It sent  JSON kind of messages in MQTT:
`tele/sonoff_shalb_boiler/SENSOR: {"Time":"2020-01-09T00:46:37","DS18B20-1":{"Id":"0114381D3AAA","Temperature":47.8},"DS18B20-2":{"Id":"0213265F7CAA","Temperature":56.8},"TempUnit":"C"}`

Is it possible to send "Temperature":47.8 and "Temperature":56.8 to zabbix?

As I understand from documentation mqttwarn can parse only non JSON messages like:
tele/sonoff_shalb_boiler/Temperature: 47.8
tele/sonoff_shalb_boiler/Temperature: 56.8

**Comment by jpmens** [comment]
Please reread the documentation: mqttwarn parses JSON
