### ISSUE TITLE
format: 'Config' object has no attribute 'datamap'

### ISSUE THREAD

**Issue by clarkspark** [jpmens/mqttwarn#399]
When trying to use 
```
format = usage()
```
 with a trivial usage() function I get the following message:
```
WARNING [core] Cannot invoke usage(): 'Config' object has no attribute 'datamap'
```
The published message ends up being 'usage()'.  Using a format string (as in format = {value}) works as expected.

I am attempting to transition from a late (late) 2019 mqttwarn github installation to one through pypi (0.13.8).

**Comment by amotl** [comment]
Dear @clarkspark,

thanks for reporting this. I haven't been aware that the "format" setting also can invoke user-defined functions. The new "datamap", "alldata" and "filter" settings are usually used for this these days. However, I tried my best to fix this issue through 3224ad61 within mqttwarn 0.13.9. 

With kind regards,
Andreas.

**Comment by clarkspark** [comment]
Can datamap only be invoked a such:
```
...
datamap = datamap_function()
...

functions.py
...
def datamap_function(topic):
```

or can the 'data' object also be accessed in it?

Thanks,
Ryan

**Comment by amotl** [comment]
I believe the "alldata" function is also accepting the transformation data dictionary.

**Comment by clarkspark** [comment]
Ok, I'll look at that reference and test your change in 0.13.9 and let you know.  

Thanks,
Ryan

**Comment by clarkspark** [comment]
Your change did the job, again allowing functions in the format stanza.

Thanks,
Ryan

**Comment by amotl** [comment]
Dear Ryan,

thanks for your feedback and thanks again for your contribution from #398.

With kind regards,
Andreas.
