### ISSUE TITLE
Extend list of notification plugins by integrating "Apprise"

### ISSUE THREAD

**Issue by amotl** [jpmens/mqttwarn#400]
Hi there,

@clarkspark just shared a list of Python implementations for XMPP within https://github.com/xmpppy/xmpppy/issues/29#issuecomment-600344126. Thanks! Within his curated list [xmpp_libs.xlsx](https://github.com/xmpppy/xmpppy/files/4346179/xmpp_libs.xlsx), I discovered [Apprise](https://github.com/caronc/apprise).

Now, I am asking myself if it would be nice to have this machinery available from [`mqttwarn`](https://github.com/jpmens/mqttwarn) to extend the plethora of notification plugins even further.

With kind regards,
Andreas.

[1] https://github.com/caronc/apprise/tree/master/apprise/plugins

**Comment by amotl** [comment]
I have added a service plugin for invoking Apprise, see 6fb7b807. The documentation can be found at [1]. Please let me know if you see any problems with the current implementation.

[1] https://github.com/jpmens/mqttwarn/blob/master/HANDBOOK.md#apprise

---

cc @clarkspark, @jpmens, @ckrey

**Comment by clarkspark** [comment]
Andreas,
Is the expectation that a user would know the details defined in DNS records (SRV records, etc)?  Or is the expectation that mqttwarn would be able to query this information itself to determine an address for a service?

**Comment by amotl** [comment]
Dear Ryan,

I don't know much about XMPP DNS interaction. Anything about that should not be of concern to mqttwarn, right?

While I acknowledge we are coming from getting appropriate support for XMPP here, this specific issue is about bringing Apprise to `mqttwarn` and I was about to close the issue as I believe it has been implemented well and nobody objected.

If you have specific requirements what should be added to mqttwarn for communicating with XMPP through Apprise, please open a different issue.

With kind regards,
Andreas.

**Comment by clarkspark** [comment]
Andreas,
Sorry I was not clearer.  The [earlier comment](https://github.com/jpmens/mqttwarn/issues/400#issuecomment-600766823) was in reference to trying to replicate the apprise-email and apprise-json services.

I was trying to verify that mqttwarn is not expected to look up an email server defined in a DNS SRV record.  Instead it is up to the user to know that the mail server for example.com is located at (for example) smtp.example.com.

Sorry for the confusion,
Ryan

**Comment by amotl** [comment]
The question from Ryan has been nswered within #402.
