### ISSUE TITLE
Using the Apprise service plugin for XMPP notifications

### ISSUE THREAD

**Issue by amotl** [jpmens/mqttwarn#401]
Together with @clarkspark, we are looking at alternatives to the current XMPP service based on `xmpppy`, see #295. With #400, that would be possible using [Apprise](https://github.com/caronc/apprise) and its [Notify_xmpp](https://github.com/caronc/apprise/wiki/Notify_xmpp) plugin.

**Comment by amotl** [comment]
@clarkspark asked:

> Is the expectation that a user would know the details defined in DNS records (SRV records, etc)? Or is the expectation that _mqttwarn_ would be able to query this information itself to determine an address for a service?

**Comment by amotl** [comment]
Dear Ryan,

I don't know much about XMPP DNS interaction. Anything about that should not be of concern to mqttwarn, right?

If you have specific requirements what should be added to _mqttwarn_ for communicating with XMPP through Apprise, please let me know. I will be happy about any guidance.

With kind regards,
Andreas.

**Comment by amotl** [comment]
6fb7b807 shows how to use Apprise for sending notifications using SMTP and HTTP. After @caronc fixed the XMPP plugin of Apprise, we also want to add a respective example how to use XMPP.

**Comment by clarkspark** [comment]
Andreas,
If I think I am using the most recent versions of relevant software and am having trouble trying to add a respective apprise-xmpp example should I detail it here or open a new issue?

Thanks,
Ryan

**Comment by amotl** [comment]
Dear Ryan,

I believe you are currently not using the Apprise service at all, but instead you are going the native way using the mqttwarn XMPP plugin?

If you are trying to use mqttwarn -> Apprise -> XMPP instead, this issue is the appropriate one, right! When we might find the issue is related to Apprise, we might well want to divert it to [1].

Cheers,
Andreas.

[1] https://github.com/caronc/apprise

**Comment by clarkspark** [comment]
Andreas,
I do use the native xmpp service and that is now working correctly.  My last post was unrelated to the native xmpp mqttwarn service.

I was trying to contribute to mqttwarn by verifying that mqttwarn's use of apprise to send messages through xmpp was working and then I was going to submit a pull request adding it to the example .ini, as your post seemed to imply that it should work.  I ran into issues while trying to verify I could deliver a message through apprise-xmpp.  The issues all appeared to be due to connecting to a TLS XMPP server, so I will open an issue at [1].

But there is a potential issue with the apprise mqttwarn implementation that was seen.  Should I open a new issue for it, or continue on this thread?

Thanks,
Ryan

[1] https://github.com/caronc/apprise

**Comment by amotl** [comment]
Dear Ryan,

thanks for looking at and improving the Apprise/XMPP thing here. There well have been issues with Apprise/XMPP and @caronc and me have been working on it, see https://github.com/caronc/apprise/issues/213, https://github.com/caronc/apprise/issues/217 and https://github.com/caronc/apprise/issues/220. So, we should wait for @caronc putting out a new release of Apprise which includes these updates and then bump its version from 0.8.4 to the next one before continuing further investigations.

With kind regards,
Andreas.

**Comment by clarkspark** [comment]
Andreas,
I was following those efforts and I thought that it was tentatively fixed.  I installed his updates through pip (pulling apprise directly from github), so I thought I had the most up-to-date versions.  But I will wait a bit and try it again.

One thing I did notice (just as a heads-up to you) is that when the mqtt apprise service is unable to deliver a message to a TLS XMPP server it doesn't seem to ever stop trying.  This leads mqttwarn to no longer respond to a ctrl-c keystroke from the command line.  Eventually mqttwarn dies with sleekxmpp giving a:
```
IndexError: list index out of range
```

Not that mqttwarn should have to work around issues in related libraries, but just letting you know.

Thanks,
Ryan

**Comment by caronc** [comment]
@amotl Would you have time to just check out the Apprise master branch and confirm everything is still working (with regards to XMPP)? I can try to push a major release today (0.8.5) of it if we're good.

**Comment by amotl** [comment]
I've just released mqttwarn 0.14.2 including an upgrade to the freshly minted apprise 0.8.5. Invoking apprise within this virtualenv using
```
apprise --body='☠☠☠ hello world ☠☠☠' 'xmpps://user:pass@jabber.ccc.de?to=another-user@jabber.ccc.de&verify=no' -v
```
worked like a charm.

Thank you so much for all the work you have been putting into this!

**Comment by clarkspark** [comment]
@amotl,
Using apprise 0.8.5 from the command line using your command as an guide it does not work for me.  But as it's not due to mqttwarn, I'll open an issue at the apprise repo.

Thanks,
Ryan

**Comment by amotl** [comment]
> I'll open an issue at the apprise repo.

Thanks! You might want to add `-vvvvv` to get additional information about why things went south.

**Comment by clarkspark** [comment]
Thanks for the tip.  I tried it with 2 v's and it didn't add more output so I thought that trick wouldn't work.

**Comment by clarkspark** [comment]
Andreas,
I think maybe you can close this issue as you have found that xmpp through apprise works for you.  

If I end up finding an issue with mqttwarn's use of the apprise-xmpp service I will create a new issue and reference this issue.

Thanks,
Ryan

**Comment by clach04** [comment]
@amotl hopefully a quick question for you; what's your current Apprise/mqttwarn setup?

I don't believe this is working under Python3, I was able to get apprise-telegram working under Python2 only. I opened #456

**Comment by amotl** [comment]
Hi again,

@caronc had to remove XMPP support from Apprise.

- https://github.com/caronc/apprise/pull/619

However, @clarkspark confirmed that the vanilla XMPP service plugin, based on [xmpppy], worked for him, see https://github.com/jpmens/mqttwarn/issues/403#issuecomment-605504107.

So, I think it will be safe to close this issue. Please let us know if you think differently.

With kind regards,
Andreas.

[xmpppy]: https://github.com/xmpppy/xmpppy
