### ISSUE TITLE
SMTP service configuration

### ISSUE THREAD

**Issue by amotl** [jpmens/mqttwarn#402]
@clarkspark just asked:

> [When trying to notify users by SMTP], I was trying to verify that mqttwarn is not expected to look up an email server defined in a DNS SRV record. Instead it is up to the user to know that the mail server for example.com is located at (for example) smtp.example.com.

**Comment by amotl** [comment]
Dear @clarkspark,

mqttwarn will not perform any MX lookup and will behave like any other application software based on SMTP actually should do: You want to make it deliver the mail to a smart host where you have the permission to relay emails over.

This usually works by using SMTP authentication, but you will also be able to configure your SMTP server to accept relaying mails by whitelisting the IP address of the sender.

So, you actually want to configure it to submit emails to `username:password@mail.acme.net`. There is no need to do the MX lookup of the receiver domain within your program. You will just use the smart host to submit any kind of mail and the MTA will sort things out.

With kind regards,
Andreas.

**Comment by clarkspark** [comment]
Ok, Thanks.
