### ISSUE TITLE
XMPP plugin croaks with "[Errno 101] Network is unreachable" after a few successful messages

### ISSUE THREAD

**Issue by amotl** [jpmens/mqttwarn#403]
## Introduction
Coming from #295, @clarkspark experienced errors when using the updated XMPP plugin.

## Observation
> The issue happens after multiple successful messages being sent, sometimes a few sometimes maybe 5-10. Then it throws the Errno 101.
```
DEBUG: socket       start Plugging <xmpp.transports.TCPsocket instance at 0x7fb5cbdcc820> into <xmpp.client.Client instance at 0x7fb5cbdccb40>
DEBUG: socket       warn  An error occurred while looking up _xmpp-client._tcp.example.com
DEBUG: socket       error Failed to connect to remote host (u'example.com', 5222): Network is unreachable (101)
Traceback (most recent call last):
  File "/srv/mqttwarn/.venv2/local/lib/python2.7/site-packages/xmpp/transports.py", line 159, in connect
    self._sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 101] Network is unreachable
```

## Thoughts
> Since it seems to die on the SRV DNS record lookup it could potentially be an issue with the related `pydns` package which is required by `xmpppy` in cases where the server uses a SRV record. I could try to enable debug in that package and see if it reveals anything.

**Comment by clarkspark** [comment]
Andreas,
    I switched from pydns to dnspython through pip in a python2 virtual environment:
```
pip uninstall pydns
pip install dnspython
```
 and the XMPP service is now stable.  It does output the following text to the terminal for each XMPP message though:
```
('type:', <type 'str'>)
('type:', <type 'str'>)
('type:', <type 'str'>)
('type:', <type 'str'>)
('type:', <type 'str'>)
('type:', <class 'xmpp.protocol.Protocol'>)
('type:', <class 'xmpp.protocol.Protocol'>)
('type:', <class 'xmpp.protocol.Message'>)
```
Not sure where it is coming from and it does not effect the successful functioning of the XMPP service, just more as an FYI.

I tried adding 'dnspython==1.16.0' in the xmpp section of the setup.py file thinking that dnspython would be installed upon:
```
pip install mqttwarn[xmpp]
```
but that does not seem to happen.  Is it possible to have dnspython installed when the above is run?

Otherwise this issue is resolved.

Thanks,
Ryan

**Comment by amotl** [comment]
Dear @clarkspark,

we just released mqttwarn 0.14.1 which hopefully addresses both issues. Please try `pip install mqttwarn[xmpp] --upgrade`. Thanks again for your feedback!

With kind regards,
Andreas.

**Comment by clarkspark** [comment]
Andreas,
Works great.  Thanks for all your super effort getting the XMPP service working again.

Ryan

**Comment by amotl** [comment]
Appreciate it. Thanks also for kicking this all off and have fun!
