### ISSUE TITLE
Query mqttwarn directly

### ISSUE THREAD

**Issue by robdejonge** [jpmens/mqttwarn#406]
I've searched through the Wiki, but have not found any evidence that this is possible. Can I somehow query mqttwarn (via MQTT, or otherwise) as to its current service status and perhaps the version that is running?

I currently [run it using Supervisor](https://jpmens.net/2014/02/13/in-my-toolbox-supervisord/), and so I use a generalized version of the included script to check status. But it's likely I'll move away from supervisor and would prefer a more direct method of status checking.

**Comment by jpmens** [comment]
That is not currently possible, though likely not difficult to implement via MQTT: a special topic mqttwarn listens on and another on which it provides the response.

**Comment by mortenf** [comment]
Using the mqttpub service module and a custom function, it is possible as is.

mqttwarn.ini (relevant parts):
```ini
functions = 'samplefuncs'
launch = file, log, mqttpub

[config:mqttpub]
targets = {
    'version' : [ 'service/mqttwarn/status/version', 0, True ]
  }

[service/mqttwarn/command/version]
targets = mqttpub:version
alldata = AllDataAddVersion()
format = {payload} mqttwarn v{version}
```

New function in samplefuncs.py:
```Python
def AllDataAddVersion(topic, data, srv=None):
    try:
        from mqttwarn import __version__
    finally:
        return dict(version=__version__)
```

Now, when publishing "test" to the topic `service/mqttwarn/command/version`, mqttwarn will respond on `service/mqttwarn/status/version` with "test mqttwarn v0.16.0".

**Comment by robdejonge** [comment]
Thanks for writing that up, @mortenf. It's a great idea to implement it this way!
