### ISSUE TITLE
SIP plugin

### ISSUE THREAD

**Issue by amotl** [jpmens/mqttwarn#407]
@terasolu suggested a SIP plugin for mqttwarn within #405: 

> I don't know what the current development capacity is and what the feasibility of it is, but I noticed that there is no plugin for SIP yet. It would be quite handy if you could work with SIP, after all SIP is used almost everywhere.
>
> There would also be no need to connect via RTP, just the invite-message would be sufficient for most cases. Currently, as far as I understood, you need Asterisk to connect both. Just as a suggestion on my part.

Here, we can discuss whether that would make any sense and how it might be implemented.

**Comment by amotl** [comment]
@jpmens commented:

> What would a SIP plugin for mqttwarn do, in your opinion? What is the use case?

**Comment by terasolu** [comment]
I see the advantage of a SIP plugin in the application like the XBMC plugin. For example, if a doorbell is pressed and sends a MQTT packet, it "routes" it to a PBX. There would be the possibility to integrate telephone systems more easily, because Asterisk is not used everywhere. SIP is also the protocol of choice for IP telephony.

**Comment by jpmens** [comment]
And what do you envision the PBX doing? Should it dial a number? Speak the payload? Please give examples of what you think this "integration" should be capable of.

**Comment by terasolu** [comment]
To get a voice output you would also have to establish an RTP connection first. I don't think this is the job of mqttwarn, voice output is a more complex issue anyway.
I think the call setup is sufficient. This is already used for doorbell systems without microphone. Via SIP a "request" is sent, the phone rings, but if it is accepted, no call can be established.
On many phones, a description can still be shown on the display, which is provided by SIP. This could be used to display the payload.
At the following link I found a project which notifies the pressing of a doorbell via SIP exactly as described:
https://wernze-home.net/wordpress/hobbys/arduino-esp8266-tuerklingel/

**Comment by jpmens** [comment]
I don't think this is something many people would use, but if you want to contribute such a plugin and its documentation, feel free to. 

I will close this issue until then.

**Comment by amotl** [comment]
Just in case someone would want to revisit this. I found these implementations for Python:
- https://github.com/AGProjects/python-sipsimple
- https://github.com/babytut/python-sip-example
