### ISSUE TITLE
Thingspeak data has big gaps

### ISSUE THREAD

**Issue by terasolu** [jpmens/mqttwarn#409]
I have set up the Thingspeak plugin at my place and it works so far. But with Thingspeak the values do not appear in the predefined intervals, but in arbitrary intervals. Sometimes the values are completely missing for hours. Has anyone ever had this problem?

**Comment by amotl** [comment]
Dear @terasolu,

while I have no experience with ThingSpeak whatsoever, I can warmly recommend [Kotori](https://github.com/daq-tools/kotori). It integrates well with [MQTT](http://mqtt.org/), [InfluxDB](https://github.com/influxdata/influxdb) and [Grafana](https://github.com/grafana/grafana) and if you are not too shy to ramp it up - and of course depending on your requirements, it will give you much pleasure in data acquisition and visualization.

In case you are interested, you might enjoy having a look at [swarm.hiveeyes.org](https://swarm.hiveeyes.org/) and [weather.hiveeyes.org](https://weather.hiveeyes.org/), which are partly driven by Kotori.

Disclaimer: I am the main author of Kotori ;].

Cheers,
Andreas.

**Comment by terasolu** [comment]
@amotl Sorry for the delay in my answer. That looks absolutely incredible! I would love to set that up one day, but at the moment I do not think that I have the competence to do this.

Meanwhile I found out that the problem maybe is from the mqttwarn.core. Sometimes it throws out a warning

"Cannot decode JSON object, payload=22.25: 'float' object is not iterable"
or
"Cannot decode JSON object, payload=0: 'int' object is not iterable".

How is this data type defined and why is it sometimes working and sometimes not?

**Comment by amotl** [comment]
Dear @terasolu,

this is a warning mqttwarn used to spit out which is somehow confusing. @mortenf removed it through #420: 

> Plain text (and other formats) payloads should be OK and not generate a warning.

So, despite this misleading warning, everything should have worked as expected.

With kind regards,
Andreas.

**Comment by terasolu** [comment]
Oh, okay. Thank you very much. I think it's probably the thingspeak plugin which can not deal with plain text, too. I will look for an alternative.

**Comment by amotl** [comment]
Dear @terasolu,

I am currently looking at the configuration of the Thingspeak plugin [1] as well as its source code [2]. The configuration snippet looks like
```
[config:thingspeak]
targets = {
                   #API WRITE KEY       field      optional builddata=true/false
    'field1'   : [ 'XXYYZZXXYYZZXXYY', 'field1' , 'true' ],
    'field2'   : [ 'XXYYZZXXYYZZXXYY', 'field2' ],
    'composite': [ 'XXYYZZXXYYZZXXYY', [ 'temp', 'hum' ] ]
  }
```

When `builddata=true` is configured, the plugin will suspend sending the data to the upstream service. Instead, it will aggregate all data until it gets a signal to a field **not** having `builddata=true`. After that, it will submit all aggregated data.

May I humbly ask you to check or share your configuration? Maybe this is the culprit why you are experiencing data loss?

With kind regards,
Andreas.

[1] https://github.com/jpmens/mqttwarn/blob/master/HANDBOOK.md#thingspeak
[2] https://github.com/jpmens/mqttwarn/blob/0.16.1/mqttwarn/services/thingspeak.py

**Comment by terasolu** [comment]
I guess the problem is that Thingspeak doesn't allow to publish more than one time in 15 seconds. To make it work one can publish multiple fields as JSON.

@amotl Thanks again for your help!
