### ISSUE TITLE
Update Dockerfile for Python 3

### ISSUE THREAD

**Issue by volschin** [jpmens/mqttwarn#416]
Python 2.7 is retired. So Dockerfile should be updated to use Python 3 instead.

**Comment by amotl** [comment]
That's true. Thanks for the heads up, @volschin. I will try to find some time to care about this detail. Otherwise, we are also happy to accept pull requests into that direction.

**Comment by amotl** [comment]
Python 3 support within Docker will be arriving through #423, thanks to @koenvervloesem!
