### ISSUE TITLE
Docker image rgitzel/mqttwarn additional python functions not working

### ISSUE THREAD

**Issue by lenny1972** [jpmens/mqttwarn#419]
Hi to everybody, 

first of all I want to thank @rgitzel for the usefull  and really complete image for mqttwarn. I need to use mqttwarn functionalities in order to feed a carbon (whisper) db from messages subscribed on a mqtt broker for my project.

I've included rgitzel image mqttwarn-full as a service within a docker-compose file in order to be used to build up my solution.

The `docker-compose.yml` file part (regarding your image) is the following:

```
  mqttwarn-full:
    container_name: mqttwarn
    restart: always
    image: rgitzel/mqttwarn-full
    volumes:
      - '/opt/mqttwarn/conf:/opt/mqttwarn/conf'
      - '/opt/mqttwarn/log/mqttwarn.log:/opt/mqttwarn/mqttwarn.log'
      - '/opt/mqttwarn/functions:/opt/mqttwarn/functions'
    environment:
      USER_ID: '998'    # UID of the docker_user I've created to run the container
      GROUP_ID: '997'   # GID of the docker_user I've created to run the container 
```

I've so create the `mqttwarn.ini` file within the host folder `/opt/mqttwarn/conf` and put a custom python function called `my_carbon.py` within the host folder  `/opt/mqttwarn/functions`. Note: I've also set the permission on that folders (and on all the files within it) to the docker_user accordingly to what I've defined within the environment variables section of the `docker-compose.yml` above (UID:998 and GID:997).

As suggested I've include in the mqttwarn.ini file above the name of my custom python function.
Below the part of the `mqttwarn.ini` file (in bold the integration I've made in order to be able to use the new python function).

```
; path to file containing self-defined functions for formatmap and datamap
#functions = 'samplefuncs.py'
functions = 'functions/my_carbon.py'
; name the service providers you will be using.
launch  = file, log, carbon, my_carbon

[config:my_carbon]
targets = {
        'c1' : [ 'graphite_statsd', 2003 ],
  }

[APA0/iIPdubgSRi/#]
targets = my_carbon:c1, log:debug, log:error
```

When I ran the docker-compose I get the following error in the log of mqttwarn:

```
2020-05-03 13:25:06,211 INFO  [mqttwarn] Starting mqttwarn
2020-05-03 13:25:06,211 INFO  [mqttwarn] Log level is DEBUG
2020-05-03 13:25:06,216 DEBUG [mqttwarn] Service file loaded
2020-05-03 13:25:06,217 DEBUG [mqttwarn] Service log loaded
2020-05-03 13:25:06,218 DEBUG [mqttwarn] Service carbon loaded
2020-05-03 13:25:06,218 ERROR [mqttwarn] Can't load my_carbon service (services/my_carbon.py): [Errno 2] No such file or directory: u'services/my_carbon.py'
```

It seems to me that the `mqttwarn.py` process is searching for the `my_carbon.py` function file within the default python function folder (that is called services and that is within the container)  
instead of searching it within the functions folder that I've crated in the host system and where I've put the `my_carbon.py` file. 

I'm also sure that the bind mount of the volume I've defined within the `docker-compose.yml` file with the command below:

```
- '/opt/mqttwarn/functions:/opt/mqttwarn/functions'
```

I'm sure is working correctly because I can "see" the content of this folder either from the container (entering with exec command) and from the host system..

I'm literally going crazy in order to understand how can I solve it...
Can someone please help me in some way?

Thanks a lot in advanced for any help you should give me!!

Leonardo

**Comment by amotl** [comment]
Dear @lenny1972,

I've deliberately decided to copy over your comment from #341 into this issue in order not to clutter the other issue.

---

Thanks @koenvervloesem for your `docker-compose.yml` file from https://github.com/jpmens/mqttwarn/issues/341#issuecomment-623601234.

I've copied your configuration on my `docker-compose.yml` file but in the
`mqttwarn.log` file I always get the same error (for what I've opened the
issue).

The only one modification to your snippet is the change of the host folder
location. This is my `docker-compose.yml` section regarding mqttwarn service:

```
mqttwarn-full:
  container_name: mqttwarn
  restart: always
  image: rgitzel/mqttwarn-full
  volumes:
    - '/etc/localtime:/etc/localtime:ro'
    - '/opt/mqttwarn/conf:/opt/mqttwarn/conf/'
    - '/opt/mqttwarn/log/mqttwarn.log:/opt/mqttwarn/mqttwarn.log'
```

And that's the part of the `mqttwarn.ini` file where I've defined my custom
function path (my function is called my_carbon.py) as per your suggestion
```
functions = '/opt/mqttwarn/conf/my_carbon.py'
```

So I've saved in my host at location `/opt/mqttwarn/conf` folder my function
`my_carbon.py` (below a screenshot of the host folder containing both the
`mqttwarn.ini` file and my custom function)

But when I run the docker compose file it ends up with this error:
```
2020-05-05 08:49:49,232 INFO  [mqttwarn] Starting mqttwarn
2020-05-05 08:49:49,232 INFO  [mqttwarn] Log level is DEBUG
2020-05-05 08:49:49,235 DEBUG [mqttwarn] Service file loaded
2020-05-05 08:49:49,236 DEBUG [mqttwarn] Service log loaded
2020-05-05 08:49:49,237 DEBUG [mqttwarn] Service carbon loaded
2020-05-05 08:49:49,237 ERROR [mqttwarn] Can't load my_carbon service
(services/my_carbon.py): [Errno 2] No such file or directory:
u'services/my_carbon.py'
```

It seems that the main process (`mqttwarn.py`) is still searching for
the custom function file in the default directory (services) and not
in the path I've defined in the mqttwarn.ini configuration file
(`/opt/mqttwarn/conf/my_carbon.py`).

Can you please help me in understand?

Which docker image are you using?

Thanks in advance,
Leonardo

**Comment by amotl** [comment]
@koenvervloesem answered:

> @lenny1972 I used the official `jpmens/mqttwarn` image.

**Comment by amotl** [comment]
Dear @lenny1972,

does referencing the function file using an absolute path help, like outlined within [1]?

With kind regards,
Andreas.

[1] https://github.com/jpmens/mqttwarn/issues/341#issuecomment-623790444

**Comment by lenny1972** [comment]
@amotl ,
unfortunately it didn't solve the issue. I've always used the full path but the error remain the same. I'll try to go indeep in the next days.I'll let you know

**Comment by koenvervloesem** [comment]
@lenny1972 I have documented this in a `docker-compose.yml` file: https://github.com/jpmens/mqttwarn/blob/master/docker-compose.yml

Have you tried this? Note that this uses `jpmens/mqttwarn`and not `rgitzel/mqttwarn`.

**Comment by lenny1972** [comment]
Hi Koen,
I've followed your detailed instructions but when I try to run  the
mqttwarn container it throws me the following error:

python: can't open file 'mqttwarn.py': [Errno 2] No such file or directory

I've copied in the docker compose file following exactly the example of
your docker compose (except for the UID/GID with which I run the container
and the path/to/mqttwarn location in my host). I've also tried to not
declare the UID/GID for running the container but I always receive the same
error.

It seems that the container didn't find the mqttwarn.py file...It sound
really strange to me :(:(

p.s.:before running the jpmens/mqttwarn official image I removed the
rgitzel/mqttwarn to be sure

Hope someone can help me

Leonardo


Il giorno mer 6 mag 2020 alle ore 20:10 Koen Vervloesem <
notifications@github.com> ha scritto:

**Comment by koenvervloesem** [comment]
Oh right, it seems @jpmens still has to update the official `jpmens/mqttwarn` image on Docker Hub. For now you can just build the Docker image yourself with:

```
git clone https://github.com/jpmens/mqttwarn
cd mqttwarn
docker build -t mqttwarn .
```

And then use `mqttwarn` instead of `jpmens/mqttwarn` in your Docker Compose file.

**Comment by jpmens** [comment]
Apologies, and thanks for reminding me, @koenvervloesem. I have pushed `0.15.1-1` to the hub.

**Comment by lenny1972** [comment]
Thanks JP for deploying the new image.
Unfortunately I'm still facing the same issue even with a slightly
different error message.
Below the docker-compose file part regarding the mqttwarn service:

  mqttwarn:
    container_name: mqttwarn
    restart: always
    image: jpmens/mqttwarn
    links:
      - mosquitto
      - graphite_statsd
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/opt/mqttwarn:/etc/mqttwarn'


Here below, instead, the part of the mqttwarn.ini file where I've declared
the function path

; --------
; Services
; --------

; path to file containing self-defined functions for formatmap and datamap
functions = '/etc/mqttwarn/my_carbon.py'


and below the error I get from the container log:


2020-05-11 08:37:17,148 INFO     [mqttwarn.commands        ] Starting
mqttwarn,
2020-05-11 08:37:17,149 INFO     [mqttwarn.commands        ] Log level is
DEBUG,
2020-05-11 08:37:17,150 INFO     [mqttwarn.core            ] Successfully
loaded service "file",
2020-05-11 08:37:17,151 INFO     [mqttwarn.core            ] Successfully
loaded service "log",
2020-05-11 08:37:17,151 ERROR    [mqttwarn.core            ] Unable to load
service "my_carbon" from file
"/usr/local/lib/python3.8/site-packages/mqttwarn/services/my_carbon.py":
[Errno 2] No such file or directory:
'/usr/local/lib/python3.8/site-packages/mqttwarn/services/my_carbon.py',
Traceback (most recent call last):,
    service_plugins[service]['module'] = load_module(modulefile),
  File "/usr/local/lib/python3.8/site-packages/mqttwarn/core.py", line 534,
in load_services,
  File "/usr/local/lib/python3.8/site-packages/mqttwarn/util.py", line 157,
in load_module,
    fp = open(path, 'rb'),
FileNotFoundError: [Errno 2] No such file or directory:
'/usr/local/lib/python3.8/site-packages/mqttwarn/services/my_carbon.py',
2020-05-11 08:37:17,153 DEBUG    [mqttwarn.core            ] Attempting
connection to MQTT broker mosquitto:1883...,
2020-05-11 08:37:17,153 DEBUG    [mqttwarn.core            ] Setting LWT to
clients/mqttwarn...,
2020-05-11 08:37:17,159 INFO     [mqttwarn.core            ] Starting 1
worker threads,
2020-05-11 08:37:17,160 DEBUG    [mqttwarn.core            ] Job queue has
0 items to process,
2020-05-11 08:37:17,160 DEBUG    [mqttwarn.core            ] Connected to
MQTT broker, subscribing to topics...


It seems that the custom functions path it's not take into consideration by
the mqttwrn core process. It searches for the my_carbon.py service file
from /usr/local/lib/python3.8/site-packages/mqttwarn/services/ instead of
searching for it in the path I've specified in the mqttwarn.ini file (that
is /etc/mqttwarn/ ).

In the attached picture the bash that I see from within the running
container (where you can see my custom function - my_carbon.py - that is in
the same location of the mqttwarn.ini file).
I really cannot undesrstand where I fail.....
:(

Il giorno dom 10 mag 2020 alle ore 18:14 JP Mens <notifications@github.com>
ha scritto:

**Comment by koenvervloesem** [comment]
And what if you build the Docker image yourself like in https://github.com/jpmens/mqttwarn/issues/419#issuecomment-626341093?

**Comment by lenny1972** [comment]
I'll give it a try in the afternoon and let you know.
Thanks Koen

Il giorno lun 11 mag 2020 alle ore 09:49 Koen Vervloesem <
notifications@github.com> ha scritto:

**Comment by lenny1972** [comment]
I've just checked by building the image (following your suggestion).
Always the same error (see below):

2020-05-11 08:37:17,148 INFO     [mqttwarn.commands        ] Starting
mqttwarn,
2020-05-11 08:37:17,149 INFO     [mqttwarn.commands        ] Log level is
DEBUG,
2020-05-11 08:37:17,150 INFO     [mqttwarn.core            ] Successfully
loaded service "file",
2020-05-11 08:37:17,151 INFO     [mqttwarn.core            ] Successfully
loaded service "log",
2020-05-11 08:37:17,151 ERROR    [mqttwarn.core            ] Unable to load
service "my_carbon" from file
"/usr/local/lib/python3.8/site-packages/mqttwarn/services/my_carbon.py":
[Errno 2] No such file or directory:
'/usr/local/lib/python3.8/site-packages/mqttwarn/services/my_carbon.py',
Traceback (most recent call last):,
    service_plugins[service]['module'] = load_module(modulefile),
  File "/usr/local/lib/python3.8/site-packages/mqttwarn/core.py", line 534,
in load_services,
  File "/usr/local/lib/python3.8/site-packages/mqttwarn/util.py", line 157,
in load_module,
    fp = open(path, 'rb'),
FileNotFoundError: [Errno 2] No such file or directory:
'/usr/local/lib/python3.8/site-packages/mqttwarn/services/my_carbon.py',


It is still searching for the custom function within the wrong path. What
about trying to expose the default path on the host? What do you think
about it?





Il giorno lun 11 mag 2020 alle ore 10:44 Leonardo <grisusca@gmail.com> ha
scritto:

**Comment by koenvervloesem** [comment]
I repeated the same process now on another machine that never had the mqttwarn Docker image installed, and this just worked. So I guess this is some old image or volume still hanging around on your host? Do you get a warning when you do a `docker-compose up -d`?

**Comment by lenny1972** [comment]
Hi Koen,
I've run the *docker-compose up -d* and got no errors. Below the output of
the command:

root@lenny1972-Gemini-X45:/opt/portainer/data/compose/2# docker-compose up
-d
Creating nginx      ... done
Creating certbot    ... done
Creating influxdb   ... done
Creating postgreSQL ... done
Creating graphite   ... done
Creating mosquitto  ... done
Creating pgadmin4   ... done
Creating grafana    ... done
Creating chronograf         ... done
*Creating mqttwarn           ... done*
Creating node-red_dashboard ... done

all the containers are created and run with no problem.

The core mqttwarn  process is still unable to find the custom functions.
The error in the log file is still the same and it's really straightforward:

2020-05-11 21:06:54,607 INFO     [mqttwarn.commands        ] Starting
mqttwarn,
2020-05-11 21:06:54,607 INFO     [mqttwarn.commands        ] Log level is
DEBUG,
2020-05-11 21:06:54,609 INFO     [mqttwarn.core            ] Successfully
loaded service "file",
2020-05-11 21:06:54,620 DEBUG    [mqttwarn.core            ] Connected to
MQTT broker, subscribing to topics...,
2020-05-11 21:06:54,609 INFO     [mqttwarn.core            ] Successfully
loaded service "log",
2020-05-11 21:06:54,610 ERROR    [mqttwarn.core            ] Unable to load
service "my_carbon" from file
"/usr/local/lib/python3.8/site-packages/mqttwarn/services/my_carbon.py":
[Errno 2] No such file or directory:
'/usr/local/lib/python3.8/site-packages/mqttwarn/services/my_carbon.py',
Traceback (most recent call last):,
  File "/usr/local/lib/python3.8/site-packages/mqttwarn/core.py", line 534,
in load_services,
    service_plugins[service]['module'] = load_module(modulefile),
  File "/usr/local/lib/python3.8/site-packages/mqttwarn/util.py", line 157,
in load_module,
    fp = open(path, 'rb'),
FileNotFoundError: [Errno 2] No such file or directory:
'/usr/local/lib/python3.8/site-packages/mqttwarn/services/my_carbon.py',
2020-05-11 21:06:54,611 DEBUG    [mqttwarn.core            ] Attempting
connection to MQTT broker mosquitto:1883...,
2020-05-11 21:06:54,611 DEBUG    [mqttwarn.core            ] Setting LWT to
clients/mqttwarn...,
2020-05-11 21:06:54,619 INFO     [mqttwarn.core            ] Starting 1
worker threads,
2020-05-11 21:06:54,620 DEBUG    [mqttwarn.core            ] Job queue has
0 items to process

Can you please share with me the configuration snippets of your:

   - docker-compose.yml file section regarding the mqttwarn service
   declaration
   - mqttwarn.ini file section where you define th custom functions path

I'm really going crazy with that...

Thanks a lot for all the time you're spending with me in order to try to
find a solution.

Leonardo




Il giorno lun 11 mag 2020 alle ore 18:37 Koen Vervloesem <
notifications@github.com> ha scritto:

**Comment by koenvervloesem** [comment]
My Docker Compose file:

```
version: '3.7'

services:
  mqttwarn:
    image: jpmens/mqttwarn
    container_name: mqttwarn
    restart: always
    volumes:
      - ./mqttwarn:/etc/mqttwarn
      - /etc/localtime:/etc/localtime:ro
```

And in my `mqttwarn.ini` I have:

`functions = 'funcs.py'`

And this is my `./mqttwarn` directory:

```
$ tree mqttwarn/
mqttwarn/
├── funcs.py
└── mqttwarn.ini
```

**Comment by koenvervloesem** [comment]
@lenny1972 Are you sure you're running the right image?

If you're looking on [Docker Hub](https://hub.docker.com/r/jpmens/mqttwarn/tags), the latest `jpmens/mqttwarn` image has SHA256 digest `e8cf6b6cea1d`. Double-check whether your local copy has the same digest (the long number in the `DIGEST` column should begin with the same characters):

```
$ docker image ls --digests jpmens/mqttwarn
REPOSITORY          TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
jpmens/mqttwarn     latest              sha256:e8cf6b6cea1d2ab3bea66de58e66a6f76e042010aff3561149068d0d986a07a1   edf1375a6ac7        3 days ago          210MB
```

And with the container running after your `docker-compose up -d`, check the image the container is using:

```
$ docker inspect mqttwarn|grep Image
        "Image": "sha256:edf1375a6ac79f19cb8d3c9a00d201a78dbc69742c17626aefa4732b271652c9",
            "Image": "jpmens/mqttwarn",
```

The first characters of the SHA256 hash should match the characters in the `IMAGE ID` column of the previous `docker image` command.

**Comment by lenny1972** [comment]
Hi Koen,
this is the image number trat I get form the docker inspect on the mqttwarn
container:
Image
sha256:edf1375a6ac79f19cb8d3c9a00d201a78dbc69742c17626aefa4732b271652c9
It means that I'm using the latest image.

This morning I've found a walkaround  in order to be able to use my custom
function.
In details I've dove what follows:
1. I've addded the following in the docker-compose file a new row in the
mqttwarn service volumes section:
      -
'/opt/mqttwarn/my_custom_function.py:/usr/local/lib/python3.8/site-packages/mqttwarn/services/my_custom_function.py'
2. In the mqttwarn.ini file I've declared the custom function path as
follows:
      functions = 'my_custom_function.py'
3. Then I've saved in the host the file my_custom_function.py in the folder
/opt/mqttwarn/
4. Relaunch the docker coompose

Et voilat! As you can see, now from the mqttwarn log  the custom function
is loaded correctly:

2020-05-14 09:48:01,358 INFO     [mqttwarn.commands        ] Starting
mqttwarn,
2020-05-14 09:48:01,358 INFO     [mqttwarn.commands        ] Log level is
DEBUG,
2020-05-14 09:48:01,360 INFO     [mqttwarn.core            ] Successfully
loaded service "file",
2020-05-14 09:48:01,360 INFO     [mqttwarn.core            ] Successfully
loaded service "log",
2020-05-14 09:48:01,361 INFO     [mqttwarn.core            ] Successfully
loaded service "my_custom_function",
2020-05-14 09:48:01,362 DEBUG    [mqttwarn.core            ] Attempting
connection to MQTT broker mosquitto:1883...

I hope this can help others facing my same issue and give you some clues in
order to fix it (if necessary).

L.



Il giorno gio 14 mag 2020 alle ore 10:46 Koen Vervloesem <
notifications@github.com> ha scritto:

**Comment by koenvervloesem** [comment]
Nice! But I still have no clue where it's going wrong... Can anyone else confirm that custom functions are working like in https://github.com/jpmens/mqttwarn/issues/419#issuecomment-626951846 or does it just magically work for me?

**Comment by DarkSupremo** [comment]
I'm using an custom function with cron, and at least on windows host it worked fine here..

Here is my docker-compose:

```
    mqttwarn:
        image: jpmens/mqttwarn
        container_name: mqttwarn
        restart: unless-stopped
        depends_on:
            - "mqtt"
        volumes:
            - ./mqttwarn:/etc/mqttwarn
        networks:
            - infranet
```

**Comment by amotl** [comment]
Dear Leonardo, Koen and Uilton,

#496 significantly improved using custom files with `mqttwarn`. The new feature/behavior is documented at https://github.com/jpmens/mqttwarn/blob/master/HANDBOOK.md#loading-external-services.

We will be happy to hear back from you about this.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi again,

I will close this ticket now. Today, we have Docker images for mqttwarn including many dependencies called `ghcr.io/jpmens/mqttwarn-full`. See also [1].

Please let us know if that works for you. Otherwise, feel free to reopen this issue.

With kind regards,
Andreas.

[1] https://github.com/jpmens/mqttwarn/blob/main/DOCKER.md#choosing-the-docker-image
