### ISSUE TITLE
Add official multi-platform Docker builds

### ISSUE THREAD

**Issue by koenvervloesem** [jpmens/mqttwarn#424]
If I want to use mqttwarn in a Docker container on my Raspberry Pi, I currently have to build the image myself, because the official Docker image on Docker Hub is only for amd64. I decided to document how to fix this.

Here's how I did this:

First some preparation on the build host (which is a amd64 machine), as explained in a [blog post from Docker](https://www.docker.com/blog/multi-platform-docker-builds/):

```
docker run --privileged --rm docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
sudo systemctl restart docker.service
mkdir ~/.docker/cli-plugins
wget https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-arm64 -O ~/.docker/cli-plugins/docker-buildx
chmod a+x ~/.docker/cli-plugins/docker-buildx
```
Build the images for different platforms and push them:

```
docker buildx build --platform linux/amd64 -t koenvervloesem/mqttwarn:amd64 .
docker push koenvervloesem/mqttwarn:amd64
docker buildx build --platform linux/arm/v7 -t koenvervloesem/mqttwarn:armv7 .
docker push koenvervloesem/mqttwarn:armv7
docker buildx build --platform linux/arm64/v8 -t koenvervloesem/mqttwarn:armv8 .
docker push koenvervloesem/mqttwarn:armv8
```

Then create and push a manifest so the latest tag refers to the right tag for your architecture:

```
docker manifest create koenvervloesem/mqttwarn:latest koenvervloesem/mqttwarn:amd64 koenvervloesem/mqttwarn:armv7 koenvervloesem/mqttwarn:armv8
docker manifest push koenvervloesem/mqttwarn:latest
```

You can try the result, a multi-arch Docker build for mqttwarn, from [koenvervloesem/mqttwarn](https://hub.docker.com/r/koenvervloesem/mqttwarn). A `docker pull` on amd64, armv7 (such as Raspbian) or armv8 (such as 64-bit Ubuntu on the Raspberry Pi) should work. I tested this on Ubuntu 19.10 for amd64 and Raspbian 10 on a Raspberry Pi 4 for armv7. Note that this image is built from https://github.com/jpmens/mqttwarn/pull/423, so the default directory is `/etc/mqttwarn`.

It would be awesome if this multi-arch build process could be integrated in this project's CI! Let me know if you need some help.

**Comment by tam481** [comment]
Hello @jpmens and @koenvervloesem 
I just wanted to add my support for this. I run my dev environment on a debian VM and the prod on a Raspberry Pi 4 and I would love for there to be a docker image for multiple architectures.

**Comment by amotl** [comment]
Dear @koenvervloesem, @tam481, @tinuva, @rgitzel, @tomhoover, @egadgetjnr, @psyciknz, @lenny1972, @darksupremo, @sumnerboy12 and all Docker lovers,

with the most recent release of mqttwarn 0.24.0, through #509, there are now [multi-platform Docker images](https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md) for mqttwarn made available for both `mqttwarn-standard` and `mqttwarn-full` flavors on each release, see [1].

We will have to polish that setup slightly, see #514, but in general we are satisified with the current state of the release pipeline (#425). Please let us know about any issues you might run into and about any things to improve.

With kind regards,
Andreas.

[1] https://github.com/jpmens?tab=packages&repo_name=mqttwarn

---

```shell
$ docker manifest inspect ghcr.io/jpmens/mqttwarn-full:latest
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2414,
         "digest": "sha256:92c13939393a36c25c049ac4d0ad5bee831adb01d54ca02846a0cdbb9a530f28",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2414,
         "digest": "sha256:dd4eec041d7f9122b7062046a6782e258570e9f6235b30b63a34747130869813",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2414,
         "digest": "sha256:fb0535e3b0351a741bfe0494df0a52ee0f68341a6b972013314381b1c0f4a500",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      }
   ]
}
```

**Comment by jpmens** [comment]
Excellent work, @amotl, thank you very much.
