### ISSUE TITLE
Populating InfluxDB with individual tags and fields from JSON message

### ISSUE THREAD

**Issue by psyciknz** [jpmens/mqttwarn#429]
Been playing with fail2ban over the past couple of days....and from it managed to get a json formatted mqtt message out on each ban.
```
{ "ip": "37.49.226.155", "failures": "28", "jail": "ssh", "time": "1591645309.58". "country": "<country"> }
```
So now I want to get these into influx.

Here is my section.....I've tried all sorts of combinations.  I basically want a table, with tags for the jail (ssh) and ip, with values of the number of failures.

```
; -----------------------------------------
;             Fail2ban
; -----------------------------------------
[fail2ban/ban]
#topic = fail2ban/ban
targets = influxdb:fail2ban
format  = jail={jail},ip={ip} value={failures}
```

But nothing I do seems to affect the format.  The logs just try sending the entire json string as the value:
```
2020-06-09 07:41:50,985 DEBUG [connectionpool] http://influxdb:8096 "POST /write?db=network&rp=default&precision=ns HTTP/1.1" 400 219
2020-06-09 07:41:50,987 WARNING [influxdb] POST request failed: (400) {"error":"unable to parse 'fail2ban,topic=fail2ban_ban value={ \"ip\": \"37.49.226.155\", \"failures\": \"28\", \"jail\": \"ssh\", \"time\": \"1591645309.58\". \"country\": \"\u003ccountry\"\u003e }': invalid boolean"}
```

**Comment by amotl** [comment]
Dear @psyciknz,

thanks for using mqttwarn and for writing in.

When looking at the configuration snippet [1] and the corresponding source code of the InfluxDB plugin [2], the `format` setting might suggest that it is possible what you are aiming at:
```
format = room=basement,entity=sensor2 temperature={payload}
```

However, it looks like the plugin currently is **not** capable of interpolating different fields from a JSON message received over MQTT into individual components of a signal to InfluxDB like you are intending here:
```
format  = jail={jail},ip={ip} value={failures}
```

With kind regards,
Andreas.

[1] https://github.com/jpmens/mqttwarn/blob/master/HANDBOOK.md#influxdb
[2] https://github.com/jpmens/mqttwarn/blob/0.16.1/mqttwarn/services/influxdb.py

**Comment by psyciknz** [comment]
So I'd have to pull it apart the payload by a function - but even then I don't this the formatting would be as I wanted, or alter the influxdb service to allow any sort of tagging the user wants.

**Comment by amotl** [comment]
I see three ² options:

- Improve the InfluxDB plugin of `mqttwarn` [1].
- Investigate whether `bch-mqtt2influxdb` [2] would fit your needs which I just found yesterday.
- Use [Kotori](https://getkotori.org/) which might also need some minor improvements in order to fulfill your needs ¹.
- Ramp up a custom MQTT->InfluxDB forwarder ².

[1] https://github.com/jpmens/mqttwarn/blob/0.16.1/mqttwarn/services/influxdb.py
[2] https://github.com/bigclownlabs/bch-mqtt2influxdb

¹ Disclaimer: I am the main author of Kotori.
² There are only two hard things in Computer Science: cache invalidation, naming things, and off-by-one errors.

**Comment by amotl** [comment]
Hmm, when looking at this more closely, I believe the code path currently seems to be [1], as you are getting 
```
fail2ban,topic=fail2ban_ban value={ \"ip\": \"37.49.226. [...]
```

However, it should probably trigger one of the other two branches within the code and things might turn out better, right?

With kind regards,
Andreas.

[1] https://github.com/jpmens/mqttwarn/blob/0.16.1/mqttwarn/services/influxdb.py#L51-L55

**Comment by amotl** [comment]
Could you say `print(item.message)` at line 50 to see what is actually going on with `item.message` here? Thanks already!

**Comment by jacques42** [comment]
Hey  @psyciknz  - Looks like the JSON you pipe into mqttwarn actually has  syntax errors 

```
"time": "1591645309.58". "country": "<country"> }
```
This should be
```
"time": "1591645309.58", "country": "<country>" }
```
Note to replace dot by comma as separator between the last and one before last key/value pair. And also note the "greater than" sign should move inside the value field of the last key/value par.

Looks like that's the reason why [1] triggers, given mqttwarn can not parse this JSON and populate the key/value pairs you are looking for in the format string. 

Try to fix the JSON format and the code should do what you are looking for, or let me know. 

[1] https://github.com/jpmens/mqttwarn/blob/0.16.1/mqttwarn/services/influxdb.py#L51-L55

**Comment by psyciknz** [comment]
Hmm I think I'm running an old one.   I hadn't updated my mqttward instance for a while, as I use a custom one (with the local services that there's an outstanding pull request for)
```
if item.message == item.payload:
            data = measurement + ',' + tag + ' value=' + value
        else:
            # sample format in .ini file; no quotes:
            # format = host=server1,location=rack1 cpu={payload}
            data = measurement + ',' + tag + ',' + item.message
```

**Comment by psyciknz** [comment]
So I pulled the latest influxdb code (was able to add it as a quick local service).
With this config and the change found by @jacques42:
```
; -----------------------------------------
;             Fail2ban
; -----------------------------------------
[fail2ban/ban]
topic = fail2ban/ban
targets = log:info, slack:general, influxdb2:fail2ban
format = jail={jail},ip={ip} value={failures}
[fail2ban/unban]
topic = fail2ban/unban
targets = log:info, slack:general, influxdb2:fail2ban
format = jail={jail},ip={ip} value=0
```

And json of :
```
 payload: u'{ "ip": "37.49.226.173", "failures": "20", "jail": "ssh", "time": "1591654022.12"}'
```
I'm now getting entries into a fail2ban table with 
```
time                ip            jail topic        value
----                --            ---- -----        -----
1591654023921039577 37.49.226.173 ssh  fail2ban_ban 20
```
Which is good enough for me.  Unbans go into the same table.  with fail2ban_unban.  Ideally I'd like it just to say ban an unban, but close enough.

I should merge you latest code into my branch for updates.  Since my PR would be well out of date now.  (#375)

**Comment by psyciknz** [comment]
I think this can be closed now also, as I'm running main mqttwarn and not a custom one.

**Comment by amotl** [comment]
Thanks for letting us know!
