### ISSUE TITLE
Maybe note at mqtt2graphite pointing here?

### ISSUE THREAD

**Issue by TRSx80** [jpmens/mqttwarn#431]
I was quite distraught when I discovered [mqtt2graphite](https://github.com/jpmens/mqtt2graphite/issues) was archived!

It took me a little more research to find this project.  Which I realized can accomplish same functionality.  Nice project by the way, and thanks for sharing it!  :beers: 

FYI, mqtt2graphite is still listed in a number of places with relevant information like [awesome-mqtt](https://github.com/hobbyquaker/awesome-mqtt#logging) and in fact it is still the very top search result for *all* of the following searches:
* graphite mqtt
* graphite mosquitto
* mqtt carbon

... And I am sure others!  But those were the ones I tried.  So, I am sure not to be the only person looking in a specific area who may have trouble finding it!

Just a short blurb at the top with a link here aught to do it!  Luckily that repository is still under control of same person (@jpmens), although I did not realize this until after I got here!

In fact it likely would have taken me a lot longer to pick this project out of the list at awesome-mqtt if I had not previously read something about carbon plug-in for mqttwarn in [this](https://www.domoticaforum.eu/viewtopic.php?f=81&t=10939) old (2015) Domotica forum post!  With the name "mqttwarn" it certainly would not have been my first thing to look for!

**Comment by jpmens** [comment]
As you've already noted, `mqtt2graphite` is read-only, so I won't add a note to it. As for the lists you refer to, I suggest you propose changing the content there, maybe with a pull request to assist the maintainers.

**Comment by TRSx80** [comment]
Unfortunate decision.  I think it makes it much harder than it should be to find this wonderful project.

Anyway, last night I was already thinking to lodge a PR at awesome-mqtt with an update as you suggest, when my wife called me to bed.  :smile:  So this is where I pick up this morning.

I realized their list is organized by categories.  I just began familiarizing myself with mqttwarn, so I am sure I am not aware of the full depth and breadth of it's functionality (as it seems quite a lot!).  So far I identified the following categories (in terms of [awesome-mqtt list](https://github.com/hobbyquaker/awesome-mqtt)) where I thought it would be relevant, but by all means any assistance would be appreciated.  I formatted the checklist in plain text (Orgmode format actually) so it should be easy to copy/paste.

I think the best approach is to list mqttwarn in each relevant category, but maybe I should trim down the blurb a lot more.  Most blurbs on that page about each project are only one sentence.  Anyway, perfection is the enemy of progress, so here is the first draft (probably needs more work).

Feedback welcomed.
```
 - [ ] Community Resources
 - [ ] Broker
 - [ ] Cloud
 - [ ] Tools
 - [ ] Clients
 - [X] Scripting
   - Subscribes to any number of MQTT topics and publishes received payloads to one or more
     notification (or other) services after optionally applying sophisticated transformations.  It
     comes with over 70 notification handler plugins for a wide range of notification services and
     is very open to further contributions. You can enjoy the alphabetical list of plugins within
     the handbook.
 - [-] Interfaces
   - [ ] Makers
   - [ ] Industry
   - [X] Telephony, PBX
     - Subscribes to any number of MQTT topics and publishes received payloads to one or more
       notification (or other) services after optionally applying sophisticated transformations.  It
       comes with over 70 notification handler plugins, including options to send notifications via
       several F/LOSS telephony/PBX solutions.
   - [ ] Operating System
   - [X] Monitoring
     - Subscribes to any number of MQTT topics and publishes received payloads to one or more
       notification (or other) services after optionally applying sophisticated transformations.  It
       comes with over 70 notification handler plugins for a wide range of notification services and
       is very open to further contributions. You can enjoy the alphabetical list of plugins within
       the handbook.
   - [ ] Location Tracking
   - [X] Logging
     - Subscribes to any number of MQTT topics and publishes received payloads to one or more
       notification (or other) services after optionally applying sophisticated transformations.  It
       comes with over 70 notification handler plugins, including options to dump into several
       databases or even plain files.
   - [ ] Smart Home Hardware Interfaces
   - [ ] Smart Home Integration Software
   - [ ] Lighting
   - [ ] Home Entertainment
   - [ ] Smart Metering
   - [X] Messaging
     - (already present in list with following blurb)
     - Subscribe to MQTT topics (with wildcards) and notify pluggable services.
   - [ ] Misc
 - [ ] Visualization, Dashboards
 - [ ] Architecture, Convention
 - [ ] Security, Encryption
```

**Comment by TRSx80** [comment]
Second draft, I essentially shortened the blurb to "Amongst [many other services](https://github.com/jpmens/mqttwarn/blob/master/HANDBOOK.md#supported-notification-services), can also [...]."

I also added it to "Operating System" heading, as I noticed `pipe` functionality.

Feedback welcomed.

```
 - [ ] Community Resources
 - [ ] Broker
 - [ ] Cloud
 - [ ] Tools
 - [ ] Clients
 - [X] Scripting
   - Amongst [many other services](https://github.com/jpmens/mqttwarn/blob/master/HANDBOOK.md#supported-notification-services), can also (optionally) apply sophisticated transformations.
 - [-] Interfaces
   - [ ] Makers
   - [ ] Industry
   - [X] Telephony, PBX
     - Amongst [many other services](https://github.com/jpmens/mqttwarn/blob/master/HANDBOOK.md#supported-notification-services), can also publish to several F/LOSS telephony/PBX solutions.
   - [X] Operating System
     - Amongst [many other services](https://github.com/jpmens/mqttwarn/blob/master/HANDBOOK.md#supported-notification-services), can also publish to [pipe](https://github.com/jpmens/mqttwarn/blob/master/HANDBOOK.md#pipe)s.
   - [X] Monitoring
     - Can publish to many different [services](https://github.com/jpmens/mqttwarn/blob/master/HANDBOOK.md#supported-notification-services).
   - [ ] Location Tracking
   - [X] Logging
     - Amongst [many other services](https://github.com/jpmens/mqttwarn/blob/master/HANDBOOK.md#supported-notification-services), can also publish to several databases.
   - [ ] Smart Home Hardware Interfaces
   - [ ] Smart Home Integration Software
   - [ ] Lighting
   - [ ] Home Entertainment
   - [ ] Smart Metering
   - [X] Messaging
     - (already present in list with following blurb)
     - Subscribe to MQTT topics (with wildcards) and notify pluggable services.
   - [ ] Misc
 - [ ] Visualization, Dashboards
 - [ ] Architecture, Convention
 - [ ] Security, Encryption
```

**Comment by TRSx80** [comment]
Round three.

Maybe change "many other services" to "many (over 70) other services"?
