### ISSUE TITLE
Default logfile should be a more standard path, or the documentation should be improved

### ISSUE THREAD

**Issue by ktaragorn** [jpmens/mqttwarn#439]
Currently if the logfile arg is not set, the default path for the logfile is `/mqttwarn.log`. This is not specified anywhere in the documentation, and is a very odd place to be, especially if used without docker (the handbook talks a lot about supervisord). It seems very cumbersome to change this to stdout (i saw 1 place mention `/dev/stdout`) but I get permission errors since im running as non root. From digging into examples in the tests, I saw `stream://sys.stderr` which seems to work.. but it should likely be the default to output to STDOUT, rather than a file at the root of the filesystem.

**Comment by amotl** [comment]
Dear Karthik,

thank you very much for writing in and apologies for the very late reply. Can I humbly ask you to check if the behavior of recent versions of `mqttwarn` got improved? As far as I know, it will emit log messages to STDERR (which I believe is fine) by default.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear Karthik,

may I humbly ask you if this is still an issue for you? I will close the ticket now, but please feel free to reopen anytime.

With kind regards,
Andreas.

**Comment by ktaragorn** [comment]
Sorry havent had the time to check again. If it is outputing to stderr now, that should work. But shouldnt stderr be used only for error messages? Is that what u mean?

**Comment by amotl** [comment]
Hi Karthik,

I think using STDERR for all logging output is completely fine. In this manner, STDOUT is free to use for _real_ program output which can be piped into other programs. While the latter does not apply specifically to mqttwarn, that is the way to think about STDOUT vs. STDERR in general.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi again,

I just found that STDERR was not selected as a default log target yet. #531 improves the situation.

With kind regards,
Andreas.
