### ISSUE TITLE
change == to >=

### ISSUE THREAD

**Issue by dlangille** [jpmens/mqttwarn#443]
Would you consider changing the == in setup.py to >=?

I'm running with this in FreeBSD now:

This follows: https://wiki.freebsd.org/Python/PortsPolicy#Dependencies

It is to avoid breaking `mqttwaren` when one of its dependencies is updated.

That request also applies to the dependencies listed under extras_require. Please read the bit under Sat, Aug 8, 11:06 PM in the [FreeBSD mqttwarn port code](https://reviews.freebsd.org/D24654). It also mentions " 'non-compulsory' test dependencies to an extras_require[dev] section, that tox.ini then pulls in. This will leave extras_require[test] as purely compulsory test dependencies (pytest, and optional run time deps)" which I admit I do not follow. My python knowledge is lacking. I can write some code, but I don't have the packaging information.

```
$ cat patch-setup.py
--- setup.py.orig	2020-08-08 02:11:44 UTC
+++ setup.py
@@ -7,14 +7,14 @@ here = os.path.abspath(os.path.dirname(__file__))
 README = open(os.path.join(here, 'README.rst')).read()
 
 requires = [
-    'six==1.13.0',
-    'paho-mqtt==1.5.0',
-    'jinja2==2.10.3',
-    'attrs==19.3.0',
-    'docopt==0.6.2',
-    'requests==2.22.0',
-    'future==0.18.2',
-    'configparser==4.0.2',
+    'six>=1.13.0',
+    'paho-mqtt>=1.4.0',
+    'jinja2>=2.10.1',
+    'attrs>=19.3.0',
+    'docopt>=0.6.2',
+    'requests>=2.22.0',
+    'future>=0.18.2',
+    'configparser>=3.5.3',
 ]
 
 extras = {

```

**Comment by jpmens** [comment]
As far as I can tell we would accept a patch which changes version _equality_ to one _greater equal_ as you suggest.

To be honest, I'm not understanding what is meant by the _ 'non-compulsory' test dependencies_.
