### ISSUE TITLE
Little Problem with nsca plugin and python3

### ISSUE THREAD

**Issue by alemid** [jpmens/mqttwarn#444]
Hi,
and thank you for great work!
I'm new to mqttwarn, with no knowledge of python language, but it seems to me a very very useful software.
I use it successfully to send alarms to Nagios, via nsca plugin.
At first, I use python 3 but when intercepted alarms and nsca plugin is invoked, I receive:
Cannot notify to NSCA host `172.18.2.210': must be str, not bytes

I googled a bit, and it seems to me it could be dueto python 3, so I reinstall mqttwarn and nsca plugin with Python2 and it worked as expected.

Can you give some suggestion to resolve issue?

Thank you in advance and sorry for my bad English.

Alessandro

**Comment by jpmens** [comment]
This should now be fixed.

**Comment by alemid** [comment]
Thank you,
and sorry for the trivial question.
Now it works

Thank you again!

Alessandro

**Comment by jpmens** [comment]
You might think it was a trivial question, but you actually found a bug, so thank you for reporting that and for testing the result.

**Comment by alemid** [comment]
Hi,
I'm sorry again, but it seems i was too hasty with test.
Maybe I'm doing something wrong, but I see source mod and  in
module /usr/local/lib/python3.6/site-packages/mqttwarn/services/nsca.py I
modify the line from:
nsca_host =  config['nsca_host']
to
nsca_host = str(config['nsca_host'])

but again I received "Cannot notify to NSCA host `172.18.2.210': must be
str, not bytes"
Thank you again




Il giorno lun 10 ago 2020 alle ore 15:00 JP Mens <notifications@github.com>
ha scritto:

**Comment by jpmens** [comment]
Just to be quite sure: you did restart mqttwarn?

**Comment by alemid** [comment]
Yes, I restart mqttwarn
I simply launch mqttwarn from shell to test, and Ctrl-c to quit.
I set: cleansession = True in mqttwarn, too.
And to be sure I change the right python file, I modify the ncsa.py file I
find in log:
2020-08-10 16:18:55,397 DEBUG    [mqttwarn.services.nsca   ] ***
MODULE=/usr/local/lib/python3.6/site-packages/mqttwarn/services/nsca.py:
service=nsca, target=test_prismon
I don't know if there could be some caching from python...



Il giorno lun 10 ago 2020 alle ore 17:10 JP Mens <notifications@github.com>
ha scritto:

**Comment by alemid** [comment]
Hi,
I tried to debug a bit, to help investigation, if possible...
I add a block raise Exception, and it seems the type error is in pynsca.py.

-------------------------------------------------------------
notif.svc_result(host_name, service_description, status, text)
  File "/usr/local/lib/python3.6/site-packages/pynsca.py", line 181, in svc_result
    buf += data
TypeError: must be str, not bytes
------------------------------------------------------------
Thank you again for great software and support

Alessandro

**Comment by jpmens** [comment]
2020-08-12 10:20:20,750 WARNING [nsca] Cannot notify to NSCA host `192.168.1.148': can only concatenate str (not "bytes") to str
2020-08-12 10:20:20,751 WARNING [core] Notification of nsca for `n/1' FAILED or TIMED OUT

**Comment by jpmens** [comment]
@alemid I confirm that `pynsca` doesn't work with Python3. I've tried hacking around it but it appears to be more than trivial (at least for me), so I'm giving up.

It appears that upstream [confirmed in 2017 already that pynsca doesn't work with Python3](https://github.com/djmitche/pynsca/issues/22) and I don't see that having been fixed.

Sorry, I cannot spend more time on this.

**Comment by alemid** [comment]
Ok, it’s a pity but doesn’t matter.Thank you again for support and for mqttwarn! Alessandro Inviato da Posta per Windows 10 Da: JP MensInviato: mercoledì 12 agosto 2020 10:52A: jpmens/mqttwarnCc: alemid; MentionOggetto: Re: [jpmens/mqttwarn] Little Problem with nsca plugin and python3 (#444) @alemid I confirm that pynsca doesn't work with Python3. I've tried hacking around it but it appears to be more than trivial (at least for me), so I'm giving up.It appears that upstream confirmed in 2017 already that pynsca doesn't work with Python3 and I don't see that having been fixed.Sorry, I cannot spend more time on this.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
