### ISSUE TITLE
configparser.ParsingError: Source contains parsing errors: 'mqttwarn.ini'

### ISSUE THREAD

**Issue by clach04** [jpmens/mqttwarn#452]
Getting:

    configparser.ParsingError: Source contains parsing errors: 'mqttwarn.ini'
            [line 165]: '}\n'

This is when using the samples for Telegram from the handbook. It looks like the closing `}` needs to be indented as once that is done problem goes away.

**Comment by jpmens** [comment]
Closed via #453
