### ISSUE TITLE
Spurious `WARNING  [mqttwarn.services.telegram] Failed to send request to Telegram`

### ISSUE THREAD

**Issue by clach04** [jpmens/mqttwarn#454]
Warning from Telegram plugin for a chatid (not tested WITHOUT chatId):

    WARNING  [mqttwarn.services.telegram] Failed to send request to Telegram

but message is received, send was successful.

Actually two issues:

* Python 3.5.3 (default py3 version on Raspbian) - telegram result status is lost
* Under all python versions, any exceptions that happen are lost and not reported.

**Comment by clach04** [comment]
I've not had luck with adding additional diagnostic tracing yet.

Interactive debugger doesn't work, trying external. Logging for tracking.

**Comment by clach04** [comment]
Turns out there are two issues:
* python2 code failing in python3 - decoding the json response
* bare except :-( so the error is lost and never reported :(

https://github.com/Kozea/wdb is awesome! Found the issue almost instantly.

**Comment by jpmens** [comment]
I believe you've fixed this in #455 ?

**Comment by clach04** [comment]
Yes, closed by ##455
