### ISSUE TITLE
Amazon Alexa support

### ISSUE THREAD

**Issue by clach04** [jpmens/mqttwarn#459]
I have a working demo setup with alexa-notify-me, however its not really what I wanted. This is a really useful feature, it uses an notification (speaker glows yellow) and awaits instruction to play the notification(s), so the announcement is never to an empty room.

I really wanted an announcement, with no real concern if no one hears them (alexa-notify-me to be used in those use cases). I ended up using the pipe support for this (I didn't have the energy to write a pure Python plugin for this).

Is this worth documenting as an example or is this too specific?

    [config:pipe]
    targets = {
       'alexa_living_room'    : [ '/home/pi/shell/alexa-remote-control/saystdin', '-d', 'Living_Room' ]
       }

    # echo testing from mqttwarn | mosquitto_pub -t 'alexa/living_room' -l
    # echo testing from m q t t warn | mosquitto_pub -t 'alexa/living_room' -l
    [alexa/living_room]
    targets = pipe:alexa_living_room

Where `saystdin` is a wrapper around https://github.com/thorsten-gehrig/alexa-remote-control (requires `curl` and `oauthtool` to be installed)

    #!/bin/sh

    . /home/pi/shell/alexa-remote-control/secrets.sh

    # Example:
    #   echo test from command line | ./saystdin -d speaker_name

    read message
    echo ${message}

    /home/pi/shell/alexa-remote-control/alexa_remote_control_plain.sh ${*} -e speak:"${message}"

And where `secrets.sh` sets up overrides config (sample American-English config):

    export EMAIL='your@email.here.com'
    export PASSWORD='your passwod here'
    export MFA_SECRET='your 2fa scret here'
    export LANGUAGE='en-US'
    export TTS_LOCALE='en-EN'
    export AMAZON='amazon.com'
    export ALEXA='pitangui.amazon.com'

This plus https://github.com/jpmens/mqttwarn/pull/458 gets coverage the big two American smart speakers.

**Comment by jpmens** [comment]
I think it may be useful to others so, yes, please document it. We've the `examples/` directory for support files if you PR them into that.

**Comment by clach04** [comment]
Posted #460

**Comment by jpmens** [comment]
Closed via #460
