### ISSUE TITLE
Can http post send the whole message as is?

### ISSUE THREAD

**Issue by tg44** [jpmens/mqttwarn#471]
I tried it with;
```
[config:http]
timeout = 60
targets = {
          #method     #URL               # query params or None                              # list auth # Json
          'mymethod'    : [ "post", "https://example.com/post, None, None, True ]
          }

```
Based on the [code](
https://github.com/jpmens/mqttwarn/blob/1abee3d73ceabde04069eff5c6a385011e1833d1/mqttwarn/services/http.py#L101) I think this should be at least sth like;
```
            if params is not None:
                if tojson is not None:
                    encoded_params = json.dumps(params)
                    request.add_header('Content-Type', 'application/json')
                else:
                    encoded_params = urllib.parse.urlencode(params)
            else:
                if tojson is not None:
                    encoded_params = item.payload
                    request.add_header('Content-Type', 'application/json')
                else:
                    encoded_params = message
```

Also I have an error `'Request' object has no attribute 'add_data'`. Which is probably due to some 'request' lib incompatibility.

If I will have more time I will try to PR this, but bcs of other errors in the project and bcs I have close to zero python knowledge I'm stucked right now.

**Comment by amotl** [comment]
Dear Gergő,

thanks for your report. We will have to look into this next week. In general, it would be good to rewrite this plugin based on the "requests" library, but we will see whether we can fix it for your specific use case.

However, if you can find some time to submit a PR, we will be more than happy.

With kind regards,
Andreas.

On 11 December 2020 16:55:21 CET, "Gergő Törcsvári" <notifications@github.com> wrote:
>I tried it with;
>```
>[config:http]
>timeout = 60
>targets = {
>#method     #URL               # query params or None                  
>           # list auth # Json
>'mymethod'    : [ "post", "https://example.com/post, None, None, True ]
>          }
>
>```
>Based on the [code](
>https://github.com/jpmens/mqttwarn/blob/1abee3d73ceabde04069eff5c6a385011e1833d1/mqttwarn/services/http.py#L101)
>I think this should be at least sth like;
>```
>            if params is not None:
>                if tojson is not None:
>                    encoded_params = json.dumps(params)
>                 request.add_header('Content-Type', 'application/json')
>                else:
>                    encoded_params = urllib.parse.urlencode(params)
>            else:
>                if tojson is not None:
>                    encoded_params = item.payload
>                 request.add_header('Content-Type', 'application/json')
>                else:
>                    encoded_params = message
>```
>
>Also I have an error `'Request' object has no attribute 'add_data'`.
>Which is probably due to some 'request' lib incompatibility.
>
>
>If I will have more time I will try to PR this, but bcs of other errors
>in the project and bcs I have close to zero python knowledge I'm
>stucked right now.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jpmens/mqttwarn/issues/471

-- 
Sent from my mind. This might have been typed on a mobile device, so please excuse my brevity.
