### ISSUE TITLE
mqttwarn is eating up all memory

### ISSUE THREAD

**Issue by gbeine** [jpmens/mqttwarn#478]
I'm using mqttwarn for a while now.
It works great, but I'm running into an recurring issue after ~4 days of uptime.
mqttwarn is eating up all memory available on my RPi2.
When I start it, it's around 2.2%, after a few days it's consuming ~75% and the load on the RPi is increasing to 25.
It tooked a while to figure this out, as the RPi seemed to be dead after a while.

The same issue happens on a RPi4 with a similar configuration.
I use mqttwarn to trigger the Icinga 2 API upon MQTT events.

mqttwarn.ini
```
; ------------------------------------------
;             Base configuration
; ------------------------------------------

[defaults]

; ----
; MQTT
; ----

hostname     = 'localhost'
port         = 1883
username     = 'mqttwarn'
password     = ''
clientid     = 'mqttwarn'
lwt          = 'clients/mqttwarn'
skipretained = False
cleansession = False
protocol     = 3

; -------
; Logging
; -------

; Send log output to STDERR
logfile   = 'stream://sys.stdout'

; one of: CRITICAL, DEBUG, ERROR, INFO, WARN
loglevel  = ERROR

; --------
; Services
; --------

; path to file containing self-defined functions for formatmap, alldata, and datamap
functions = '/opt/service/mqttwarn/functions.py'

; name the service providers you will be using.
launch    = log, icinga2

; -------
; Targets
; -------
[config:log]
targets = {
    'debug'  : [ 'debug' ],
    'info'   : [ 'info' ],
    'warn'   : [ 'warn' ],
    'crit'   : [ 'crit' ],
    'error'  : [ 'error' ]
  }

[config:icinga2]
host = 'https://monitoringserver'
port = 5665
username = 'mqttwarn'
password = ''
cacert = '/opt/service/mqttwarn/icinga.crt'
targets = {
    'vzlogger-q3m' : [ 'busproxy', 'vzlogger-q3m', 'mqttwarn' ],
    'vzlogger-mt174' : [ 'busproxy', 'vzlogger-mt174', 'mqttwarn' ],
    ...
  }

; special config for 'failover' events
[failover]
targets = log:error


; ------------------------------------------
;              Periodic tasks
; ------------------------------------------

[cron]


; ------------------------------------------
;              Icinga monitoring
; ------------------------------------------

[home/devices/vzlogger/#]
format = icinga2_timestamp()
targets = {
    'home/devices/vzlogger/chn0/#': [ 'log:warn', 'icinga2:vzlogger-q3m' ],
    'home/devices/vzlogger/chn1/#': [ 'log:warn' ],
    'home/devices/vzlogger/chn2/#': [ 'log:warn', 'icinga2:vzlogger-mt174' ],
    'home/devices/vzlogger/chn3/#': [ 'log:warn' ],
  }

...
```

functions.py
```
import json

from datetime import datetime

def icinga2_timestamp(data, srv):
    icinga2_payload = {
        'exit_status'  : 0,
        'plugin_output': "OK: @ {}".format(datetime.today().ctime()),
        }

    return json.dumps(icinga2_payload)

def icinga2_format(data, srv):
    icinga2_payload = {
        'exit_status'  : 0,
        'plugin_output': "OK: {}".format(data['payload']),
        }

    return json.dumps(icinga2_payload)
```

**Comment by jpmens** [comment]
Thank you for the report and sorry you're experiencing trouble. This is going to be a tough one to find because I know many of us are running `mqttwarn` for months on end without reboots and I've not heard of it chewing RAM like this.

My first thought is it must be the `icinga` plugin, but that's Python `requests` only so not super likely. Your configuration is not complex so I cannot really ask you to start slimming it down as there is not much to remove. :-) 

Which Python version are you running and which distro? Are there any outstanding updates (particulary to Python) you can apply?

**Comment by gbeine** [comment]
Thanks for the quick reply.
I'm using Raspbian (Debian) Linux 10.7 which is quite up-to-date.
The venv where I run mqttwarn is Python 3.7.3.
The modules are up-to-date too:
```
Package       Version
------------- ---------
attrs         20.3.0
certifi       2020.12.5
chardet       4.0.0
configparser  5.0.1
docopt        0.6.2
future        0.18.2
idna          2.10
Jinja2        2.11.2
MarkupSafe    1.1.1
mqttwarn      0.20.0
packaging     20.8
paho-mqtt     1.5.1
pip           20.3.3
pip-review    1.1.0
pkg-resources 0.0.0
pyparsing     2.4.7
requests      2.25.1
setuptools    51.1.1
six           1.15.0
urllib3       1.26.2
```
I can try to save a debug log on an NFS share if that would help.

**Comment by gbeine** [comment]
I've created a workaround to restart mqttwarn with cron.hourly.
That works, but it feels wrong.

**Comment by jpmens** [comment]
It **is** wrong.

**Comment by gbeine** [comment]
Yes, but it helps to survive until I had a chance to dig deeper into what causes this memory consumption.
The interesting fact is, that I can reproduce it on two different Raspberry Pi.

**Comment by amotl** [comment]
Dear Gerrit,

thank you for your report and apologies for the late reply. When looking into this issue and following [1], I have been able to identify the `requests` library as a potential source of a memory leak. This is also observed by others and summarized at https://github.com/psf/requests/issues/4601. Specifically, I would also like to point out https://github.com/psf/requests/issues/5215.

Maybe you can make any sense of that? Maybe it will enable you to conclude any further investigations.

With kind regards,
Andreas.

[1] https://www.fugue.co/blog/diagnosing-and-fixing-memory-leaks-in-python.html

**Comment by amotl** [comment]
Hi again

> I'm using Raspbian (Debian) Linux 10.7 which is quite up-to-date.
> The venv where I run mqttwarn is Python 3.7.3.

According to the report at https://github.com/psf/requests/issues/5215, there is a Windows-only memory leak bug, see https://bugs.python.org/issue37702. Can I still humbly ask you to try with a more recent version of Python, if possible?

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear Gerrit,

are you still observing those issues with `mqttwarn`, even with the most recent version 0.29.0?

With kind regards,
Andreas.

**Comment by jpmens** [comment]
I'm closing this as very stale; no response in over a year. We can reopen if necessary

**Comment by gbeine** [comment]
Hi, sorry for the late reply.
As the restart cronjob worked quite well, I did not investigate into this.
Next time, when I have access to the system, I'll try an update and see what happens.
I'll come back with the result, but don't expect it early.
