### ISSUE TITLE
Add Squeezebox service (for notification announcements)

### ISSUE THREAD

**Issue by sumnerboy12** [jpmens/mqttwarn#48]
Already do this in openHAB but it would be good to move to mqttwarn.

Using the Google translation web service, but that only accepts a max of 100 chars, so would need to break up long sentences.

**Comment by jpmens** [comment]
Is there nothing non-cloudy which can do this? I.e. something that doesn't rely on an external service knowing what I'm saying?

**Comment by sumnerboy12** [comment]
I have a local TTS service running via Apache (https://community.openhab.org/t/googletts-responding-with-503-error-even-after-the-url-fix/3385/17) which I use for all voice announcements. But I haven't found anything out-of-the-box which can do this in a simpler way.

**Comment by sumnerboy12** [comment]
Yeah I have moved away from the Squeezebox ecosystem so not going to be able to add anything sorry.
