### ISSUE TITLE
mysql plugin didn't use  the specified port

### ISSUE THREAD

**Issue by Hello-Hyman** [jpmens/mqttwarn#480]
No matter what port is used in the configuration, mysql plugin will only connect to port 3306.I checked the code and found that the port variable was not used.
I think the code should be like this

```python
try:
        conn = MySQLdb.connect(host=host,
                               user=user,
                               passwd=passwd,
                               db=dbname,
			       port=port)
```

**Comment by amotl** [comment]
Dear @Hello-Hyman,

thanks for writing in and for reporting this bug. Nice catch!

We need to fix all those of [1,2,3]. A pull request with respective patches would be tremendously helpful for us. Would you be able to submit one?

With kind regards,
Andreas.

[1] https://github.com/jpmens/mqttwarn/blob/0.20.0/mqttwarn/services/mysql.py#L55-L58
[2] https://github.com/jpmens/mqttwarn/blob/0.20.0/mqttwarn/services/mysql_dynamic.py#L101-L104
[3] https://github.com/jpmens/mqttwarn/blob/0.20.0/mqttwarn/services/mysql_remap.py#L68

**Comment by Hello-Hyman** [comment]
[](url) #481

**Comment by Hello-Hyman** [comment]
#481 I have submit a pull request to fix this bug;
