### ISSUE TITLE
How to handle input with many messages?

### ISSUE THREAD

**Issue by Fux2** [jpmens/mqttwarn#487]
Hi all,
I have an RF-interface which is getting plenty of raw messages of all kind of devices. There are also messages, I am not interested for.
Example:
`{"raw":"2F80B19A1442051151","delay":12050,"val_Tlow":310,"val_Thigh":1290,"value":342142}`
Unfortunately the messages are unsorted, means the messages are arriving all at the equal topic.

I have a few remotes which are generating different values on this topic.
I don't want to write for each button a single function, as this would cause messy code and maybe high system load.
What I am looking for, is a function where I can filter if the message is relevant and if yes, give back the formatted value.
I have read the docs, but I can only find either a filter function or a format function.
Is there some function or code which can handle both inside one function or do you have any other suggestions?

Thanks!
Fux2

**Comment by koenvervloesem** [comment]
You could try a trick like this one I used with The Things Network messages: https://koen.vervloesem.eu/blog/one-weird-trick-to-re-enable-mqtt-messages-for-uplink-fields-in-the-things-network-with-mqttwarn/

**Comment by Fux2** [comment]
Koen, thanks for your input!
Seems a promising approach.
I have revised your function to this:
(not completely finished yet, just for test purposes)

`def rfInput(data, srv=None):`
`	if type(data) == dict and "rfin" in data:`
`		value = data["rfin"]`
`		if value[:6] == "261058":`
`			value = 10`
`			srv.mqttc.publish("/topicRF", value, qos=0, retain=False)`
`		return "Published uplink fields of "`
`	return None`

The input I get is "rfin = C001019318A299FE"
I just need the 6 right digits.
Unfortunately the above code is not working - any hints?
Error message in mqttwarn: `Cannot decode JSON object, payload=C001019318A299FE: Expecting value: line 1 column 1 (char 0)`

**Comment by koenvervloesem** [comment]
That input doesn't seem valid JSON. Shouldn't it be something like `{"rfin": "C001019318A299FE"}`?

**Comment by Fux2** [comment]
Ok, I checked. It's no JSON value.
I suppose it is a simple string: `rfin = C001019318A299FE`
Maybe mqttwarn is demanding a JSON format?
```
This is the config in mqttwarn.ini:
[ESPURNA-AA3495/rfin]
topic = ESPURNA-AA3495/rfin
targets = log:info
format = rfInput()
```

**Comment by Fux2** [comment]
Ok, it is working now.
The error message is still there:  `Cannot decode JSON object, payload=C00150A118135AB2: Expecting value: line 1 column 1 (char 0)
`
But it is working anyway. Here is the working code:
```
def rfInput(data, srv=None):
	value = data["payload"][-6:]
	if value == "135AB2":
		srv.mqttc.publish("rfCmd/ab/tasterLinks", 1, qos=0, retain=False)
	elif value == "135AB4":
		srv.mqttc.publish("rfCmd/ab/tasterRechts", 1, qos=0, retain=False)
	else:
		return value
	return "Published rf input: " + value
```
