### ISSUE TITLE
Docker and modules (eg slack_sdk)

### ISSUE THREAD

**Issue by psyciknz** [jpmens/mqttwarn#503]
Trying to look at the official image.
As I'm using slack, I need to pip install slack_sdk.
At this stage, I'm just planning on running 
```docker run --it <volume> jpmens/mqttwarn pip install slack_sdk.```

But i get a permissions error:
```
WARNING: The directory '/home/mqttwarn/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Defaulting to user installation because normal site-packages is not writeable
Collecting slack_sdk
  Downloading slack_sdk-3.6.0-py2.py3-none-any.whl (225 kB)
     |████████████████████████████████| 225 kB 566 kB/s
Installing collected packages: slack-sdk
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/home/mqttwarn'
Check the permissions.
```

How have others done this?

**Comment by psyciknz** [comment]
I did try this as well, but also seems to get permissions error:
```
pip cache dir --cache-dir=/usr/local/lib/python3.9/site-packages/
WARNING: The directory '/usr/local/lib/python3.9/site-packages' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
ERROR: pip cache commands can not function since cache is disabled.
```

**Comment by amotl** [comment]
Dear @psyciknz,

thank you for describing your usage scenario and apologies it didn't work out of the box. As far as I know, a core concept of Docker images is that they are immutable, so in order to customize their contents, one would always need to build a custom image derived from another base image.

In order to outline a solution to your problem based on this, I just submitted #504.

With kind regards,
Andreas.

**Comment by amotl** [comment]
I am only now seeing that @sumnerboy12 apparently also added 7f287fc0, adjusting the main Dockerfile to also install the `slack-sdk` and `gpxpy` Python modules ;].

**Comment by sumnerboy12** [comment]
Whoops, did that go into master? Apologies, I was only meant to push that to my fork!

**Comment by psyciknz** [comment]
This might be a possible docker-compose usage....

```
services:
  mqttwarn:
    build: .
    container_name: mqttwarn-test
    hostname: mqttwarn
    environment:
      - ARCH=amd64
      - BASEPATH=/hdd/docker-data
    restart: always
    mem_limit: 400m
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - ${BASEPATH}/ha-shared/mqttwarn/:/opt/mqttwarn/conf
      - ${BASEPATH}/ha-shared/mqttwarn/run.sh:/opt/mqttwarn/run.sh
      - ${BASEPATH}/ha-shared/mqttwarn/local-services:/opt/local-services
```

Where in the path of . where the docker-compose.yml file exists, you put a Dockerfile with the following:
```
# Docker build file for mqttwarn, with Slack SDK.
# Based on https://hub.docker.com/r/jpmens/mqttwarn.
#
# Invoke like:
#
#   docker build --tag=mqttwarn-slack --file=Dockerfile.mqttwarn-slack .
#

# Derive from upstream image.
FROM jpmens/mqttwarn

# Make package installation run as "root" user
USER root

# Install Slack SDK.
RUN pip install mqttwarn[slack]

# Make process run as "mqttwarn" user
USER mqttwarn
```
#504

**Comment by psyciknz** [comment]
> Whoops, did that go into master? Apologies, I was only meant to push that to my fork!

@sumnerboy12 breaking mqttwarn since ages ago - lol

**Comment by sumnerboy12** [comment]
who the hell gave me write permissions to `master`?!

**Comment by amotl** [comment]
On #506, I started working on using GHA for automatically staging `mqttwarn-full` images. Let's see how much they weigh in  and whether that would provide you the needed convenience.

**Comment by amotl** [comment]
Dear @psyciknz and @sumnerboy12,

the Python package `slack_sdk` is now part of the recently released `mqttwarn-full` Docker images on GitHub Container Registry (GHCR).

You might be able to verify it on your machine by invoking:
```shell
docker run -it --rm ghcr.io/jpmens/mqttwarn-full python -c 'import slack_sdk; print(slack_sdk.version.__version__)'
```

> Let's see how much they weigh in and whether that would provide you the needed convenience.
```shell
$ docker images | grep mqttwarn-standard
ghcr.io/jpmens/mqttwarn-standard                  latest                  4f7beb7ba42b   5 minutes ago   133MB

$ docker images | grep mqttwarn-full
ghcr.io/jpmens/mqttwarn-full                      latest                  f6ac0a250bac   14 hours ago    234MB
```

What do you think about it? Do you believe this will resolve your issue?

With kind regards,
Andreas.

**Comment by psyciknz** [comment]
hmm at 100mb bigger, Its probably not worth me fiddling around with a custom build command in compose.

I just need to work out how to re-integrate my custom "services"

**Comment by amotl** [comment]
Dear @psyciknz,

> At 100mb bigger, Its probably not worth me fiddling around with a custom build command in compose.

Excellent!

> I just need to work out how to re-integrate my custom "services".

#496 improves the situation on that angle. The documentation at [1] outlines how to load custom service plugins from either a Python package or a plain Python file. Let me know if that works for you.

With kind regards,
Andreas.

[1] https://github.com/jpmens/mqttwarn/blob/0.23.1/HANDBOOK.md#loading-external-services

**Comment by psyciknz** [comment]
Can be closed with patches may, and the use of custom dockerfiles.
