### ISSUE TITLE
Adding Python GPX module?

### ISSUE THREAD

**Issue by amotl** [jpmens/mqttwarn#505]
Dear Ben,

at https://github.com/jpmens/mqttwarn/issues/503#issuecomment-856292715, I just wrote:

> I am only now seeing that @sumnerboy12 apparently also added 7f287fc0, adjusting the main Dockerfile to also install the `slack-sdk` and `gpxpy` Python modules ;].

However, I can't find any service plugin within mqttwarn which actually uses `gpxpy`. So, may I humbly ask what this is about and whether it should be better supported by `mqttwarn` in any way?

With kind regards,
Andreas.

**Comment by sumnerboy12** [comment]
Apologies, this was a mistake on my part - I have now reverted that commit!
