### ISSUE TITLE
Improve Prowl notification plugin

### ISSUE THREAD

**Issue by amotl** [jpmens/mqttwarn#507]
Hi there,

according to [1], the Prowl service plugin is based on @jacobb's `prowlpy` [2]. As the most recent release happened on 14 Mar 2011, we should probably start looking for a more recent wrapper. @toddrob99's `pyprowl` might come to the rescue.

With kind regards,
Andreas.

P.S.: This would currently break installation with `pip install mqttwarn[all]` for building the Docker image `mqttwarn-full`, added with #506, so we had to exclude this package there.

[1] https://github.com/jpmens/mqttwarn/blob/0.23.0/setup.py#L181
[2] https://github.com/jacobb/prowlpy
[3] https://github.com/toddrob99/pyprowl

**Comment by jacobb** [comment]
Despite having not touched prowlpy for over a decade now (...wow), I'm happy to help however I can to make these transition -- even if that's just adding heavy deprecation warning + pointing people to pyprowl.

**Comment by amotl** [comment]
Dear Jacob,

thanks for your quick answer.

a) I believe the right strategy would be to update [mqttwarn's prowl service plugin](https://github.com/jpmens/mqttwarn/blob/0.23.1/mqttwarn/services/prowl.py) to use `pyprowl` instead.

b) On the other hand, we might decide to also retroactively upload your `prowlpy` package to PyPI. However, given that it will probably not work on Python 3 without further ado, it is probably not worth the effort and we should look into option a) instead.

With kind regards,
Andreas.

**Comment by amotl** [comment]
> Update [mqttwarn's prowl service plugin](https://github.com/jpmens/mqttwarn/blob/0.23.1/mqttwarn/services/prowl.py) to use `pyprowl` instead.

#511 now brings in a corresponding patch.

**Comment by amotl** [comment]
Hi again,

we will integrate the patch from #511 and see how that goes. Maybe one of you or other people reading here might want to give this a test drive?

With kind regards,
Andreas.

/cc @jacobb, @martinjo, @MansM
