### ISSUE TITLE
Enable GitHub Container Registry (GHCR)

### ISSUE THREAD

**Issue by amotl** [jpmens/mqttwarn#508]
Dear @jpmens,

#506 brings in some improvements to CI and also adds staging Docker images to GHCR. In order to be able to do it, it needs an additional option on GitHub to be enabled for the `jpmens` namespace, see [1].

Can I humbly ask you to enable that "Improved container support" feature on your GitHub account in order to make this patch work? Currently, the process croaks when finally trying to upload the image, see [2].

With kind regards,
Andreas.

[1] https://docs.github.com/en/packages/working-with-a-github-packages-registry/enabling-improved-container-support-with-the-container-registry
[2] https://github.com/jpmens/mqttwarn/runs/2769669836

**Comment by jpmens** [comment]
@amotl I have enabled "Improved Container Support" and have triggered the failed build which appears to have completed.
