### ISSUE TITLE
Install mqttwarn 0.23.1: TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by aerrow5** [jpmens/mqttwarn#510]
Using standard install of mqttwarn on debian 10. Did update as imagebash64 via pushover gave error messages.
Update now gives error: both on debian 10 install as well as on docker.

Error:
```
Traceback (most recent call last):
  File "/usr/local/bin/mqttwarn", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/mqttwarn/commands.py", line 76, in run
    run_mqttwarn()
  File "/usr/local/lib/python3.9/site-packages/mqttwarn/commands.py", line 98, in run_mqttwarn
    config = load_configuration(name=scriptname)
  File "/usr/local/lib/python3.9/site-packages/mqttwarn/configuration.py", line 191, in load_configuration
    return Config(configfile, defaults=defaults)
  File "/usr/local/lib/python3.9/site-packages/mqttwarn/configuration.py", line 88, in __init__
    if os.path.isfile(self.functions):
  File "/usr/local/lib/python3.9/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by amotl** [comment]
Dear Arthur,

thanks for your report. Can I humbly ask to share more details with us? Having your `mqttwarn.ini` at hand would be sweet in order to be able to reproduce what you might be observing.

With kind regards,
Andreas.

**Comment by amotl** [comment]
```
  File "/usr/local/lib/python3.9/site-packages/mqttwarn/configuration.py", line 88, in __init__
    if os.path.isfile(self.functions):
```
That might indicate that the configuration file does not have an entry `functions` or it is empty / simply `None`.

**Comment by amotl** [comment]
Dear Arthur,

I have been able to reproduce the observations you reported and came up with a corresponding improvement, see #513.

With kind regards,
Andreas.

**Comment by aerrow5** [comment]
Apologize for not being complete. It was indeed the solution: 
```
; logging
logformat = '%(asctime)-15s %(levelname)-5s [%(module)s] %(message)s'
logfile   = '/var/log/mqttwarn/mqttwarn.log'

; one of: CRITICAL, DEBUG, ERROR, INFO, WARN
loglevel  = DEBUG

; path to file containing self-defined functions for formatmap and datamap
; functions = 'samplefuncs.py'

; name the service providers you will be using.
launch    = file, log, pushover
```
I disabled the functions resulting in an error. In the older version (April '21) it worked, that's why I expected another issue.
Thanks a lot for the input.

**Comment by amotl** [comment]
Thanks a stack for your report!
