### ISSUE TITLE
Problems running custom "smsgateway.py" service plugin

### ISSUE THREAD

**Issue by amotl** [jpmens/mqttwarn#525]
Dear @psyciknz,

thank you for sharing some more details about your scenario at https://github.com/jpmens/mqttwarn/pull/496#issuecomment-858048410 ff. We will be happy to make mqttwarn support your use case in an optimal manner.

1. In order to clarify the module path resolution, we just improved the documentation by submitting #524.
2. Regarding `ModuleNotFoundError: No module named 'httplib'`, it looks like you are still running Python 2? Offical support for Python 2 will be dropped soon, so it will make sense to update your module to use Python 3.
3. Maybe it would also make sense to share your `smsgateway.py` with the community? In this case, it would be easy to integrate it into mqttwarn for your benefit of reduced maintenance and at the same time, for the benefit of others.

Let me know what you think about this.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Does your comment at https://github.com/jpmens/mqttwarn/pull/496#issuecomment-858063824 mean you have actually been successful?

> Ok, and a test (invalid payload) but I saw my local service called smsgateway kick into gear and try and run:
> ```
> 2021-06-09 20:06:59,172 DEBUG [core] Message received on smsgateway/inbox: test
> 2021-06-09 20:06:59,172 DEBUG [core] Section [smsgateway/inbox] matches message on smsgateway/inbox. Processing...
> 2021-06-09 20:06:59,173 DEBUG [core] Cannot decode JSON object, payload=test: Expecting value: line 1 column 1 (char 0)
> ```

If so, feel free to close this issue right away.

**Comment by psyciknz** [comment]
I thnk smsgateway was evaluated at the time and found to be of no use, and that is what prompted me to investigate running my own services.

Yes I was able to get it running  so we can close this.
