### ISSUE TITLE
Add an 'image' field to the item data collection

### ISSUE THREAD

**Issue by sumnerboy12** [jpmens/mqttwarn#53]
Used initially only in the XBMC service to specify an image URL to use in the notification popup.

Not sure if any other services could use this?

**Comment by amotl** [comment]
A cropped and scaled-down image variant, for adding it to the documentation. Thanks.

![image](https://user-images.githubusercontent.com/453543/236633180-a3151a0f-3b43-472b-b05d-99b3de929629.png)
