### ISSUE TITLE
README on Docker Hub not rendering correctly

### ISSUE THREAD

**Issue by amotl** [jpmens/mqttwarn#537]
Hi.

Currently, the rendering on https://hub.docker.com/r/jpmens/mqttwarn is a bit suboptimal. The patch from #536 didn't help. I don't actually know if there is reStructuredText allowed on Docker Hub? I remember from Kotori that I had to edit this file manually, having had to convert its README.rst into a README.md beforehand using Pandoc.

![image](https://user-images.githubusercontent.com/453543/122649369-cbed6b80-d12d-11eb-8ee9-7caf2f747356.png)

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear @jpmens,

given that the `mqttwarn` Docker images are published on GHCR these days, may I ask you if it would be a sane choice to remove the `mqttwarn` images from Docker Hub altogether? In this manner, we would not have to spend additional time figuring out how to update the README file over there.

As an additional bonus, people would get less confused, see #544 and #567.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi JP,

I was aiming to resolve all open issues labeled as https://github.com/jpmens/mqttwarn/labels/bug, so I am revisiting this. Sorry to bother you about it. May I ask what you think about my proposal?

With kind regards,
Andreas.

**Comment by jpmens** [comment]
Andreas, I have deleted the mqttwarn repository on Docker Hub.

**Comment by amotl** [comment]
Thank you very much for the prompt response.
