### ISSUE TITLE
[config:file] config params like overwrite are global only

### ISSUE THREAD

**Issue by Gulaschcowboy** [jpmens/mqttwarn#545]
Hi there,

it seems that the config params of the file plugin are global only. So this config

```ini
[config:file]
append_newline = True
overwrite = True
targets = {
    'f01'       : ['/tmp/f.01'],
    'log-me'    : ['/tmp/log.me'],
    'mqttwarn'  : ['/tmp/mqttwarn.err'],
    }
```

would set those params for all file targets.

It doesn't seem to be possible to configure those options on a per target level. Wouldn't this be a nice feature? ;-)

Dank u well

**Comment by amotl** [comment]
Dear Alexander,

thank you for writing in. I propose to add the possibility to have an alternative configuration section like that:
```ini
[config:file]
targets = {
    'f01'       : {'path': '/tmp/f.01', 'append_newline': True, 'overwrite': True},
    'log-me'    : ['/tmp/log.me'],
    'mqttwarn'  : ['/tmp/mqttwarn.err'],
    }
```

Around https://github.com/jpmens/mqttwarn/blob/0.26.2/mqttwarn/services/file.py#L21-L24, the code would then be like:
```python
# `item.addrs` is either a dict or a list associated with a particular target.
# While lists may contain more than one item (e.g., for the pushover target),
# the `file` service only allows for single items, the path name.
# When it's a dict, additional parameters can be obtained to augment the
# behavior of the write operation on a per-file basis.
append_newline = False
overwrite = False
if isinstance(item.addrs, dict):
    filename = addrs['path'].format(**item.data)
    append_newline = addrs.get('append_newline', False)
    overwrite = addrs.get('overwrite', False)
else:
    filename = item.addrs[0].format(**item.data)
```

Around https://github.com/jpmens/mqttwarn/blob/0.26.2/mqttwarn/services/file.py#L35-L38, it would be like:
```python
if type(config) == dict and 'append_newline' in config and config['append_newline']:
    append_newline = True
if type(config) == dict and 'overwrite' in config and config['overwrite']:
    overwrite = True

if append_newline:
    text += "\n"
if overwrite:
    mode = "w"
```

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear Alexander,

after you reported that you need to have 99 files to be overwritten, but 1 not, we refined the logic a bit. Now, global parameters are evaluated first and will effectively be specialized by per-item parameters.

See [`mqttwarn/services/file.py`](https://github.com/jpmens/mqttwarn/blob/00f79df1c7f53f25fc623340fa90c1bdf0b30d9c/mqttwarn/services/file.py) from #546.

As this patch is still untested, please let us know if this will work for you.

With kind regards,
Andreas.

**Comment by Gulaschcowboy** [comment]
Hi Andreas,

this patch works for me.

Thank you very much!
