### ISSUE TITLE
IRCcat service croaks

### ISSUE THREAD

**Issue by JanKoppe** [jpmens/mqttwarn#547]
Hi,

I have some issues configuring mqttwarn to talk to irccat. All of this runs in a Docker Swarm stack, so using hostnames would be preferred and should be possible as far as I can read in the Python `socket` module documentation.

I am configuring mqttwarn like this, pretty much exactly like the example in the handbook:

```
[config:irccat]
targets = {
    'noise': [ 'irccat', 12345, '#montage2-noise' ],
  }
```

In this case the irccat container is available under the hostname `irccat`.

When running such a configuration with `ghcr.io/jpmens/mqttwarn-full:0.26.2` (https://github.com/jpmens/mqttwarn/pkgs/container/mqttwarn-full/8273086?tag=0.26.2) and sending a notification, I am getting the following error:

```
INFO     [mqttwarn.commands        ] Starting mqttwarn
INFO     [mqttwarn.commands        ] Log level is INFO
INFO     [mqttwarn.core            ] Successfully loaded service "mattermost"
INFO     [mqttwarn.core            ] Successfully loaded service "irccat"
INFO     [mqttwarn.core            ] Starting 1 worker threads
INFO     [mqttwarn.core            ] Invoking service plugin for `irccat'
ERROR    [mqttwarn.services.irccat ] Error sending IRCCAT notification to noise:irccat [12345]: a bytes-like object is required, not 'str'
WARNING  [mqttwarn.core            ] Notification of irccat for `services/noise' FAILED or TIMED OUT
```

As the next step I manually resolved the `irccat` hostname to an IP address, and inserted that into the config. This led to the same error.

```
INFO     [mqttwarn.commands        ] Starting mqttwarn
INFO     [mqttwarn.commands        ] Log level is INFO
INFO     [mqttwarn.core            ] Successfully loaded service "mattermost"
INFO     [mqttwarn.core            ] Successfully loaded service "irccat"
INFO     [mqttwarn.core            ] Starting 1 worker threads
INFO     [mqttwarn.core            ] Invoking service plugin for `irccat'
ERROR    [mqttwarn.services.irccat ] Error sending IRCCAT notification to noise:10.0.21.7 [12345]: a bytes-like object is required, not 'str'
WARNING  [mqttwarn.core            ] Notification of irccat for `services/noise' FAILED or TIMED OUT
```

I don't have a good idea right now if I'm missing something super obvious, or this is just a bug in the code, or related to the Python environment in the Docker image.

Next up for me is trying to understand the code a little bit more and maybe do some debugging.

**Comment by amotl** [comment]
Dear Jan,

> I'm wondering if appending a newline in the code (e.g. additional `socket.send("\n".encode()))` would be in line with the project.

Apparently, other services are doing the same thing, see [`carbon.py#L59`](https://github.com/jpmens/mqttwarn/blob/0.26.2/mqttwarn/services/carbon.py#L59).

> Would you want me to create a Pull Request with my modifications?

I am already about to submit a corresponding patch. Thanks!

With kind regards,
Andreas.
