### ISSUE TITLE
Send Apprise/Discord notifications to another user

### ISSUE THREAD

**Issue by psyciknz** [jpmens/mqttwarn#555]
I Understand using appraise I can get discord notifications, but details are fairly light.

I’m after being able to send a discord message to a certain user. It won’t change. We won’t be connected to a discord server, but are friends.

Can someone give me some pointers.

**Comment by amotl** [comment]
> I’m looking at being able to send a discord message to a certain user.

Wait. Currently, from reading the documentation at [4], I can't see how you would send a message to _another_ user. Maybe the Apprise Discord notifier just aims to send messages to oneselves? Am I missing something?

/cc @caronc

[4] https://github.com/caronc/apprise/wiki/Notify_discord

**Comment by psyciknz** [comment]
> Dear @psyciknz,
> 
> good to hear you figured it out.
> 
> > I need a server and they must be a member"....I wonder. I have a server, but @sumnerboy12 is not a member, but I'll see if I can @ him from my server.
> 
> I believe the "right way" in this context would be to have different members in the same _channel_, as this _channel_ is addressed from the webhook, right?

Yeah that's how I expect it to work.  Ben shouldn't get my message or notification as he's not a member of my server.  But I'm wanting to message my son to get off the minecraft...discord is the only app I've allowed him, with no servers....but he can join the family one I've just made.
> 
> With kind regards, Andreas.

**Comment by psyciknz** [comment]
OK so if I have this right:
```
targets = {
   'discord-channel1'     : [ { 'baseuri':  'discord://4174216298/JHMHI8qBe7bk2ZwO5U711o3dV_js' } ],
   'discord-channel2'     : [ { 'baseuri':  'discord://4174216298/JHMHI8qBe7bk2ZwO5U711o3dV_js' } ],
],
   }
```

etc is how we could use it?

**Comment by amotl** [comment]
Dear Chris and @psyciknz,

thanks for your response.

> I'm not sure if I should add private messages to Discord; even their API kind of insists you don't do it.

Yes, I also believe we should not do it, unless being pressured hard.

> Otherwise it sounds like you've got a great alternative solution going too!

I also believe notifying a channel, where the users in question are members of, should be sensible as well. Did you have the chance to test the new feature already, @psyciknz?

With kind regards,
Andreas.

**Comment by psyciknz** [comment]
Hi @amotl 
Sorry, I just had a play then, seems to work well.  Had a few issues with updating mqttwarn in general.  Will make a new issue for that, but the apprise-multi worked well.

I need to work out the formatting.
![image](https://user-images.githubusercontent.com/5350515/139598511-37e368cf-422f-4119-a87e-d0dd0aa2907a.png)

Config
```
; -----------------------------------------
;             Discord via Apprise
; -----------------------------------------
[test/general]
targets = log:info, apprise-multi:discord_1
[test/test]
targets = log:info, apprise-multi:test
```
for the following pulish:
```
mosquitto_pub -t test/test -m "hello"
```

**Comment by psyciknz** [comment]
Oh and while I think about it, here's how you @ a user:
```
mosquitto_pub -t <discord apprise topic> -m "hello <@user_id> again"
```
So to get the user id, right click on the user and click copy id, it should be a numerical id.  It's not their text user name.

The exception to this rule is that sending a messages to @everyone does not require the id.

```
mosquitto_pub -t <discord apprise topic> -m "hello @everyone again"
```
should work.  No <> needed

**Comment by amotl** [comment]
Dear @psyciknz,

> The apprise-multi worked well.

Sweet, thanks for letting us know.

> Oh and while I think about it, here's how...

It would be nice to add some corresponding words to the documentation. Maybe you want to submit a patch?

With kind regards,
Andreas.

P.S.: Would `<@everyone>` work as well? If so, I would not see a need to add the remark that it also works without.

**Comment by amotl** [comment]
Dear @psyciknz,

I've just submitted #578, which improves the documentation with your feedback. I believe it is safe to close the issue now. Feel free to reopen if you think something has not been addressed well.

With kind regards,
Andreas.
