### ISSUE TITLE
Inconsistent instructions (docker)

### ISSUE THREAD

**Issue by psyciknz** [jpmens/mqttwarn#561]
Just trying to test and upgrade for #555 I pulled a new version, something I hadn't done for a while as I like to keep mqttwarn stable.

In the readme (for container image - https://github.com/jpmens/mqttwarn#container-image ) it says:
```
For running mqttwarn on a container infrastructure like Docker or Kubernetes, corresponding images are automatically published to the GitHub Container Registry (GHCR).

ghcr.io/earthobservations/wetterdienst-standard:latest
ghcr.io/earthobservations/wetterdienst-full:latest
```

I tried this and it really didn't seem to like it.    I couldn't get a run instance, and exec'ing into the container it couldn't seem to find the mqttwarn command.

But then in the hand book it says:
```
# The standard image on GHCR.
export IMAGE=ghcr.io/jpmens/mqttwarn-standard:latest

# The full image on GHCR.
export IMAGE=ghcr.io/jpmens/mqttwarn-full:latest

# The standard image on Docker Hub.
export IMAGE=jpmens/mqttwarn
```

So there's a bit of an inconsistency there.  The latter seems to work for GHCR

**Comment by amotl** [comment]
Dear @psyciknz,

thanks a stack for this report. I just fixed the documentation with #562.

With kind regards,
Andreas.
