### ISSUE TITLE
Connect to multiple MQTT brokers

### ISSUE THREAD

**Issue by tobru** [jpmens/mqttwarn#564]
As I understand it's currently only possible to connect to one MQTT broker and subscribe to topics there.

In my use case I have to connect to multiple MQTT brokers, or to the same broker but with different users. The use case I'm talking about is getting sensor data from [The Things Network](https://www.thethingsnetwork.org/) where each so-called application has its own username/password. See [the documentation](https://www.thethingsindustries.com/docs/integrations/mqtt/) for more information.

A possible way to implement that in the configuration file could be to have a section per broker and specify per subscription in which broker this subscription is available.

**Comment by jpmens** [comment]
Would several instances of mqttwarn solve the requirement?

**Comment by koenvervloesem** [comment]
There's another way to solve this, and this is how I'm doing it for The Things Network: configure a bridge in Mosquitto for each TTN application. You then just have to connect mqttwarn to one MQTT broker, but are able to subscribe to all topics from The Things Network. Here's an example configuration for Mosquitto: https://koen.vervloesem.eu/blog/bridge-the-things-network-to-your-local-mqtt-broker/

**Comment by tobru** [comment]
@jpmens Yes, that would be an option. The idea of @koenvervloesem is also solving my use case. Two options to choose from, thank you both very much.
