### ISSUE TITLE
Bump docker to latest

### ISSUE THREAD

**Issue by Sc0th** [jpmens/mqttwarn#567]
Hey,

Just wondering if it's possible to bump the docker image to 0.28.1, seems it's still running 0.26.1

Cheers!

**Comment by amotl** [comment]
Dear @Sc0th,

we switched gears to GHCR (GitHub Container Repository). There [^1], two flavors of images are published:
- `ghcr.io/jpmens/mqttwarn-standard:latest`
- `ghcr.io/jpmens/mqttwarn-full:latest`

We've updated the corresponding documentation [^2] with 97e2a6791.

With kind regards,
Andreas.

[^1]: https://github.com/jpmens?tab=packages&repo_name=mqttwarn
[^2]: https://github.com/jpmens/mqttwarn#container-image

**Comment by Sc0th** [comment]
Excellent, thank you :)
