### ISSUE TITLE
[Desktop] Migrate to `desktop-notifier`, deprecate `osxnotify`

### ISSUE THREAD

**Issue by portalzine** [jpmens/mqttwarn#569]
I have tweaked the osxnotify service to switch to Desktop Notifier, far better support and can be used cross plattform.
The current osxnotify service was not working for me on Monterey / Mac MINI. And well [pync](https://github.com/SeTeM/pync) is outdated :)

Would be nice, if that could be a core option for desktop notifications.
[Desktop Notifier](https://github.com/samschott/desktop-notifier)

**Comment by amotl** [comment]
Dear Alexander,

thank you for writing in. I think we can see what those alternatives can do to improve the situation?

- At [terkin-datalogger::tools/notify.py](https://github.com/hiveeyes/terkin-datalogger/blob/729bad3a9b391576f16087a4508fc49da245f80b/tools/notify.py), we conceived a cross-platform notifier the other day.
- Quickly searching on PyPI, I discovered the [desktop-notifier](https://pypi.org/project/desktop-notifier/) package.

What do you think about it?

With kind regards,
Andreas.

P.S.: Even better would be a Python package which provides desktop notifications for all the three major platforms Linux, macOS, and Windows. However, I did not do a thorough research about it, yet.

**Comment by portalzine** [comment]
Hi Andreas,
Thanks for looking into this ...

Desktop Notifier has perfect support for all desktop platforms:
[Desktop Notifier - Platform Support](https://desktop-notifier.readthedocs.io/en/latest/background/platform_support.html)

I have it running on OSX and Linux and will do a testdrive on windows this week.

Kind regards
Alexander

**Comment by amotl** [comment]
Hi again,

that sounds sweet. I probably missed to read about Windows support from `desktop-notifier`. Do you think you can submit a patch to add this as a new service plugin? Maybe [osxnotify.py] can be used as a blueprint.

With kind regards,
Andreas.

[osxnotify.py]: https://github.com/jpmens/mqttwarn/blob/main/mqttwarn/services/osxnotify.py

**Comment by portalzine** [comment]
You read my mind :) Already mapping it out as a service ;) and will gladly share when ready !
Cheers
Alexander

**Comment by amotl** [comment]
Dear Alexander,

before this will completely slip off our shared attention, may I humbly ask if there would be something to be shared? I think verifying the functionality on Windows may well be postponed.

With kind regards,
Andreas.

**Comment by portalzine** [comment]
Hi Andreas,
still on my radar and will hopefully have some time soon ...
Regards
Alexander

**Comment by portalzine** [comment]
Pull request is out, with a complete rewrite. Also proposed an update to the handbook.
Regards
Alexander

**Comment by jpmens** [comment]
@portalzine thank you very much for your contribution which I have approved and merged.
