### ISSUE TITLE
[file] System to rotate or truncate

### ISSUE THREAD

**Issue by zoic21** [jpmens/mqttwarn#622]
Hello,

Is it possible on file to configuration a rotate or truncate from mqttwarn ? Idea is to limit file size when we send mqtt to file.

Thank in advance,

**Comment by zoic21** [comment]
I run mqttwarn on docker on synology, I can do a truncate but it will be easier on mqttwarn directly

**Comment by jpmens** [comment]
It wouldn't be trivial to implement, and there's no need to as, following the Unix philosophy, there are already tools to do so.
