### ISSUE TITLE
Remove `gss` service plugin in favor of `gss2`?

### ISSUE THREAD

**Issue by amotl** [jpmens/mqttwarn#647]
Dear @jpmens, @sumnerboy12, @gumm, and @padelt,

I am currently doing some spring cleaning on mqttwarn, and wanted to humbly ask if the [gss] service plugin, based on the [gdata-python-client] package, which maintenance has ceased, actually stopped working anyway, and has been superseded by [gss2] completely?

With kind regards,
Andreas.

[gss]: https://mqttwarn.readthedocs.io/en/latest/notifier-catalog.html#gss
[gss2]: https://mqttwarn.readthedocs.io/en/latest/notifier-catalog.html#gss2
[gdata-python-client]: https://github.com/google/gdata-python-client

**Comment by sumnerboy12** [comment]
I have no idea sorry. I don't use that plugin.

**Comment by jpmens** [comment]
I think we should drop it completely.

**Comment by amotl** [comment]
Thanks. It will be dropped with 3fecc080a.
