### ISSUE TITLE
Logo required

### ISSUE THREAD

**Issue by jpmens** [jpmens/mqttwarn#81]
Anybody around who would care to create a square logo for mqttwarn? Perhaps one of you has a graphics artist spouse with an hour to spare whilst watching TV or something? :-)

It can contain the text "mqttwarn" but maybe need not.

**Comment by gumm** [comment]
A first shot at something. Uses every trick in the book: Combination of letters. An exclamation mark to increase the volume and orange - that most urgent of warning colours. Oh, and also the very hipster flat shadow effect.

![mqttwarn_logo_flat](https://cloud.githubusercontent.com/assets/2345521/6315029/9b53da76-b9fc-11e4-801e-8bd24c03af00.png)
![mqttwarn_wordmark](https://cloud.githubusercontent.com/assets/2345521/6315030/a469b41e-b9fc-11e4-96b0-6648314e1e38.png)

**Comment by gumm** [comment]
![mqttwarn_logo_flat2](https://cloud.githubusercontent.com/assets/2345521/6316050/269bcfe0-ba1f-11e4-9627-50571ecc6912.png)

**Comment by jpmens** [comment]
@gumm Neat, good job! 
For some reason I'm seeing more NN than MW though .. I'll have to think a bit about this. I like the white on orange, and the 3rd with the orange exclamation mark.

**Comment by gumm** [comment]
I agree. The NN seems to jump out. Not sure this is it yet...

**Comment by gumm** [comment]
Interestingly, if you slant the exclamation mark the other way, the NN becomes less prominent.

![mqttwarn_logo_6](https://cloud.githubusercontent.com/assets/2345521/6320103/47e69be8-bade-11e4-9b8c-d41ba6e5fd91.png)

![mqttwarn_logo_5](https://cloud.githubusercontent.com/assets/2345521/6320105/4dd7a826-bade-11e4-9a61-72aa163a40a9.png)

And here are some variations on the theme. 

![mqttwarn_logo_3](https://cloud.githubusercontent.com/assets/2345521/6320108/56e0c218-bade-11e4-9ec3-d45302401276.png)

![mqttwarn_logo_4](https://cloud.githubusercontent.com/assets/2345521/6320109/5cb2f918-bade-11e4-82c6-26770e94419d.png)

**Comment by justinatomatic** [comment]
This appeared on my feed today https://twitter.com/museumweek.
Apparently a common way to treat the MW combination. 
![natgalleryaus_2015-feb-23](https://cloud.githubusercontent.com/assets/3860848/6323254/113aa0f6-bb7b-11e4-85cc-8b7d9006e86f.jpg)

**Comment by jpmens** [comment]
You're on  the right track, @gumm I'm liking this one 
![](https://cloud.githubusercontent.com/assets/2345521/6320105/4dd7a826-bade-11e4-9a61-72aa163a40a9.png)

Not quite convinced yet, (sorry!), also because of what @justinatomatic says

**Comment by matbor** [comment]
![1291658909 1](https://cloud.githubusercontent.com/assets/1978503/6938657/e16b2ed8-d8b0-11e4-8b91-8ef707114b3c.png)

Was looking at signs from openclipart, maybe this one but change background to a blue...  

I do like the name of it ;)
https://openclipart.org/detail/99661/psychohazard

**Comment by jpmens** [comment]
@gumm wins this with the one I mentioned above. Thank you, and it'll be in the next release. (@amotl made me think about this again :-)

**Comment by amotl** [comment]
Bump. I would also like to thank @gumm for the logo design. By making an official release on https://pypi.org/project/mqttwarn/ (#127), it has become the official logo for *mqttwarn* from now on.

**Comment by jpmens** [comment]
@gumm Thank you once again for your contribution: much appreciated. May we kindly ask you to provide a larger image with a higher resolution?, maybe as a PR?

**Comment by amotl** [comment]
Hi there,

is #387 provided by @gumm (thanks again!) sufficient to close this issue?

With kind regards,
Andreas.

**Comment by jpmens** [comment]
Closing
